### ISSUE TITLE
binary info not included?

### ISSUE THREAD

**Issue by speters** [earlephilhower/arduino-pico#1003]
Thx for the arduino-pico framework!

I tried to include binary info metadata in my program, but I am unable to find this info in the uploaded code.
```
[...]
#include <pico/binary_info.h>
[...]
void setup()
{
  bi_decl(bi_program_name("myprogram"));
  [...]
```

`picotool info -a` does not show any info after uploading to the PiPico.
When I do a `strings firmware.* | grep 'myprogram'` there is also nothing found.

Compilation is done via the Platformio setup from the docs (had to manually remove arduino-mbed framework as pio kept preferring this).

I am hoping for a hint of a solution...

**Comment by earlephilhower** [comment]
Binary info is not supported in the Arduino core.  Because we use a multi-stage bootloader (for OTA support), the Pico SDK tools cannot properly use any info we'd include from then last-stage real app binary.

**Comment by kilograham** [comment]
@earlephilhower Feel free to comment on https://github.com/raspberrypi/picotool/issues/82 which is something i'd been thinking about for a while
