### ISSUE TITLE
Unable to use WiFi with `WizFi360-EVB-Pico` board

### ISSUE THREAD

**Issue by ggardet** [earlephilhower/arduino-pico#1018]
I am unable to use WiFi with `WizFi360-EVB-Pico` board. I suspect the board support is missing WiFi since compilation fails with `WiFi.begin()` unknown:
```
undefined reference to `_ZN9WiFiClass5beginEPKcS1_'
collect2.exe: error: ld returned 1 exit status
```

**Comment by earlephilhower** [comment]
You are correct, the built-in WiFi is only for the PicoW.  You will need to se the WizNet WiFi libraries to use that part of your device.

**Comment by maxgerhardt** [comment]
Specifically, https://github.com/Wiznet/WizFi360-EVB-Pico-C.
