### ISSUE TITLE
Arduino-pico and external EEPROM

### ISSUE THREAD

**Issue by fletchjp** [earlephilhower/arduino-pico#1025]
I am attempting to connect an external EEPROM AT24C256 to a Raspberry Pi Pico using I2C via pins GP6 and GP7.

A scan for the I2C device finds 0x50 and 0x58 as on other hardware (e.g. Arduino DUE).

Write apparently succeeds and read fails.

I am using the latest Arduino-Pico 2.6.4. and Arduino IDE 1.8.19.  I am using Wire1 and pins GP6 and GP7.

Do you have any relevant examples?

Thanks

John

**Comment by earlephilhower** [comment]
Sorry, no.  As this is a general programming Q, I'm moving to a discussion for followup.  I'd suggest looking at some of the existing Arduino libraries for talking to your chip for starters...
