### ISSUE TITLE
Pico W connects to Wifi only every second boot

### ISSUE THREAD

**Issue by jokinghands** [earlephilhower/arduino-pico#1031]
Im trying to connect over C++ / Arduino IDE
If i take the Example code it would connect only every second boot. No matter if just flashed or Hardreset:

     WiFi.mode(WIFI_STA);
      WiFi.begin(ssid, password);
      Serial.println("");
    
      while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
      }

If I write it that way it would always conntect skipping the first try.

    WiFi.begin(ssid, password);
      if (WiFi.waitForConnectResult() != WL_CONNECTED) {
        Serial.printf("STA: Failed!\n");
        WiFi.disconnect(false);
        delay(1000);
        WiFi.begin(ssid, password);
      }

it works with a while loop aswell. But he doesnt need more the a second attempt.

Anyone any Ideas? I guess its something about the router, i never experienced this with any ESP.

Thanks!

**Comment by brentru** [comment]
Having a similar issue with the same code. @earlephilhower  Any ideas/advice for further debugging?

**Comment by brentru** [comment]
Not running into the same issue with the `WiFiClient.ino` example, https://github.com/earlephilhower/arduino-pico/blob/master/libraries/WiFi/examples/WiFiClient/WiFiClient.ino. Possibly an issue with setting `WiFi_STA`?

**Comment by earlephilhower** [comment]
I've noticed that, depending on the state of the moon and whether or not it was already connected, the CYW43 chip onboard the Pico can take a long time to connect to an AP in my own setup.

My hunch is that you're just timing out for this reason.  Please add
````
WiFi.setTimeout(20000); // 20 sec to connect before giving up
````
before your `WiFi.begin()` and try again and report back, please.  I can always bump out the timeout if it's just a matter of that and others have even slower connections than myself...

**Comment by StefanKellerAC** [comment]
Yes, it often fails "finally" with WL_CONNECT_FAILED.
I can reliably connect with this code after some seconds:

```
  int NTries = 99; 
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  int Status =  WiFi.status();
  while ( Status != WL_CONNECTED && NTries-- > 0) {
    Serial.printf ("NTries: %d, status: %d\n",NTries,Status);
    if (Status == WL_CONNECT_FAILED)
      {
      Serial.println("retry:");
      WiFi.begin(ssid, password);
      }
    else  
      delay(1000);
    Status = WiFi.status();
    }

  IPAddress myIP = WiFi.localIP();
  Serial.println(myIP);
```

**Comment by washburnit** [comment]
I'm experiencing the same thing, most of the time it connects to my AP (Unifi UAP AC Lite) within 5/6 secs.
When it doesn't connect I have to reset it and then it connects.
On the "connected devices" page of the AP when it tries to connect it is displayed with its mac address as name, and stays there until it connects succesfully (then the name changes to "PicoW").

**Comment by RickSeiden** [comment]
I don't know if this is relevant, but I noticed that it won't connect to serial until the serial monitor is open.  So if I have an

while (!Serial);

statement in my code, it never connects to the AP because it never gets past waiting for Serial to connect.
