### ISSUE TITLE
Upload works fine, but IDE is stuck on "Uploading..." since a few days

### ISSUE THREAD

**Issue by darkBuddha** [earlephilhower/arduino-pico#1047]
Hi, thanks for this great library. I used it a few months, suddenly I get no Serial connection to my Pico W. Flashing works just fine, but the Serial Monitor stays empty, and the IDE doesn't realize the upload is finished. Any ideas what the reason could be? Maybe an update of some component?

I use

- Pi Pico W
- macOS 13.1 (Ventura)
- Arduino IDE 2.0.3
- arduino-pico 2.6.4

I tried with TinyUSB as well, to no sucess. I am observing it on different 2 Pico Ws.

Thanks for every hint!

**Comment by maxgerhardt** [comment]
>macOS 13.1 (Ventura)

There's some talk about that in #971, maybe related?

Do alternative upload methods with `picotool` work?

**Comment by maxgerhardt** [comment]
And the serial doesn't work even for the sketch
```cpp
void setup() { Serial.begin(9600); }
void loop() {}
```
no matter if you have the Pico USB stack or TinyUSB selected as your USB stack? (Tools->USB)
