### ISSUE TITLE
lib about timers interrupts like Khoi Hoang >> https://github.com/khoih-prog/RPI_PICO_TimerInterrupt

### ISSUE THREAD

**Issue by karadevnet** [earlephilhower/arduino-pico#1052]
hi, like all world and i use your lib about RPI PICO 2040 but nowhere in pdf i can not see some about timers interrupt like this lib >>> lib about timers interrupts like Khoi Hoang >> https://github.com/khoih-prog/RPI_PICO_TimerInterrupt

are you plan to make some or is still in develop ? best regards for all your work <> www.karadev.net

**Comment by earlephilhower** [comment]
Sorry, if you have a question about Khjoi's lib you will need to open up an issue/discussion there.
