### ISSUE TITLE
ili9341

### ISSUE THREAD

**Issue by fredykoci** [earlephilhower/arduino-pico#1057]
![Snímek obrazovky 2022-12-21 v 16 37 22](https://user-images.githubusercontent.com/18038918/208943606-e6ad7aab-c36c-4c9b-9839-e032a5c22a3f.png)

There is screen from my code. The screen with this configuration can not display anything. but if I manualy set SPI pins then it works. But I need to use SPI for mcp2515. Is there any help?

**Comment by earlephilhower** [comment]
Sorry, for help with Adafruit libs you should really go to its repo.
