### ISSUE TITLE
1-Wire not working

### ISSUE THREAD

**Issue by weigu1** [earlephilhower/arduino-pico#109]
Hi,
I get a warning that the lib is using the Fallback mode:

<In file included from /home/pi/Arduino/libraries/OneWire/OneWire.cpp:144:
/home/pi/Arduino/libraries/OneWire/util/OneWire_direct_gpio.h:416:2: warning: #warning "OneWire. Fallback mode. Using API calls for pinMode,digitalRead and digitalWrite. Operation of this library is not guaranteed on this architecture." [-Wcpp]
  416 | #warning "OneWire. Fallback mode. Using API calls for pinMode,digitalRead and digitalWrite. Operation of this library is not guaranteed on this architecture.">

And I can't access the DS18B20 trough the library.
Any help is appreciated.

Greetings

**Comment by earlephilhower** [comment]
Sorry, that's a 3rd party library that has not been ported to the RP2040.  Nothing we can do here

You might want to attempt to do the port and submit a PR to the author since it's important to you.  I'm sure that's how the other ports got into the codebase.

Good luck.

**Comment by weigu1** [comment]
Thanks :)
