### ISSUE TITLE
testing for rp2040?

### ISSUE THREAD

**Issue by reppr** [earlephilhower/arduino-pico#110]
To determine the processor the code gets compiled for I use pp macros like
#if defined ESP32
#if defined  __SAM3X8E__
...

How can I find out if I am compiling for an rp2040 processor (or a raspberry pico board)?

**Comment by earlephilhower** [comment]
`#ifdef ARDUINO_ARCH_RP2040` will work.  Good luck.

**Comment by reppr** [comment]
thanks a lot
very useful
