### ISSUE TITLE
HID Keyboard Unable to print the character

### ISSUE THREAD

**Issue by VuDuc09** [earlephilhower/arduino-pico#1106]
Hello,
I use a adafruit macropad rp2040, 
my aim is to create a numpad. But when I assigned the keys to the pins, one of them couldn't be printed to the screen ex number 8. The pins work perfectly because when I test to print to serial console it's work. Is anyone like me? Is that a character key error?

**Comment by earlephilhower** [comment]
You will need to post code to reproduce the failure for anyone to help you.   The keyboard library runs fine when sending '8's, as far as I can tell.  Replacing `A` with `8` in the `KeyboardPassword.ino` example works fine:
````
/* Released into the public domain */
/* Earle F. Philhower, III <earlephilhower@yahoo.com> */

#include <Keyboard.h>

void setup() {
  Serial.begin(115200);
  Keyboard.begin();
  delay(5000);
  Serial.printf("Arduino USB Password Typer\n");
  Serial.printf("Press BOOTSEL to enter your super-secure(not!) password\n\n");
}

void loop() {
  if (BOOTSEL) {
    Serial.println("Typing password for you...shhhh....");
    Keyboard.print("ThisPasswordIsWeakLike8Baby");
    while (BOOTSEL);
  }
}
````

<pressing the BOOTSEL>...ThisPasswordIsWeakLike8Baby
