### ISSUE TITLE
Support for chinese YD-2040 boards?

### ISSUE THREAD

**Issue by prosper00** [earlephilhower/arduino-pico#1109]
Any appetite to add support for the inexpensive Chinese boards that came on the market a year or so ago? 
See https://www.aliexpress.com/item/1005004004120604.html

Documentation (schematics, BOM, pinout) (provided by the seller) attached:
[YD-2040-2022-V1.1-SCH.pdf](https://github.com/earlephilhower/arduino-pico/files/10396038/YD-2040-2022-V1.1-SCH.pdf)
![YD-2040-PIN](https://user-images.githubusercontent.com/57373245/211920388-d339f085-840d-433d-a575-590ace58219c.png)
![YD-RP2040-Inch-SIZE](https://user-images.githubusercontent.com/57373245/211920391-5d389e2e-92d6-48ab-b440-bc0ab6f3465d.jpg)
[YD-RP2040-Inch-SIZE.pdf](https://github.com/earlephilhower/arduino-pico/files/10396039/YD-RP2040-Inch-SIZE.pdf)
![YD-RP2040-Metric-SIZE](https://user-images.githubusercontent.com/57373245/211920392-dc9787a8-d514-48fb-a055-5a6af82bd5a5.jpg)
[YD-RP2040-Metric-SIZE.pdf](https://github.com/earlephilhower/arduino-pico/files/10396040/YD-RP2040-Metric-SIZE.pdf)

**Comment by earlephilhower** [comment]
That's very simple to do, but without having some to test I'm not sure what the actual flash should be in the board definition.  The BOM is one thing, but do we really know what is actually being stuffed on the board?

Do you have some in hand to test?  If so, could you try the `Generic` board and go thru the different flash options (i.e. load blink.ino, set boot stage 2 to A/4, upload and run, set boot stage 2 to A/2, upload and run, etc.) . Some will work, others will fail to boot  I'm thinking the `W25Q64JV /2` or `/4` will be the right one given the BOM.

**Comment by prosper00** [comment]
I don't have an option for W25Q64JV /2 - but W25Q16JVxQ /4 and W25Q64JV /4, and 'Generic SPI /2 and /4' options all work for the 4MB and 16MB models.

**Comment by tistructor** [comment]
The files and the "variant" folder for this board have not been created

**Comment by earlephilhower** [comment]
Yeah, sorry.  Just added!
