### ISSUE TITLE
Library description for Arduino IDE

### ISSUE THREAD

**Issue by sstaub** [earlephilhower/arduino-pico#1111]
The board description is nearly unreadable in the Arduino IDE 2.x. It is too long so you need endless scrolling to see other boards.
<img width="1414" alt="Bildschirm­foto 2023-01-12 um 13 02 31" src="https://user-images.githubusercontent.com/6450325/212061991-3d8ad308-fb40-404c-9407-bb70d0393f96.png">

**Comment by Phoenix1747** [comment]
Most importantly this makes it impossible to click the "Install" button, because it will be pushed out of the window. But this is more of a general problem for the Arduino IDE, I think. Just writing for completeness.

**Comment by sstaub** [comment]
@Phoenix1747 I seen this also on WIN10 when look to updateable boards and the pico is the last item.

**Comment by maxgerhardt** [comment]
It seems to be ignoring the `boards` array of the package index json though, as seen [here](https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json) that only declares
```json
          "boards": [
            {
              "name": "Raspberry Pi Pico"
            },
            {
              "name": "Raspberry Pi Pico W"
            },
            {
              "name": "Adafruit Feather RP2040"
            },
```
Aka not with every combination of `(pico-debug)`, `(Picoprobe)` and without it. Seems to be reading it straight from the `boards.txt`.

But if that's the case, then that cannot be made smaller without throwing board definitions out or restructuring it.
