### ISSUE TITLE
Is it possible to add WPA2 enterprise?

### ISSUE THREAD

**Issue by syedzayyan** [earlephilhower/arduino-pico#1124]
MicroPython has never added support for this, and I was hoping if it would be possible to add it here of it its already supported.

Edit:

I saw it as a Todo in WiFiClass.h, could this be a possibility in the very near future?

**Comment by earlephilhower** [comment]
Sorry, this needs support from the binary WiFi blob that just isn't there.  Your best bet is to open up something on the Pico-SDK repo and see if they can help enable support.  It's not something we can do unilaterally here unfortunately.
