### ISSUE TITLE
WiFi.isConnected ?

### ISSUE THREAD

**Issue by kakopappa** [earlephilhower/arduino-pico#1165]
Hi, 

Just wondering what's the reason behind naming `WiFi.connected()` rather `WiFi.isConnected` which how it's being done in ESP8266/ESP32

Right now we have to do this.
```   
  #if defined(ESP32) || defined(ESP8266)
      isWiFiConnected = WiFi.isConnected();
  #elif defined(ARDUINO_ARCH_RP2040)
      isWiFiConnected = WiFi.connected();
  #endif

```

**Comment by earlephilhower** [comment]
`WiFi.connected()` is the "official" Arduino WiFi.h call, which is the template I used when writing the core.  That said, I've been adding helper calls to make porting ESP8266 code simpler, and #1166 will add `WiFi.isConnected()` (which just calls `WiFi.connected()` behind the scenes).
