### ISSUE TITLE
Working SD card example uploaded

### ISSUE THREAD

**Issue by DingoOz** [earlephilhower/arduino-pico#1172]
The current examples for the SD Card don't appear to work due to pin allocation (vis-a-vis the SPI0 ports).

I was not sure of the etiquette re updating the Arduino examples. Rather than trying to do a PR and causing an issue I have created a separate repository for a working example:

https://github.com/DingoOz/pico-sd-card-example

All this does is ask the excellent existing library (where all the work has taken place) to use the SPI1 pins on the Pico and a Chip Select of 13.

I tweaked the code a little to make the serial messages a bit more logical (to me) too.

I had not been able to find a working example using the SDFS library (of the SD wrapper for it) so here it is.

If I ought to have submitted a PR against this repository let me know and I'll do that too.

**Comment by earlephilhower** [comment]
I was just working w/the SD examples this weekend, funnily enough!

Yes, the comments are still from the original Arduino AVR-style I think and should be updated.  There's no need to use SPI1 like in your example, and the pins themselves will vary depending on the board in use so I'll throw in some constants and comments to explain.
