### ISSUE TITLE
mDNS on Pi Pico W

### ISSUE THREAD

**Issue by specialcircumstances** [earlephilhower/arduino-pico#1176]
Just looking to validate something really....

I'm trying to resolve a name using mDNS on Pi Pico W.

I've installed this lib: https://github.com/khoih-prog/MDNS_Generic

Also: 
```

#include <DigitalIO.h>
#include <PsxControllerBitBang.h>
#include <avr/pgmspace.h>

#include <WiFi.h>
#include <WiFiUDP.h>
#include <SPI.h>
#include <Adafruit_ILI9341.h>
#include <MDNS_Generic.h>
#include <MDNS_Generic.hpp>

etc

WiFiUDP udp;
MDNS mdns(udp);

etc
```

I can see the mDNS query being sent and the almost immediate reply (through Wireshark), and all looks well, but the resolver fails when the handler is called (no ip, rather than timeout).

I'm just wondering if there is any (obvious) reason why the multicast listener in your WiFiUDP would not work with this library?

Thanks

**Comment by earlephilhower** [comment]
Sorry, you'll need to bring this up in Khoih's repo.  I haven't worked with his stuff, but I know he does a lot of work to make things cross-platform.  This might just be one he hasn't ported yet.

FWIW there's `LEAmDNS` already as part of this repo, tested and working and used in several of the examples.
