### ISSUE TITLE
Serial1 and Serial2 does not work in multicore.

### ISSUE THREAD

**Issue by chester2400** [earlephilhower/arduino-pico#1203]
I have a program that one core dose the computing and second core takes care of display with TFT_eSPI library.
In loop0 i have a serial1 sending data to other device and there is no signal on the scope. I have to put core1 to sleep to see the outgoing data. I tryed using SepialPIO there is no diferance.  The SPI on second core makes the Serial1 have no signal. Without SPI it works ok.

**Comment by earlephilhower** [comment]
Please make and post a small MCVE sketch that reproduces the failure w/o the extra 3rd party libraries.  Without that, there's nothing we can even look at here.

**Comment by chester2400** [comment]
Its not the multi core problem. Its the TFT_eSPI library. It pulls pin 0 high.

**Comment by earlephilhower** [comment]
You can change the pins using `Serial1/2.setRX/setTX` to move it them to different pins.  Be sure the selected pins are legal for the hardware (see https://learn.adafruit.com/assets/99339 )
