### ISSUE TITLE
Crash on ISR with pin13

### ISSUE THREAD

**Issue by Hasenpups** [earlephilhower/arduino-pico#1212]
Hello, 

A call of ISR on Pin13 will force a crash of the pi pico w. 

This minimal sample can be used to force the error: 

```
void setup()
{
  attachInterrupt(13, pin13ISR, FALLING);

  Serial.begin(115200);
}

void loop() {
  delay(500);
  Serial.println("I'm alive");
}

void pin13ISR() {
  Serial.println("crash");
};
```

Other pins like 10, 11, 12, 14, 15, 16, 17 work without any problems. 

The crash only happens when compiling as Pi Pico W, if Pi Pico is used it is running without any problems. 
Used hardware plattform: Pi Pico W

**Comment by earlephilhower** [comment]
This looks to be SDK related.  SDK1.5 does not crash, while SDK1.4 does.  There were many changes to the CYW43 driver, this was probably one of them.  Fixed by #1167
