### ISSUE TITLE
Should I use SPI or SPI1 in the program?

### ISSUE THREAD

**Issue by jinyistudio534** [earlephilhower/arduino-pico#1215]
https://shop.sb-components.co.uk/products/raspberry-pi-pico-hat-expansion?_pos=9&_sid=155b6beff&_ss=r
![image](https://user-images.githubusercontent.com/121013147/220228576-1d841553-934d-475e-b9ac-30749714d03a.png)

When I want to use GP2~GP5 (SPI,PICO side) in the figure, Should I use SPI or SPI1 in the program?

**Comment by earlephilhower** [comment]
When in doubt about pinouts, check this image to verify: https://learn.adafruit.com/assets/99339
![image](https://user-images.githubusercontent.com/11875/220422886-34f12886-5427-4eb1-af5a-de137ea79a6c.png)

GP2-5 are `SPI`, not `SPI1`.

**Comment by jinyistudio534** [comment]
`SPI.setCS(5);
  SPI.setSCK(2);
  SPI.setRX(4);
  SPI.setTX(3);`

I have connect a spi device to GP2~GP5. Why do i need to specify the pin position in the above program when using SPI in the program? If not specified, SPI cannot communicate

**Comment by earlephilhower** [comment]
It depends on your board.  Those pins may not be the default ones for it (many peripherals can come out on many different pins on the RP2040).
