### ISSUE TITLE
New compilation error from 2.7.2 to 2.7.3

### ISSUE THREAD

**Issue by Raphael-Boichot** [earlephilhower/arduino-pico#1221]
Hello !

I'm using you excellent and versatile library for this project : https://github.com/Raphael-Boichot/Mitsubishi-M64282FP-dashcam

Everything went fine until I updated from 2.7.2 to 2.7.3 today (same installation on my system). I got this error message when compiling :

"C:\\Users\\BOICHOT\\AppData\\Local\\Arduino15\\packages\\rp2040\\tools\\pqt-python3\\1.0.1-base-3a57aed/python3" -I "C:\\Users\\BOICHOT\\AppData\\Local\\Arduino15\\packages\\rp2040\\hardware\\rp2040\\2.7.3/tools/signing.py" --mode header --publickey "F:\\Personnel\\Projets divers\\2023-01-18 Pi pico dashcam\\2023-02-22\\Mitsubishi_M64282FP_dashcam/public.key" --out "C:\\Users\\BOICHOT\\AppData\\Local\\Temp\\arduino_build_210128/core/Updater_Signing.h"
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

When reversing to 2.7.2, no issue again...

Do you have an idea of the issue ?

Regards

Raphaël

**Comment by earlephilhower** [comment]
This is an IDE installation issue.  Sometimes the unpacking of the Python3 standalone interpreter stops in the middle, leaving files missing.  2.7.3 had a new toolchain hence the chance of the IDE failing.

Try completely removing the Arduino-Pico core from the boards manager and re-installing.  You may also need to manually go and delete the partially unpacked directory `C:\Users\BOICHOT\AppData\Local\Arduino15\packages\rp2040\tools\pqt-python3\1.0.1-base-3a57aed/python3` if the board manager uninstall/reinstall doesn't work.

**Comment by Raphael-Boichot** [comment]
Thanks !
