### ISSUE TITLE
MacOS: Board Info does not show correct VID & PID (and serial monitor is not working as well)

### ISSUE THREAD

**Issue by Papirosnik** [earlephilhower/arduino-pico#1231]
- MacOS Ventura 13.2.1
- Apple M1 Pro
- Arduino IDE 2.0.3
- Arduino-picp v.2.7.3

<img width="603" alt="image" src="https://user-images.githubusercontent.com/1651549/221438509-bf85b782-6bd3-4b68-8ace-c74c88d22000.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/1651549/221438534-6f94c295-c435-489f-acc1-dcb4622d440d.png">

While they are visible in system:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/1651549/221439335-9f07400e-ac7f-4d76-8c45-e88cd03e4c4b.png">

(BTW, for Arduino Mbed OS RP2040 board the info shows correctly)
<img width="314" alt="image" src="https://user-images.githubusercontent.com/1651549/221439472-0718d2f3-1547-4365-ab0a-334b79d235ba.png">

Here is my simple sketch. It definitely works (the led is blinking at least) and is supposed to  write to serial port as well. 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1651549/221439540-7836dcb5-9ab8-473c-bb7d-cf51fa039134.png">

But it either does not or I cannot see its ouput.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/1651549/221438830-5f8721c9-3cb6-46ce-87a9-f28d93e0bd80.png">

Screen command gives an empty screen

![image](https://user-images.githubusercontent.com/1651549/221439111-14e86346-eeea-429f-8212-ca0e91b21251.png)

So, can someone confirm that Serial facilities are working with Pico on Mac?
Any ideas how to treat that?

**Comment by earlephilhower** [comment]
As far as the IDE issue, that's something that works fine in 1.8.x and got broken when they moved to the new IDE.  It's not a big issue but if you do have a solution, a PR would be welcome.

I'm not a Mac user, but for the USB port, if you cannot manually choose the existing USB port from the IDE menu then I would guess you have a permission problem.  Either the app or the user isn't allowed to see the port, even though it's `rw` for everyone.  You'll need to find a Mac user to get more info on setting their equivalent of `udev` rules/etc. if such a thing exists.

**Comment by earlephilhower** [comment]
No response in a week, closing.

**Comment by Papirosnik** [comment]
Hah!
I've just read these messages on already closed thread and decided to try one more time.
I read this [stuff](https://www.stoneitech.com/raspberry-pi-pico-tutorial/#:~:text=The%20default%20baud%20rate%20is,similar%20to%20COM1%20in%20windows.) and thought about that `enable_uart=1` option, although had no idea if it is pico-related actually.
And suddenly and magically everything started working as expected :)
Probably, the issue was in my connected peripheria. This time I tried without any pins connected - the micro-usb cable only.
And voila!
<img width="270" alt="image" src="https://user-images.githubusercontent.com/1651549/223551798-9c643fec-5d95-4b72-aca6-1d3274c2f737.png">
And serial port is working properly and I can see its output.
