### ISSUE TITLE
Pi Pico with large Flash

### ISSUE THREAD

**Issue by akhodeir** [earlephilhower/arduino-pico#1262]
Standard Pi Pico has 2 MB of flash.
I have a clone wich has 16 MB of flash, is it possible to modify your code to reflect the real flash that I have? 

standard : 
```
Sketch uses 52532 bytes (2%) of program storage space. Maximum is 2093056 bytes.
Global variables use 8964 bytes (3%) of dynamic memory, leaving 253180 bytes for local variables. Maximum is 262144 bytes.
Resetting /dev/ttyACM0
Converting to uf2, output size: 138240, start address: 0x2000
```

**Comment by earlephilhower** [comment]
Use the `Generic` board where you can set the flash size thru the menus, or maybe you have a `VCC-GND` one in which case select that from the menus.
