### ISSUE TITLE
Layout and Schematic

### ISSUE THREAD

**Issue by akhodeir** [earlephilhower/arduino-pico#1263]
I see when I save sketches that the layout and schematic are still not reflecting Pi Pico hardware.

is there any thing that I can help you to achieve correct drawings ?

![layout](https://user-images.githubusercontent.com/42145977/222928254-9a0c3f54-1dd2-44ad-bbce-a8ff8dee254c.png)
![schematic](https://user-images.githubusercontent.com/42145977/222928258-b4131b1e-f9bd-42c7-88cb-e6905241ff28.png)

**Comment by earlephilhower** [comment]
Sorry, I have no idea what tool you're using but it's not related to the core here.  Closing.  I suggest opening an issue on the tool's repo instead.
