### ISSUE TITLE
Use HTTPClient with EthernetClient W5500-EVB-Pico

### ISSUE THREAD

**Issue by martinerk0** [earlephilhower/arduino-pico#1282]
It seems that HTTPCLient: https://github.com/earlephilhower/arduino-pico/tree/master/libraries/HTTPClient library is using WiFiClient.h
I would like to use it with ethernet on W5500-EVB-Pico which I suppose would not work as it is now.
Would it be possible to rewrite it so it would be usable with W5500-EVB-Pico's ethernet?

Thanks

**Comment by martinerk0** [comment]
It seems [ArduinoHttpClient](https://github.com/arduino-libraries/ArduinoHttpClient) is working with W5500-EVB-Pico, why is there a separate [HTTPClient](https://github.com/earlephilhower/arduino-pico/tree/master/libraries/HTTPClient) library 🤔?

**Comment by earlephilhower** [comment]
Looks like you've found a solution, so let's close this.  As far as why we have our own HTTPClient, it's because it works better with the WiFi interface and is more compatible w/the ESP8266 and ESP32 infrastructures (probably the de-facto WiFi Arduino cores).  Good luck!

**Comment by sdrshnptl** [comment]
Hi @martinerk0 
Have you able to solve problem?
