### ISSUE TITLE
Advanced templating not supported with this version of gcc ?

### ISSUE THREAD

**Issue by qbolsee** [earlephilhower/arduino-pico#1291]
Hi Earle,

Thanks for all the great work. We've been trying to use advanced templating at my lab, and the following snippet doesn't compile:

```c++
template<typename T, unsigned length>
class Array {
  public:
    T val[length];
    size_t len = length;
};

template<typename T>
class TypeHelper {
};

template<>
template<typename T, unsigned length>
class TypeHelper<Array<T, length>> {
};

void setup() {
}

void loop() {
}
```

The error is:

```error
template-of-template:14:7: error: too many template-parameter-lists
   14 | class TypeHelper<Array<T, length>> {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
exit status 1
too many template-parameter-lists
```

The same snippet compiles fine on the Arduino AVR toolchain with `AVR gcc 7.3.0-atmel3.6.1`, and the Arduino SAMD toolchain with `arm gcc 7-2017q4`. Could this be advanced feature only found in more recent gcc versions?

**Comment by earlephilhower** [comment]
> Could this be advanced feature only found in more recent gcc versions?

I think it may be the opposite, in fact.  We're at GCC 10.3 and `-std=gnu++17` which is probably a newer spec than the AVR compiler is set to (it's the `-std=xxx` which sets the behavior here more than the GCC version).

I'm not quite sure what you're trying to get to w/the example, but looking on S.O. there seems to be a different legal way of specifying the multiple levels which I think is the crux here.

Unfortunately, nothing to do here in the core related to this.  We may move to GCC 12 at some point (4.x?) and `-std=gnu++20` at some point, but that would not change things WRT this.  Good luck!
