### ISSUE TITLE
Can't install / update board via Arduino 2.0.x (4) 

### ISSUE THREAD

**Issue by jaszczurtd** [earlephilhower/arduino-pico#1302]
Please take a look on the attached screenshot(s).
The description of the rp2040 board package is so long, that somehow overlaps the buttons/controls for the install/update in Arduino 2.0.x IDE release. However, it seems that with the older version of Arduino (pre 2.x.x)  the issue does not exists.
Hint: there is no "More info" link, which indicates the possibility to jump onto github repository.
Tested on Arduino 2.0.4 on windows/osx.

<img width="220" alt="Zrzut ekranu 2023-03-13 o 15 07 22" src="https://user-images.githubusercontent.com/30230229/224726311-202cf918-6d99-4c67-8954-f045394beea5.png">
<img width="208" alt="Zrzut ekranu 2023-03-13 o 15 07 37" src="https://user-images.githubusercontent.com/30230229/224726354-144abdca-a3d9-4caa-b40d-cb4089a83b1c.png">

**Comment by jazztunes** [comment]
You can resize the boards flyout menu.

![image](https://user-images.githubusercontent.com/10814506/224741779-df50e567-ea5c-4565-bc98-f33f7c80eba7.png)

**Comment by jaszczurtd** [comment]
lol, nice. :D
