### ISSUE TITLE
WiFi.begin(ssid, password) causes a blocking loop when CYW43439 is missing

### ISSUE THREAD

**Issue by lyusupov** [earlephilhower/arduino-pico#1327]
**Release**: 2.7.3
**Hardware**: Pico
**Sketch**: [WiFiServer.ino](https://github.com/earlephilhower/arduino-pico/blob/master/libraries/WiFi/examples/WiFiServer/WiFiServer.ino)

The sketch has been built for '**Pico W**' target but is running on '**Pico**' board with no SPI Wi-Fi module .

### Expected behavior

WiFi.begin() should return a failure code. The sketch could continue without Wi-Fi features involved.

### Actual behavior

The sketch does not pass beyond the WiFi.begin procedure.

**Comment by earlephilhower** [comment]
Thanks for the detailed bug report.  Unfortunately running the PicoW blob on a Pico causes trouble, and it's all controlled by the Pico-SDK.  That's where things are stuck in a busy loop in this call, and it's not something we can directly affect here.

What we have added is this call: https://github.com/earlephilhower/arduino-pico/blob/master/docs/rp2040.rst#bool-ispicow which will let your sketch, if you want it to run on either Pico or PicoW, to decide whether to attempt WiFi calls or not.
