### ISSUE TITLE
SPI pin reconfiguration does not allow any combination

### ISSUE THREAD

**Issue by therman89** [earlephilhower/arduino-pico#1331]
I'm trying to use SPI on pins other than the default settings. I found that I cannot use any combination of the available pins, and reception of data over SPI does not work all the time. 
I want to use GP2-GP5 pins to connect to a sensor, but it reception does not work. Using an oscilloscope, I can see that the data is present on both MISO and MOSI pins (so the sensor receives the command and even replies correctly), but the pico reports that there is no reply.

If I change the wires and use GP4-GP7 pins for SPI, the communication works, as well as on GP16-GP19.

I also tried GP0-GP3 and it does not work, either. 
Is there a restriction regarding the collection of pins that I can use for SPI? GP0-GP7 are all SPI0 pins, so in my understanding any valid combination of these should work. I did not find any information on this, so that's why I'm looking for help here.

Meanwhile, I'll rewire my PCB to use GP4-GP7.

**Comment by earlephilhower** [comment]
As @lyusupov listed, there are only specific pinouts supported for each bit of the SPI interface.  ( You can see the official Raspberry Pi graphic here: https://www.raspberrypi.com/documentation/microcontrollers/images/pico-pinout.svg )

By inspection in the code, you can see the following 0..3 config is allowed (and no other ordering...can't swap TX and RX for example):
````
SPI.setRX(0);
SPI.setCS(1);
SPI.setSCK(2);
SPI.setTX(3);
````

**Comment by treyus30** [comment]
Hi, noob here. Been pulling my hair out the last couple days on why I couldn't get basic SPI to work going through limited documentation. This thread finally made me realize you MUST declare SPI**1** for pins 10-13, so thought I'd document it explicitly. 
https://arduino-pico.readthedocs.io/en/latest/spi.html << The first couple sentences never made sense to me, or how to invoke, so a better example would be nice! Anyway, thanks for the hard work. I'm out of my depth here. 

The code that stopped my USB crashes was this 
`#include "SPI.h"
int sckPin = 10;
int mosiPin = 11;
int misoPin = 12;
int csPin = 13;


void setup() {
  // put your setup code here, to run once:
    SPI1.setCS(csPin);
    SPI1.setRX(misoPin);
    SPI1.setTX(mosiPin);
    SPI1.setSCK(sckPin);
    SPI1.begin();

    pinMode(25, OUTPUT);
}`

**Comment by earlephilhower** [comment]
> ...realize you MUST declare SPI1 for pins 10-13...

No, that is not correct.  You must follow one of the legal pinouts given by the RP2040 datasheet.  For example, https://microcontrollerslab.com/wp-content/uploads/2021/01/Raspberry-Pi-Pico-pinout-diagram.svg .

**Comment by treyus30** [comment]
> > ...realize you MUST declare SPI1 for pins 10-13...
> 
> No, that is not correct. You must follow one of the legal pinouts given by the RP2040 datasheet. For example, https://microcontrollerslab.com/wp-content/uploads/2021/01/Raspberry-Pi-Pico-pinout-diagram.svg . There are multiple options you can choose from, but you can't just randomly pick pins or the Pico will crash as it can't physically do what you're asking it to do.

I was referring to the need for the "1" in SPI1 to be used for the channels 1, whereas "SPI" (sans-1) is for 0 channels. Am I mistaken? The text turned red when I did so, signifying it was linked to a class/library, and suddenly the Pico was able to boot.

**Comment by earlephilhower** [comment]
Yup, looks like a misunderstanding.  `SPI` is normally `spi0` and `SPI1` is normally so look for `SPI0.XXX` for `SPI` and `SPI1.XXX` for `SPI1` in the diagrams
