### ISSUE TITLE
stdio_init_all(); does not compile

### ISSUE THREAD

**Issue by NickDolfin** [earlephilhower/arduino-pico#1347]
stdio_init_all();

Apparantly it is in the sdk 1.5.0 library.

I'm not sure why it is undefined. What am I missing to understand?

I use the following platform.io:

[env:waveshare_rp2040_zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
board_build.core = earlephilhower
framework = arduino
platform_packages = toolchain-rp2040-earlephilhower@https://github.com/earlephilhower/pico-quick-toolchain/releases/download/1.5.0-b/x86_64-w64-mingw32.arm-none-eabi-c7bab52.230216.zip
monitor_speed = 115200
upload_speed = 115200
upload_protocol = picotool
build_flags = 
	-fstack-protector
lib_deps = 
	adafruit/RTClib@^2.1.1
	adafruit/Adafruit BusIO@^1.14.1

**Comment by earlephilhower** [comment]
That's not supported.  Use the Arduino `Serial` instead.
