### ISSUE TITLE
Feature Request: Support for SparkFun RP2040 mikroBUS

### ISSUE THREAD

**Issue by warhubster** [earlephilhower/arduino-pico#1366]
This is an absolutely great addition to the Arduino IDE!
However, it does not include the SparkFun RP2040 mikroBUS. I just started playing with this board and am having trouble getting I2C communication to work. 
I'm using the Sparkfun ProMicro RP2040 drivers, which works fine for most I/Os, but the SDA and SDC are GPIO 16 and 17 respectively. On the mikroBUS version they are GPIO 6 and 7. I have not been able to force the correct GPIOs into Wire.
Your assistance would be greatly appreciated.

**Comment by earlephilhower** [comment]
GP 6 and GP7 don't work work for Wire, they're connected to the `i2c1` peripheral.  Use `Wire1.setSDA(6); Wire1.setSCL(7);` before `Wire.begin()` to assign them.

See the RP2040 pinout fro the RPI folks for more info: https://www.raspberrypi.com/documentation/microcontrollers/images/pico-pinout.svg
