### ISSUE TITLE
Update Adafruit TinyUSB to latest version

### ISSUE THREAD

**Issue by TheRacc2** [earlephilhower/arduino-pico#1382]
Adafruit TinyUSB v2.0.3 includes support for multiple HID devices, which is critical for low-latency situations. The earlphilhower core currently supports Adafruit TinyUSB v1.17

Is updating the TinyUSB version possible?

**Comment by TheRacc2** [comment]
Can be fixed by [pull #1383](https://github.com/earlephilhower/arduino-pico/pull/1383)

**Comment by earlephilhower** [comment]
Wow, that was a fast upstream release.  I checked this morning, less than a day later, and there it was.  Hope it's all working for you now!
