### ISSUE TITLE
Is it possible to make try & catch work?

### ISSUE THREAD

**Issue by GFoxPM** [earlephilhower/arduino-pico#1404]
Is it possible to make try & catch work?
When executing throw -- pico just hangs...

**Comment by earlephilhower** [comment]
Use `Tools->C++ Exceptions->Enabled`.  It will blow up the code size and RAM usage a lot, though.

**Comment by GFoxPM** [comment]
@earlephilhower 
Oh thanks!
I missed this option...
At first I tried to enable this with -fexceptions
