### ISSUE TITLE
Serial.print not working after delay

### ISSUE THREAD

**Issue by GFoxPM** [earlephilhower/arduino-pico#1407]
The following code does not display anything in third party serial monitor programs until any character has been sent.
Tested with: tio, screen, pyserial-miniterm, putty
But everything works if you build this code with Arduino Mbed OS RP2040 core
In order for the bug to manifest itself, you need to run the serial port monitor in reconnect mode in case of a disconnect.
```C++
void setup() {
    pinMode(LED_BUILTIN, OUTPUT);
    digitalWrite(LED_BUILTIN, LOW);

    Serial.begin(115200);

    // bool ResetAllSettings = false;
    delay(5000);
    // ResetAllSettings = BOOTSEL;
    digitalWrite(LED_BUILTIN, HIGH);

    // while(!Serial);
    // delay(100);
    Serial.println("START");

    // ...
}
```

**Comment by GFoxPM** [comment]
@SocrateCrypto Presence of while(!Serial); does not affect the existence of the bug.

**Comment by GFoxPM** [comment]
![изображение](https://user-images.githubusercontent.com/91090231/235187392-d6100753-a817-48b1-9e4b-58bc8d3c7bfc.png)

**Comment by GFoxPM** [comment]
![изображение](https://user-images.githubusercontent.com/91090231/235194077-8464f6e6-c134-4feb-b0b8-fc575d8d42d7.png)

**Comment by earlephilhower** [comment]
Sorry, I cannot reproduce this and it seems like something that would kill every user if it was happening since Serial output is the basis for most sketches.

I just ran your sketch (with loop() added) :
````
void setup() {
    pinMode(LED_BUILTIN, OUTPUT);
    digitalWrite(LED_BUILTIN, LOW);

    Serial.begin(115200);

    // bool ResetAllSettings = false;
    delay(5000);
    // ResetAllSettings = BOOTSEL;
    digitalWrite(LED_BUILTIN, HIGH);

    // while(!Serial);
    // delay(100);
    Serial.println("START");

    // ...
}
void loop() {
  static int c = 0;
  Serial.printf("%d\n", c++);
  delay(1000);
}
````

And in the IDE serial monitor got
````
START
0
1
2
3
4
5
6
7
8
9
10
....
````

I suggest you double check which serial port is being connected to in your terminal.  The OS can assign a new ID every reboot of the Pico (i.e. COM5: to COM6: or /dev/ttyACM1 to /dev/ttyACM2) and you might be connecting to an older, non-existing port...

**Comment by GFoxPM** [comment]
@earlephilhower You must:
Launch Serial Monitor (Not from Arduino IDE!).
Disconnect USB cable and reconnect it After that the output will be missing.
This works in any of the listed Serial Monitor except Arduino IDE.

**Comment by earlephilhower** [comment]
I just closed the IDE monitor, unplugged the device, replugged it in, and ran `minicom -D /dev/ttyACM0` and got...

````
Welcome to minicom 2.7.1

OPTIONS: I18n 
Compiled on Dec 23 2019, 02:06:26.
Port /dev/ttyACM0, 11:11:54

Press CTRL-A Z for help on special keys

START
0
 1
  2
   3
    4
     5
      6
       7
        8
````

**Comment by GFoxPM** [comment]
@earlephilhower A prerequisite for the bug is to start the port monitor before loading the RP2040

**Comment by GFoxPM** [comment]
![изображение](https://user-images.githubusercontent.com/91090231/235223638-374943af-a425-433b-abd2-2f11352a994a.png)

**Comment by GFoxPM** [comment]
![Peek 2023-04-28 21-21](https://user-images.githubusercontent.com/91090231/235224464-a8f3c82c-751b-4b35-babf-c3a3bdb4806e.gif)

**Comment by earlephilhower** [comment]
Again, I can't reproduce this on my Ubuntu 22.04 install.

I restarted minicom (the Pico had been running since last message) and then did a USB disconnect/reconnect w/o exiting minicom and all comes back fine:
````
Compiled on Dec 23 2019, 02:06:26.
Port /dev/ttyACM0, 11:13:28

Press CTRL-A Z for help on special keys                                                               
                                                                                                      
1266                                                                                                  
    1267                                                                                              
        1268                                                                                          
            START
0
 1
  2
   3
    4
     5
      6
       7
        8
         9
          10
            11
````

Again, I think you need to check the `dmesg` when you lose connectivity.  Linux might leave `/dev/ttytACM0` even though it's disconnected, and enumerate the Pico as `/dev/ttyACM1`.

**Comment by GFoxPM** [comment]
![Peek 2023-04-28 21-45](https://user-images.githubusercontent.com/91090231/235228617-4aef7eec-973a-4577-9d8b-ee5d76042df2.gif)

**Comment by GFoxPM** [comment]
Arduino Core
![Peek 2023-04-28 21-48](https://user-images.githubusercontent.com/91090231/235229187-bef3d6b0-5be3-4dd2-a2e0-484eacc908bd.gif)

**Comment by earlephilhower** [comment]
I believe you're seeing what you're showing, but it's not reproducible here and we've not gotten other reports of behaviour like this.

At this point, I think the only way forward is for you to dig into SerialUSB.cpp on your own install while this happens and see exactly what's happening in the Pico.  I'd also recommend hooking up a SWD debugger and get a stack trace and see what the core is actually doing in this case (is it sending to TinyUSB where it disappears?  is it thinking it's not connected and throwing things away?  something else?)

**Comment by GFoxPM** [comment]
@earlephilhower Just a guess:
The kernel is waiting for some information from the port monitor.
Because if you press any key, thereby sending a character to the RP2040, then the transmission will resume.

**Comment by GFoxPM** [comment]
`Linux FoxPC 6.1.0-0.deb11.5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1~bpo11+1 (2023-03-05) x86_64 GNU/Linux`

Yes, if I restart the minicom, the transmission will resume by itself.

**Comment by GFoxPM** [comment]
TinyUSB CDC resumes without restarting minicom but prints 2 lines at a time.
![Peek 2023-04-28 22-17](https://user-images.githubusercontent.com/91090231/235234347-b709c1c1-04e9-46bf-8c1b-c6719b1feeec.gif)

**Comment by GFoxPM** [comment]
TinyUSB CDC also doesn't resume transmission without restarting minicom and prints 2 lines at a time.

**Comment by earlephilhower** [comment]
Adafruit_TinyUSB is a different version than the Pico-SDK one, so that points more to a specific system problem than a global issue in SerialUSB.cpp, I think.

The 2-line thing is a known normal effect w/the Adafruit version.  You need to do a `flush()` after each line or it will buffer it.  The buffering increases potential bandwidth but at the cost of latency in this case.

**Comment by GFoxPM** [comment]
I will test this bug in Ubuntu 22.04.

**Comment by earlephilhower** [comment]
@GFoxPM sorry, mybad.  I'm running Ubu **20**.04.6 LTS, not 22.04

In any case the Adafruit Serial implementation is completely different from my own, and they themselves do all the USB stack (including IRQ handling).  So there's no USB shared code between the main core SerialUSB and Adafruit USB.

**Comment by GFoxPM** [comment]
@earlephilhower 
On Ubuntu 22.04 the error does not appear.
And I think I found the reason...
I have a udev rule `SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="0003", MODE="0666"`
After this rule is deleted, the transmission resumes automatically.
But the problem is not completely solved.
The first 3-4 lines are missing...

**Comment by GFoxPM** [comment]
Well, the problem seems to be really in my system...
If I find a reason, I'll post it.

**Comment by GFoxPM** [comment]
The source of the problem could not be found.
Reinstalling the system solved the problem.
It is strange that the problem is completely absent on the Arduino core...

**Comment by VitRuzicka** [comment]
Hello,
I encountered the very same bug on upgraded ubuntu from 22.04 to 23.04. The serial port "dies" after nothing is being send for ~2s. Might have something to do with the new system because it previously worked flawlessly. The issue can be replicated in both arduino-ide 2.xx and vscode.

Regards,
Vít.
