### ISSUE TITLE
WIFI AP bug?

### ISSUE THREAD

**Issue by enginekid92** [earlephilhower/arduino-pico#1431]
https://github.com/earlephilhower/arduino-pico/blob/3dee0a276b63c42899bc1d705d1e4de774f7e023/libraries/WiFi/src/WiFiClass.cpp#L151

Could not get AP mode to work until I changed the " 42," to " 4," on this line, please take a look and correct if needed, sorry for the low quality post, in a hurry and found this last minute.

**Comment by earlephilhower** [comment]
No response in a week, closing.
