### ISSUE TITLE
Native USB host options?

### ISSUE THREAD

**Issue by XZCE** [earlephilhower/arduino-pico#1488]
RE: https://github.com/adafruit/Adafruit_TinyUSB_Arduino/issues/292#issue-1685764735

Knowing almost zero about the Arduino IDE internals, I think the menu config (boards.txt) controlling build options would be part of this repo...  So, if Adafruit were to make changes (or be supplied some pull-request) to allow "native USB host" support for the Pico, rather than force the far more limited bit-banged/PIO host support which doesn't suit quite so many users, changes would also be needed here?

It's marked as an enhancement "over there" - but, in my understanding, other platforms have not been hobbled like this (because they don't have the Pico's superior PIO device, shoehorned into limited clock options)?

Is there any chance anyone here has the ability and motivation to make this happen?

**Comment by earlephilhower** [comment]
What exactly does this need to be added in this core?  After reading the thread linked, I'm not quite sure.

Right now, it seems edits need to be done to TinyUSB, yes?  If so, we need those to get applied upstream (and then pulled in to Adafruit's wrapper library).  Once that's done, we can really start hacking here.  (It's definitely possible to temporarily fork the two projects and apply patches until they are committed upstream, but it's not something I feel happy supporting for a real commit.  No reason to be a middle-man.)

If you have something running already, maybe you're the best person to start roughing out a pull request?  I would suggest this can be done in the `USB Stack` as a new option `USB Host` which can set a couple `#define`s which you can then use to bracket any changes.
