### ISSUE TITLE
Ethernet on w5100s-evb-pico

### ISSUE THREAD

**Issue by nickehallgren** [earlephilhower/arduino-pico#1489]
Is ethernet supported or must I use the Wiznet Ethernet library? Using the the DhcpAdressPrinter sketch I get:

Ethernet shield was not found.  Sorry, can't run without hardware. :(

With WizNet library installed it works, using the same setting

`Ethernet.init(17);`

I want to use MQTT over TLS and had some problems with the WizNet library when adding SSLClient

**Comment by earlephilhower** [comment]
Sorry, you'll need to use the WizNet library.  It's not been ported into the `libraries/lwip_XXX` yet #775 (always happy to get a PR for it 😄).
