### ISSUE TITLE
pico/stdio_usb.h not found

### ISSUE THREAD

**Issue by thirstyice** [earlephilhower/arduino-pico#1498]
Trying to do some debugging by printing stdio messages to usb, but the compiler can't find the header.
Weird because it finds pico/stdio_uart.h just fine.

Platformio on Windows 11

**Comment by earlephilhower** [comment]
That is not supported, nor needed.  Just use `printf` and set the Debug port via the IDE to `Serial` in order to get `printf` outputs.  You can also use `Serial.printf()` if needed.

**Comment by thirstyice** [comment]
I'm looking to get the output of a `panic()` over the usb connection.
Where do I set the debug port in the IDE?

**Comment by earlephilhower** [comment]
>  Where do I set the debug port in the IDE?

Err...`Tools->Debug Port`

**Comment by thirstyice** [comment]
PlatformIO, not Arduino

**Comment by thirstyice** [comment]
Never mind, found it in the documentation!
https://arduino-pico.readthedocs.io/en/latest/platformio.html#debug-port
