### ISSUE TITLE
request for Adafruit_TinyUSB_Arduino submodule update

### ISSUE THREAD

**Issue by lyusupov** [earlephilhower/arduino-pico#1509]
Would you, please, consider to update the Adafruit_TinyUSB_Arduino submodule on [**version 2.2.1**](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/releases) to take advantage of new CP210X and FT2XX USB CDC Host drivers available there ?

**Comment by earlephilhower** [comment]
All set, will be in next release (later this week I hope).

**Comment by lyusupov** [comment]
Thank you so much!
