### ISSUE TITLE
micro delay on Interrupt, Freezes Pico

### ISSUE THREAD

**Issue by Srjames094** [earlephilhower/arduino-pico#1549]
if I remove the delay and the readtemperature() and set only one variable to true and read it in the loop, the code works but as soon as I put a microdelay it stops working and the pico frezzes.

my code sample:

#define signalReadPin 22

void setup() {
  pinMode(signalReadPin, INPUT);
  attachInterrupt(signalReadPin, interruptRead, FALLING);
}

int sensorValue;
float tensao_AmpOp;

void interruptRead() {
  delayMicroseconds(500);
  readTemperature(0);
}

void readTemperature(float offset) {
  sensorValue = analogRead(sensorPin);

  tensao = (float)map(sensorValue, 0, ADC_res, 0, max_Voltage) / 1000;

  tensao_AmpOp = 1000 * tensao / AmpOp_gain;
  temp_Raw = tensao_AmpOp * sense_Termocouple + offset;

  input = f.filterIn(temp_Raw);
}

My "solution"

void interruptRead() {
  enable = true;
}

void loop() {
  if (enable) {
      enable = false;
      delayMicroseconds(300);
      readTemperature(0, false);
  }
printValues();
}

how can i make this code better and read on interrupt?

**Comment by earlephilhower** [comment]
You can't do blocking operations like `delay` in an ISR.  You could, theoretically, use `busy_wait_us` instead, but it's generally a bad idea to spend extra time in interrupts.
