### ISSUE TITLE
PICO Sometime going freeze

### ISSUE THREAD

**Issue by maxmurugan** [earlephilhower/arduino-pico#1558]
hi sir,
I am using PICO with Arduino software using read Modbus data ,some time  Pico goes to freeze after restart it working

how to solve the freeze issue?

**Comment by earlephilhower** [comment]
Sorry, without an MCVE that can run w/o additional hardware there's nothing anyone else can do.  I suggest you check things like the power supply quality, simplifying your code, using the SWD debug port during freezes to check if it's a HW or SW hang, etc.  Good luck!
