### ISSUE TITLE
Should we switch default probe to cmsis-dap

### ISSUE THREAD

**Issue by hathach** [earlephilhower/arduino-pico#1559]
Ref: https://github.com/earlephilhower/arduino-pico/discussions/1299

Problem: Arduino IDE v2 doesn't seem to pick up the probe selection from menu when launching debug session. As far as I have tested, IDE v2 will always use the default probe, seems like the debug daemon/code in the IDE will scan {build.openocdscript} once and never try to re-scan it. Even though this is IDE bug, user will just complain and confused anyway (like me).

Solution: Is it reasonable to switch the default probe to cmsis-dap implementation instead. The reason is the old implementation of picoprobe (pre-1.0) is legacy firmware now, the project https://github.com/raspberrypi/picoprobe/releases will only be based on daplink and will eventually reach more user than pre-1.0. In addition, people that buy commercial pi debug probe https://www.raspberrypi.com/products/debug-probe/ will probably assume it will work out of box with pico.

As bonus point, the cmsis-dap probe can also be used to debug other cortex mcu such as samd, nrf. It is kind of nice one cheap probe for most things.

For old picoprobe, we can simply tell user to either upgrade firmware or change menu selection !! 

If that sounds good to you, I could make an PR to move the cmsis-dap to be the default one.

**Comment by earlephilhower** [comment]
Sounds good.  I would appreciate the PR, thanks!
