### ISSUE TITLE
UART communication

### ISSUE THREAD

**Issue by albmaid** [earlephilhower/arduino-pico#1564]
Hello Earle! Thanks in advance for your work!!

I am trying to communicate with my raspberry pi pico via UART using your core and I'm having some troubles. Despite being not sure about the code, I am testing if the GPIOs 4 (UART1 TX) and 0 (UART0 TX) are really sending information with an oscilloscope but the pins only remain in High state. Then I am trying to use PuTTY to see if the info is only being send by the physical wire but also I can't read anything, I don't know if it's because I am configurating badly the PuTTY because of the bootloader disconection of the raspberry pi pico or anything else.

Also say that I'm having so much trouble for combining arduino libraries with the core. I don't really know if there is something that I'm missing but every time I try to make something with the microcontroller and I need to use some libraries or export some internet code examples the raspberry doesn't work as expected.

Nevertheless, this github repository is really good for programming the raspberry pi pico. Thank you very much!!

**Comment by earlephilhower** [comment]
Please check your pinouts and wiring (the pins specified are always GPx pins from the RP2040 and do not correspond 1:1 to the Pico PCB pinout).

The following example runs and shows up properly on my $5 logic analyzer:
````
void setup() {
  Serial1.setTX(0);
  Serial1.begin(9600);
}

int cnt = 0;
void loop() {
  Serial.printf("send PING: %d\n", cnt);
  Serial1.printf("PING: %d\n", cnt++);
  delay(1000);
}
````

![image](https://github.com/earlephilhower/arduino-pico/assets/11875/92345ead-522c-48ec-b828-77d5517913f9)

**Comment by walchko** [comment]
what logic analyzer is that? Do you like it?

**Comment by josephduchesne** [comment]
> what logic analyzer is that? Do you like it?

That looks like pulseview (sigrok project) which is FOSS works with a long list of cheap and professional logic analyzers. You can get 8/16 channel USB analyzers for $20 from sparkfun or cheaper on aliexpress that work fine for most hobby stuff below a few Ghz.
