### ISSUE TITLE
Malfunction at restart

### ISSUE THREAD

**Issue by Lizethgm** [earlephilhower/arduino-pico#1581]
Hi, 
I have an error in the program generated from pico-sdk (https://github.com/raspberrypi/pico-sdk)

If I load to my board which has a RP2040 chip a .uf2 generated from the pico-sdk it works correctly when loading the first time, but once the board is turned off and on again the program is still there but does not initialize. Sometimes it works when restart but it is very rare when it does. The error can be seen in the following video.
https://github.com/earlephilhower/arduino-pico/assets/105874681/2e299098-daf0-42cb-9206-82ab782732a3

If I use its core "arduino-pico" it works correctly, it doesn't have any problem, it initializes all the time even if it is turned off and on again. This can be seen in the following video 
https://github.com/earlephilhower/arduino-pico/assets/105874681/f3735d04-6070-403b-88c6-b58f196ac2ff

Do you have any idea what could be happening or what is missing to add to the pico-sdk?

**Comment by earlephilhower** [comment]
Sorry, but there's very little someone without your exact HW and app can do.  FWIW the core here uses the SDK unmodified so there are no code changes there that would affect things.  My suggestions:
* Check the flash type (BOOT2).  Use the Generic SPI/4 option in the SDK as the most compatible code
* Use a basic LED blinker, not your app.  If that works but your app doesn't, then maybe there's some global uninitialized or some race condition in your app code
* Hook up a SWD debugger and see what the core is actually doing when it doesn't start your app.
