### ISSUE TITLE
Breaking the peripheral interrupts when I2C ports swapped

### ISSUE THREAD

**Issue by earlephilhower** [earlephilhower/arduino-pico#1607]
> This seems to break the peripheral interrupts(onReceive callback function never gets called), causing the RX buffer to fill, and SCL to be pulled low permanently causing the controller to freeze. TalkingToMyselfExample.ino does not work (even after swapping the Wire<>Wire1) assignments. Reverting back to the old pin_arduino.h fixes it. Not sure what the dependency is.

_Originally posted by @jfentonatnklabs in https://github.com/earlephilhower/arduino-pico/issues/1465#issuecomment-1650909920_

**Comment by earlephilhower** [comment]
@jfentonatnklabs, I think you are right.  The proper IRQ *shim* handler is installed, but when it calls the actual object it doesn't look at the physical I2S port and assumes no swapping.
https://github.com/earlephilhower/arduino-pico/blob/67a07edcccb954c7ef8938ff64733f4a89eff893/libraries/Wire/src/Wire.cpp#L110-L116

**Comment by jfentonatnklabs** [comment]
Thank you. I tried the fix in #1608 and it is working using the example file. One side note is the example file (TalkingToMyselfExample.ino) needs to have the pin numbers swapped between Wire<>Wire1 to account for the change in #1465  on the Adafruit Feather RP2040.

**Comment by earlephilhower** [comment]
Thanks for the report!
