### ISSUE TITLE
Set power mode to get WiFi power-saving off.

### ISSUE THREAD

**Issue by meoinhan** [earlephilhower/arduino-pico#1610]
I was told if using micropython it would be “wlan.config(pm = 0xa11140)” then i just need to replace wlan with WiFi i am using lib WiFi.h I'm trying to find out, thanks. We hope to receive an answer...

**Comment by earlephilhower** [comment]
It's already set to that by default.  You can use any of these calls to adjust to different options:
https://github.com/earlephilhower/arduino-pico/blob/5fd4736d8f3c726b4e8af3d8294625d4462c44d6/libraries/WiFi/src/WiFiClass.cpp#L596-L607
