### ISSUE TITLE
Wire library problem using two different I2C busses

### ISSUE THREAD

**Issue by caiannello** [earlephilhower/arduino-pico#1634]
Hello.

First of all, thank you so much for all the hard work on this repo! I find it so much more convenient to running cmake in a Linux VM!

Is it possible there is some kind of issue using dual I2C busses (I2C0 on GP6, GP7, and I2C1 on GP14, GP14)  via the `Wire` and `Wire1` classes?

I designed a board which makes use of two different I2C peripherals, each with it's own bus:

Peripheral 1: Atmega328P as I2C master on pi pins GP6 (I2C0_SDA)  and GP7 (I2C0_SCL)
Peripheral 2: NAU8822  audio codec as I2C slave on GP14 (I2C1_SDA), GP15 (I2C1_SCL)

Both buses are terminated (pulled to +3v3) with external 4.7K resistors, one per line, for a total of four resistors.

The Atmega is a keyboard matrix scanner, and I was successful getting messages from it over the bus, but there is already something mysterious. The is the init code follows:

```
  // kb controller i2c
  pinMode(6,INPUT);
  pinMode(7,INPUT);
  Wire1.onReceive(recv);  // I know this should be Wire and not Wire1, see below.
  Wire1.onRequest(req);
  Wire1.setSDA(6);
  Wire1.setSCL(7);
  Wire1.begin(0x30);
```

I expected since 6,7 are I2C0, I would need to use the `Wire` object rather than the `Wire1` object, but when I change all occurrences from `Wire1` to `wire`, communications stops working!

I wanted to start trying to initialize the audio codec, hoping that the issue was a simple case of `Wire` and `Wire1` being swapped in software, so I began by adding the following lines:

```
  // audio codec i2c
  #define pSCL  15
  #define pSDA  14
  pinMode(pSCL,INPUT);
  pinMode(pSDA,INPUT);
  Wire.setSDA(pSDA);
  Wire.setSCL(pSCL);
```

But with the addition of the above, comms with peripheral 1 on Wire1 stops working.  Again, I tried swapping all occurrences of `Wire` for `Wire1`, but comms is still broken with peripheral 1. 

Thank you for your time.
Craig Iannello

**Comment by caiannello** [comment]
I see what I'm doing wrong.  Both sets of pins are really I2C1..

**Comment by earlephilhower** [comment]
Great [rubber duck debugging!](https://en.wikipedia.org/wiki/Rubber_duck_debugging)  😆 Happens to us all!
