### ISSUE TITLE
Feature Request: RP2040 I2S TDM Support?

### ISSUE THREAD

**Issue by DatanoiseTV** [earlephilhower/arduino-pico#1666]
There are some codecs including the CS42448 which have more than 2 channels I/O.
Supporting TDM mode would be great for some applications like samplers.

**Comment by earlephilhower** [comment]
Err, this is a dup of #1066, no?

**Comment by DatanoiseTV** [comment]
Sorry, indeed. I didn't find the old feature request anymore.
