### ISSUE TITLE
Missing include stdint.h in common.h

### ISSUE THREAD

**Issue by jpavieira** [earlephilhower/arduino-pico#1676]
In file https://github.com/earlephilhower/arduino-pico/blob/master/variants/generic/common.h 
I get many errors like this:
```
\framework-arduinopico\variants\generic\common.h:43:14: error: 'uint8_t' does not name a type
   43 | static const uint8_t D28 = (28u);
```

I could fix it by adding including stdint.h in that file.

**Comment by earlephilhower** [comment]
That seems fine, would you like to make the PR for this?

I'm curious, though, how you're seeing this.  The variant's `.h` file is normally included by `Arduino.h` well after a `#include <stdint.h>` has happened.

**Comment by jpavieira** [comment]
Sure, I will do it.
I'm also puzzled how this can happen. Anyway, the header has that dependency so it's not self-contained.
