### ISSUE TITLE
Nano RP2040 Connect: Serial port only available after first using IDE Serial Monitor

### ISSUE THREAD

**Issue by rolfmeesters** [earlephilhower/arduino-pico#1678]
Nano RP2040 Connect (version 3.3.2) on Windows 11.

when i plugin my Nano it is not possible to get respons on my laptop.
my (Pure Data) program can 'connect'  to the port and 'send' bytes without complaint from Windows, but the Nano does not respond.
only after first using the Arduino IDE Serial Monitor  the Nano is willing to respond.

with  "Serial.begin(bauds); while(!Serial){delay (2000);}
opening the Serial Monitor triggers the start of the sketch.

without the "while(!Serial)..."
the sketch starts 'by itself'; when i open the Monitor it's already running.

on a Mac with the same setup it's connecting ok.
also with the "while(!Serial)...".
and also after pushing the reset-button.

however, doing a 'soft-reset' with

rp2040_wdt_begin(1000);
while(1){};

is causing the same unresponsive port behaviour of the Nano.

rolf meesters

**Comment by earlephilhower** [comment]
Sorry, you're going to need to post some MCVE code for the Pico and explain exactly what you're running on the PC side.  The Serial port is pretty simple and untouched for many releases, and it's all SW controlled from the Pico so the Arduino Nano and the RPI Pico boards have the same exact code and behavior.

One thing found on some odd Windows apps is that they don't assert the virtual `DTR` signal.  You can try adding `Serial.ignoreFlowControl()` to the top of your code and see if that helps.  See https://github.com/earlephilhower/arduino-pico/blob/master/docs/serial.rst#rp2040-specific-serialusb-methods
