### ISSUE TITLE
UART1 prints garbage.

### ISSUE THREAD

**Issue by the-maldridge** [earlephilhower/arduino-pico#1693]
I'm troubleshooting a problem with using Serial2/UART1 to provide an extra serial port in a design.  When using the following test program, I get garbage in my console that appears to be the right number of bytes.  At this point I'm inclined to think that there's something wrong in the underlying code that drives Serial2, so I'm looking for any help in figuring out what went wrong here.

```
void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  Serial2.setTX(4);
  Serial2.setRX(5);
  Serial2.begin(300);
}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(250);
  digitalWrite(LED_BUILTIN, LOW);
  delay(250);
  Serial2.println("A");
}
```

**Comment by maxgerhardt** [comment]
I can very easily check this with a logic analyzer on GP4 to see what's being output. Maybe the small baudrate is a problem because it can't find a right clock divider or delay number of for it? Did you test with another one like 9600?

**Comment by earlephilhower** [comment]
I suggest you check your UART for proper configuration.  Default is 8N1, and with your example at 300bps I get a nice, decoded `A\r\n` using my logic analyzer.  Same at other baud rates:

![image](https://github.com/earlephilhower/arduino-pico/assets/11875/4f3513a5-56f2-4e8e-8d1d-28ec0b9fe4dd)

**Comment by maxgerhardt** [comment]
I can confirm the same results, compiling and uploading your sketch and feeding the GP4 signal to the RX of a USB-UART adapter (with the same common GND) gives the expected results at 300 baud.

![grafik](https://github.com/earlephilhower/arduino-pico/assets/26485477/979910ac-2696-4832-9231-c0c10b8154e8)
