### ISSUE TITLE
Pimoroni Tiny 2040 LED_BUILTIN is defined wrongly

### ISSUE THREAD

**Issue by Andy2No** [earlephilhower/arduino-pico#1696]
The Pimoroni Tiny 2040 board definition has LED_BUILTIN defined as 25, in v3.4.1, but does not have an LED on that pin.

It has an RGB LED (not NeoPixel) with connections to R, G and B on pins 18-20 (active low).  The pinout I'm referring to seems to imply that pin 19 (Green) should be the one used for LED_BUILTIN, from the way it's drawn, but any one of the three would do.

I've verified that the usual Blink sketch doesn't affect the LED via LED_BUILTIN (GP25) but flashes the Green LED if I use pin 19 instead.

![tiny-2040-pinout-diagram](https://github.com/earlephilhower/arduino-pico/assets/8021302/99d1b22b-d421-4341-bbe8-d540afe42ac5)

Perhaps Pimoroni could say which of the three LED elements they'd prefer to be used for LED_BUILTIN.

**Comment by earlephilhower** [comment]
Please feel free to update the variant.  The `git blame` for it is all on me now, and I'm happy to have others to point the finger at. :laughing:

I think I only did the variant because of the flash type and size being non-default.  I probably didn't look too closely at the schematic as you've seen.

**Comment by Andy2No** [comment]
I made a pull request, then spotted a problem, so hold off on that one.

generic /  common.h refers to PIN_SPI0_SS but the Tiny 2040 doesn't have one - it doesn't have any physical header pins with that option.

The genetic / arduino.h has this:

#define PIN_SPI0_SS    (17u)

so I'll put that back as a dummy pin, unless there's a better way.

**Comment by earlephilhower** [comment]
FYI, it's possible to swap SPI and SPI1, see some of the Adafruit boards where only SPI1 pinouts are available.

**Comment by Andy2No** [comment]
Hmmm... going by their pinout, we can have SPI0 in one of two places, but they don't mention SPI1.

It only has GPIO0-7, plus the 4 ADC pins on GPIO26-29  like the ItsyBitsy RP2040 and WaveShare RP2040-Zero.  Going by the pinout of the standard Pico, it looks like there's no way to involve SPI1, or any SS pin.  I've also read that it can't have an SS pin, but I can't remember where, off hand.

I've amended the pins_arduino.h to put the dummy SS pin definition in.  I'm not sure if that's the best way to do it.  The alternative would be to not use generic / common.h, and copy in all but one line, but maybe that would break something else..

It's https://github.com/earlephilhower/arduino-pico/pull/1699
