### ISSUE TITLE
Platformio debugging: Watching class member variables doesn't work

### ISSUE THREAD

**Issue by LinusHeu** [earlephilhower/arduino-pico#1716]
![grafik](https://github.com/earlephilhower/arduino-pico/assets/118672629/30b32913-96a2-484d-ae08-cf8d9f4ed73e)

In the bottom right, an error message pops up:

> There is no member or method named private. (from var-create watch_d1fa06f3898bc8ff4df7d0a42ff362c8} @ "obj.private.privat")

This bug already happened before the update. I just noticed it again.

**Comment by earlephilhower** [comment]
I think this is a general Platform.IO thing and unrelated to the core running.  `public` and `private` are simple C++ keywords...

**Comment by maxgerhardt** [comment]
The "public" and "private" displays are just in the debugger view so that you know where these variables were declared.

I think that in the watch window, you should just access the variables directly as you would in code, i.e.,
```
obj.i
obj.privat
```

**Comment by LinusHeu** [comment]
Yes, that's it! Thanks!
Then I suppose it's just a UI/Platformion issue. Because right-clicking a variable -> "add to watch" automatically adds .private/.public.

**Comment by maxgerhardt** [comment]
Huh I actually never tried to add a variable watch that way. I think you have a good case to open a bug at https://github.com/platformio/platformio-vscode-ide/issues/ to better the debugging UI?
