### ISSUE TITLE
Unable to flash Raspberry Pico W over the OTA

### ISSUE THREAD

**Issue by Jaishankar872** [earlephilhower/arduino-pico#1728]
Hi
   I am using Raspberry Pico W official board from Raspberry Pi

   And I used the example of BasicOTA, 
![image](https://github.com/earlephilhower/arduino-pico/assets/45547294/c5d44bb5-b67c-4d27-83a9-1555d0bf330e)

Flash the Raspberry Pico W over the OTA, getting failed with below Error
(Note: Also I tried installing the latest release of 3.6.0 Refer the below screenshot)
08:45:01 [ERROR]: Bad Answer: ERR: No Filesystem
Failed uploading: uploading error: exit status 1

![image](https://github.com/earlephilhower/arduino-pico/assets/45547294/dbe9c912-7854-4a3a-ae86-fca953160bb7)

**Comment by earlephilhower** [comment]
>  08:45:01 [ERROR]: Bad Answer: ERR: No Filesystem

You need to have a Filesystem to do OTA.   Use the Tool->Flash Size to assign a FS setaside.

**Comment by Jaishankar872** [comment]
Hi 
Thanks for your fast response

Now, new error is coming as below

Usage: espota.py [options]

espota.py: error: option -p: invalid integer value: '{upload.port.properties.port}'
Failed uploading: uploading error: exit status 2

![image](https://github.com/earlephilhower/arduino-pico/assets/45547294/af0d5de8-5c5a-4712-8d21-7c1e16987c3c)

**Comment by bartgrefte** [comment]
> Hi Thanks for your fast response
> 
> Now, new error is coming as below
> 
> Usage: espota.py [options]
> 
> espota.py: error: option -p: invalid integer value: '{upload.port.properties.port}' Failed uploading: uploading error: exit status 2
> 
> ![image](https://private-user-images.githubusercontent.com/45547294/270149611-af0d5de8-5c5a-4712-8d21-7c1e16987c3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTA3NDgsIm5iZiI6MTcwOTgxMDQ0OCwicGF0aCI6Ii80NTU0NzI5NC8yNzAxNDk2MTEtYWYwZDVkZTgtNWM1YS00NzEyLThkMjEtN2MxZTE2OTg3YzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDExMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwY2IwYzZlOGE0YWI2MzI0YzdhYTQ4MmNjOTM1MTUzMGY3NWMyNzA3MWI1NDZjZjAwMjQ3ZDZhN2YxMWRhZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZVsiUaW9Sw2vLy7r9KOUgfx4VcyktfJZ0Vc1xTyuXVs)

Same error here:
```
Sketch uses 398820 bytes (19%) of program storage space. Maximum is 2093056 bytes.
Global variables use 73356 bytes (27%) of dynamic memory, leaving 188788 bytes for local variables. Maximum is 262144 bytes.
Usage: espota.py [options]

espota.py: error: option -p: invalid integer value: '{upload.port.properties.port}'
Failed uploading: uploading error: exit status 2
```

Also running into https://forum.arduino.cc/t/ide-2-0-ota-mdns-discovery-only-intermittently-finds-nodes/1036850/2 , not sure if related. 

As for the error, I've checked both the firewall on my router as well as ESET Internet Security on the Arduino IDE W10 host, nothing is being blocked as far as I can tell.
