### ISSUE TITLE
SPISlave cannot communicate with other arduino with MODE0 or MODE2

### ISSUE THREAD

**Issue by asukiaaa** [earlephilhower/arduino-pico#1746]
Thank you for sharing useful environment.
I tried SPIClass and have a problem.

I tried SPI communication with the following connection.
Arduino Uno R3 as SPI Master - 5V to 3.3V level shifter - Pi Pico SPI Slave
(I also tried STM32H753ZI as SPI master but same result.)

The pi pico succeeded in communicatiing with MODE1 or MODE3 but cannot with MODE0 or MODE2.
Do you have any idea to resolve problem of MODE0 and MODE2?
Is it problem of pico-sdk?

The code what I tried.

Pi Pico slave
```cpp
#include <Arduino.h>
#include <SPISlave.h>

#if true
#define PIN_SPI_CS 17
#define PIN_SPI_MOSI_RX 16
#define PIN_SPI_MISO_TX 19
#define PIN_SPI_SCK 18
#define SPI_SLAVE SPISlave
#else
#define PIN_SPI_CS 9
#define PIN_SPI_MOSI_RX 8
#define PIN_SPI_MISO_TX 11
#define PIN_SPI_SCK 10
#define SPI_SLAVE SPISlave1
#endif

SPISettings spisettings(1000000, MSBFIRST, SPI_MODE0); // OK for MODE 1 and 2, bad for 0 and 2

void setup() {}
void loop() { delay(5000); }

volatile bool recvBuffReady = false;
const uint8_t lenBuff = 20;
char recvBuff[lenBuff] = "";
int recvIdx = 0;
void recvCallback(uint8_t *data, size_t len) {
  if (recvIdx + len >= lenBuff) {
    len = lenBuff - recvIdx;
  }
  if (len > 0) {
    memcpy(recvBuff + recvIdx, data, len);
    recvIdx += len;
  }
  while (recvIdx >= lenBuff) {
    recvBuffReady = true;
    recvIdx -= lenBuff;
  }
}

int sendcbs = 0;
char sendBuff[10];
int sendIndex = 0;
void sentCallback() {
  SPI_SLAVE.setData((uint8_t *)&sendBuff[sendIndex], 1);
  ++sendIndex;
}

void setup1() {
  SPI_SLAVE.setRX(PIN_SPI_MOSI_RX);
  SPI_SLAVE.setCS(PIN_SPI_CS);
  SPI_SLAVE.setSCK(PIN_SPI_SCK);
  SPI_SLAVE.setTX(PIN_SPI_MISO_TX);
  sentCallback();
  SPI_SLAVE.onDataRecv(recvCallback);
  SPI_SLAVE.onDataSent(sentCallback);
  SPI_SLAVE.begin(spisettings);
  delay(3000);
  Serial.println("S-INFO: SPISlave started");
}

void loop1() {
  if (digitalRead(PIN_SPI_CS) == HIGH && recvIdx > 0) {
    Serial.printf("S-RECV: '%s'\n", recvBuff);
    recvBuffReady = false;
    recvIdx = 0;
    sendIndex = 0;
    ++sendcbs;
    sprintf(sendBuff, "hi %d", sendcbs);
    Serial.printf("set sendBuff '%s'\n", sendBuff);
  }
}
```

Arduino Uno R3 master
```cpp
#include <Arduino.h>
#include <SPI.h>

SPISettings spisettings(1000000, MSBFIRST, SPI_MODE0); // OK for MODE 1 and 2, bad for 0 and 2
#define PIN_CS SS
#define SPI_MASTER SPI

void setup(void) {
  Serial.begin(115200);
  Serial.println();
  pinMode(PIN_CS, OUTPUT);
  digitalWrite(PIN_CS, HIGH);
  SPI_MASTER.begin();
  SPI_MASTER.setDataMode(SPI_MODE0);
}

byte transferAndWait(const byte what) {
  byte a = SPI_MASTER.transfer(what);
  delayMicroseconds(20);
  return a;
}

void loop(void) {
  char data[10];
  sprintf(data, "hello ");
  SPI_MASTER.beginTransaction(spisettings);
  digitalWrite(PIN_CS, LOW);
  SPI_MASTER.transfer(data, sizeof(data));
  SPI_MASTER.endTransaction();
  digitalWrite(PIN_CS, HIGH);
  delay(10);
  Serial.println("hello results:");
  for (size_t i = 0; i < sizeof(data); i++) {
    // Serial.print(data[i]);
    Serial.print(data[i], HEX);
    Serial.print(' ');
  }
  Serial.println();
  for (size_t i = 0; i < sizeof(data); i++) {
    Serial.print(data[i]);
    // Serial.print(data[i], HEX);
  }
  Serial.println();

  Serial.println("at " + String(millis()));
  Serial.flush();
  delay(1000);
}
```

**Comment by earlephilhower** [comment]
Unfortunately I haven't had access to an Uno in something like 10 years.  

What exactly do you mean it's not communicating?  That it's not sending/receiving at all?  That it's getting bad data?  That things are shifted, etc?

Are you able to get traces of the SPI signals between the two devices in the passing and failing modes?  That would help diagnose things.

FWIW MODE0/2 are both `SPI_CHPA_0` meaning the opposite edge is used to sample data from MODE1/3, so that's worth exploring.  Especially if there's HW between the 2 devices like the level shifters, could the setup/hold times be broken because of it?

**Comment by asukiaaa** [comment]
Thank you for the respoinse.

> What exactly do you mean it's not communicating? That it's not sending/receiving at all? That it's getting bad data? That things are shifted, etc?

Slave basically receive nothing but sometimes get first byte.

> Are you able to get traces of the SPI signals between the two devices in the passing and failing modes? 

I checked the signals from Pico and ProMicro(ATMega32u4) then found that SS signal is different betreen Pico and Arduino(ATMega32u4).

![pico_master_mocd0_ss_mosi](https://github.com/earlephilhower/arduino-pico/assets/5975178/21ff9325-7538-4bb8-b9cb-83d55b012248)
![pico_master_mode0_sck_mosi](https://github.com/earlephilhower/arduino-pico/assets/5975178/41e43842-2092-439b-8cc5-da5cb0128d9d)
![pico_master_mocd1_ss_mosi](https://github.com/earlephilhower/arduino-pico/assets/5975178/f245906e-20a7-4260-9e96-c55d8131f191)
![pico_master_mode1_sck_mosi](https://github.com/earlephilhower/arduino-pico/assets/5975178/7eaad6d4-fc4f-47a7-a005-30fc81438ce1)
![promicro_master_mocd0_ss_mosi](https://github.com/earlephilhower/arduino-pico/assets/5975178/ca8a7aa1-d719-4766-8ff4-f697e7fb2b85)
![promicro_master_mode0_sck_mosi](https://github.com/earlephilhower/arduino-pico/assets/5975178/ec8824cb-64e4-443e-a828-c3e636580ba4)
![promicro_master_mocd1_ss_mosi](https://github.com/earlephilhower/arduino-pico/assets/5975178/35a18ef4-6b82-4f16-bcbb-bb5ae37a2599)
![promicro_master_mode1_sck_mosi](https://github.com/earlephilhower/arduino-pico/assets/5975178/a7c3d101-93e2-454a-8b2d-f6509c28c443)

**Comment by earlephilhower** [comment]
Sorry, but it's pretty impossible to tell anything when the clocks and MOSI/MISO are on different graphs and overlaid.  Since the voltage swings seem fine, can you use a logic analyzer instead and capture all channels at the same time to look at?

**Comment by earlephilhower** [comment]
Also, we need enough detail to identify when the data is changing relative to the clock on MOSI and MISO, especially since this is a weird clocking mode being debugged.  So higher sampling rate is better. :)

**Comment by asukiaaa** [comment]
Thank you for the response but I don't have logic analyzer so I cannot show information any more now.

**Comment by earlephilhower** [comment]
Unfortunately, I don't think there's anything we can do here then since this is hardware and timing related.  The different SPI modes only differ in 2 setup calls (the CPOL and CPHA settings).  Looking at the code, the settings for MODE0..3 match the info found in the Analog Devices whitepaper.  Given the clock/data relationships this could well be related to setup and hold times which are outside our control here.

So, closing for now.  If we can get some good hi-res traces with all signals we can look at it some more...

**Comment by asukiaaa** [comment]
The problem is not resolved so I think it's better to keep open state.

**Comment by earlephilhower** [comment]
Looking into it, those calls are not used in the SPISlave object, only in the normal SPI master one.
