### ISSUE TITLE
File system documentation mentions SPIFFS

### ISSUE THREAD

**Issue by palmerr23** [earlephilhower/arduino-pico#1753]
At several points in the File System documentation under "File system object (LittleFS/SD/SDFS)" heading SPIFFS is mentioned explicitly, despite it being unsupported.

It is unclear whether these references can be translated to "SDFS".

**Comment by earlephilhower** [comment]
Thanks, by the way, for reading the documents!

**Comment by palmerr23** [comment]
BTW, I've just written a little utility to manage OTA and LittleFS files.

It will be at https://github.com/palmerr23/PICO_OTA shortly.

**Comment by earlephilhower** [comment]
Neat, but the README's a little out of date (about a week).  There is now a LittleFS upload for IDE 2.x: https://github.com/earlephilhower/arduino-littlefs-upload/releases .
