### ISSUE TITLE
Not an issue, just a thank you

### ISSUE THREAD

**Issue by pstimpel** [earlephilhower/arduino-pico#18]
Sorry for abusing the issue tracker

**Comment by marcelvanherk** [comment]
Agree, amazing work!

**Comment by earlephilhower** [comment]
No problem!  I've been doing a lot of work on the ESP8266 Arduino port (https://github.com/esp7266/Arduino), but came in to help well after it was started.  Here, I get to see the actual sausage making process from the beginnings which is interesting.

Best way to say "thanks" is with PRs for code or documentation, or helping other folks use it. :)
