### ISSUE TITLE
exiting bootloader without physical interaction with the board

### ISSUE THREAD

**Issue by jonspieg** [earlephilhower/arduino-pico#1827]
Is there a way of exiting bootloader mode without physically interacting with the device?
From my experience, only uploading a new uf2 file initiates a reboot without manually resetting the board, is there another way?

Ideally there would be a timeout for staying in mass storage mode (we added this functionality for the ESP32-S2 and it worked well).

**Comment by earlephilhower** [comment]
The bootloader is baked into the ROM on the RP2040.  There's nothing we can do here about its behavior.  I suggest you offer this suggestion in the official Raspberry Pi forums.
