### ISSUE TITLE
unsolicited ports open on the standard webserver example w5500

### ISSUE THREAD

**Issue by jonspieg** [earlephilhower/arduino-pico#1829]
I'm running a simple web server on a specific port, however when I run an nmap check I see that other than the desired port I have both 143 and 1720 tcp ports open. Why is that?

How can I disable it?

I'm using Wiznet W5500-EVB-Pico board

Thanks

**Comment by earlephilhower** [comment]
Please double check your IP assignment and nmap output.  There's definitely no IMAP(port 143) server running on the Pico.  My own board, running HelloServer.ino (commenting out MDNS) on a W5100 gives the expected output:
````
earle@amd:/tmp$ nmap 192.168.1.191
Starting Nmap 7.80 ( https://nmap.org ) at 2023-11-20 08:38 PST
Nmap scan report for 192.168.1.191
Host is up (0.055s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
80/tcp open  http

Nmap done: 1 IP address (1 host up) scanned in 7.19 seconds
````
