### ISSUE TITLE
Invalid path for picotool in platform.txt

### ISSUE THREAD

**Issue by ruswerner** [earlephilhower/arduino-pico#1835]
Uploading via `picotool` fails due to a bad path in platform.txt:

```
$ arduino-cli upload --verbose -b rp2040:rp2040:rpipicow:wificountry=usa,uploadmethod=picotool -p /dev/tty.usbmodem21401

"/Users/x/Library/Arduino15/packages/rp2040/tools/pqt-picotool/2.1.0-a-d3d2e6b/picotool" load "/private/var/folders/yl/rklkq5d55vd1667wszr366tm0000gn/T/arduino/sketches/1026D17EFC05482E362F1FA82046CBF5/pico_arduino_test.ino.uf2" -f
Failed uploading: cannot execute upload tool: fork/exec /Users/x/Library/Arduino15/packages/rp2040/tools/pqt-picotool/2.1.0-a-d3d2e6b/picotool: no such file or directory
```

https://github.com/earlephilhower/arduino-pico/blob/1020023eab73da7476d1b2535490b24a9e8500f6/platform.txt#L205

The line should be:

```
tools.picotool.upload.pattern="{cmd}/bin/picotool" load "{build.path}/{build.project_name}.uf2" -f
```

... adding `/bin` to the path.

Consequently, after fixing this I get the `Library not loaded: '/usr/local/opt/libusb/lib/libusb-1.0.0.dylib` error since I'm on a M1 mac and have libusb 1.0.26 installed. Argh.

**Comment by earlephilhower** [comment]
Thanks for the report.  It's a little more complicated, sadly.  The `Makefile` generated `picotool` executables (5-6 different Linux systems) don't have `/bin/` in the path, while the Win32/64 and Mac manually make and install into a `/bin/` subdir.

Looking at the other mini tools, none have `/bin` so I will normalize things and update the Mac and Windows toolsets to the right path...
