### ISSUE TITLE
Feature Request: Clear AP List in WiFiMulti

### ISSUE THREAD

**Issue by richteel** [earlephilhower/arduino-pico#1846]
I'm using WiFiMulti and wanted the ability to load a new AP list when the configuration has been updated. I found that the AP List is not publicly accessible and adding the same SSID to the AP List, creates duplicates. I see a few options to change the WiFiMulti class to address this issue.

One is to create a new method to clear the list. (This is the same code that is present in the destructor.)
```cpp
void WiFiMulti::clearAPList() {
    while (!_list.empty()) {
        struct _AP ap = _list.front();
        _list.pop_front();
        free(ap.ssid);
        free(ap.pass);
    }
}
```

A second, perhaps better option is to modify the addAP method to modify the password value for a SSID if it already exists in the AP List.

If this issue should be added to another repository to help propagate this request to all platforms, please point me to the best repository and I will create the issue there. I just happen to be using a Raspberry Pi Pico W, which is why I posted it here.

**Comment by earlephilhower** [comment]
That seems fine.  Would you like to make the PR for it?  (FWIW, the WiFiMulti code here is all mine and there's no generic upstream that I know of, so this would be the spot to do the PR.)

**Comment by richteel** [comment]
Just created the PR.
