### ISSUE TITLE
Bug in version 3.6.1 - BLE keyboard option does not work

### ISSUE THREAD

**Issue by mwwojcik2017** [earlephilhower/arduino-pico#1847]
Hi, after update from version 3.6.0 to 3.6.1 my simple code for BLE keyboard stopped working completely - the board is not responding when connected to the laptop via BLE. When downgraded to 3.6.0 same code started working again.
Please investigate.
I am using following libraries:

#include <KeyboardBLE.h>
#include <Keypad.h>

**Comment by earlephilhower** [comment]
Sorry, you will need to post a complete, short MCVE.  The example keyboard BLE run fine here (in fact they were used to debug #1817).
