### ISSUE TITLE
Feature Request:  Add Waveshare RP2040-Pi Zero

### ISSUE THREAD

**Issue by LeonardoCT** [earlephilhower/arduino-pico#1870]
Board name: "RP2040-PiZero"

Additional information:
[https://www.waveshare.com/wiki/RP2040-PiZero](url)
[https://files.waveshare.com/wiki/RP2040-PiZero/RP2040-PiZero-Schematic.pdf](url)

**Comment by Stass48** [comment]
It's already working. I have exactly this board. See my answer.

[](https://github.com/earlephilhower/arduino-pico/discussions/1854)

earlephilhower, please pay attention to my questions in that thread.
