### ISSUE TITLE
SPI transfer16 operation changed in v3.6.1

### ISSUE THREAD

**Issue by Bodmer** [earlephilhower/arduino-pico#1879]
Some SPI devices require 16 bit command data transfers:
![LSM330 SPI read](https://github.com/earlephilhower/arduino-pico/assets/15824805/a5501ddc-8679-43a9-b822-61e440b487c4)

These devices worked fine prior to v3.6.1 since a true 16 bit transfer occured and the chip select was raised at the end of the 16 bit transfer (clock (blue) and CS(red) signals shown):
![transfer16 v3_6_0](https://github.com/earlephilhower/arduino-pico/assets/15824805/a7277925-fcec-4bcc-b2f4-f98297fb435f)

If CS is raised in the middle of the 16bit transfer then the device aborts the command and fails to return data.

In v3.6.1 the 16 bit transfer is split into two 8 bit transfers, this causes problems with some devices:
![transfer16](https://github.com/earlephilhower/arduino-pico/assets/15824805/c41a8af8-a06c-43b6-a827-a19b90475b65)

It is not clear why this change as been made since there is a performance penalty and it now precudes the use of transfer16() in some SPI peripheral device cases.  Note: it is safe to change the format from 8 to 16 bits, providing checks are made that the SPI FIFO buffer is clear and transfer is complete. In the case where DMA is used then it must be checked that the DMA is complete AND the SPI port has completed transfer of the last bytes/words. If these checks are not made then glitches/faults can occur in the transfer/data signals.

The short term work-around is to change user code to manage the chip select under software control. but this is inconvenient...

**Comment by earlephilhower** [comment]
#1760 was the original reason for the change.  There were glitches on the SPI bus when changing formats (even when changing to the "same settings") with the latest SDK so I tried to factor out any changes.  I could have sworn that I tested a `transfer16` as 2 8-byte writes and did not see the CS toggle.  Do you have a timescale for the CS deassert in your 2nd image?  Maybe my LA isn't fast enough to grab it.

**Comment by Bodmer** [comment]
I set the clock rate to 1MHz giving  a clock period of 1us, CS is high for half a clock period between bytes, i.e 500ns in this case.

I just tried 10kHz clock rate and the CS is high between bytes for 50us. So if you logic analyser is slow then reduce the SPI clock rate.

The glitches sound like a problem introduced into the SDK?  Has an issue been raised for this? Is there some test code I can try that demonstrates these glitches? I am not convinced this is the root cause of the #1760 problem, given the issue title says "SPI crashes when invoked from different parts of the program" makes me suspect there is an issue in the user code not the SDK.

**Comment by earlephilhower** [comment]
I think it was a PEBKAC and I was looking at a SW CS pin when verifying it, d'oh!  I was able to reproduce the failure on the example in #1882, so it's absolutely repro'd and a problem.  #1882 uses the fast bitset to give the proper results AFAICT using the simple test I ran, but you've obviously got much more intricate apps to test on...

**Comment by Bodmer** [comment]
OK, all is good with that change. Thanks.
