### ISSUE TITLE
Error: Mysql and LiquidCrystal I2C

### ISSUE THREAD

**Issue by cidminh** [earlephilhower/arduino-pico#1926]
i have error mysql and LiquidCrystal I2C when upload Pico

WARNING: library LiquidCrystal I2C claims to run on avr architecture(s) and may be incompatible with your current board which runs on rp2040 architecture(s).
c:\Users\MINH\Documents\Arduino\libraries\MySQL_Connector_Arduino\src\MySQL_Encrypt_Sha1.cpp: In member function 'virtual size_t Encrypt_SHA1::write(uint8_t)':
c:\Users\MINH\Documents\Arduino\libraries\MySQL_Connector_Arduino\src\MySQL_Encrypt_Sha1.cpp:89:1: error: no return statement in function returning non-void [-Werror=return-type]
   89 | }
      | ^
c:\Users\MINH\Documents\Arduino\libraries\MySQL_Connector_Arduino\src\MySQL_Encrypt_Sha1.cpp: In member function 'virtual size_t Encrypt_SHA1::write(uint8_t*, int)':
c:\Users\MINH\Documents\Arduino\libraries\MySQL_Connector_Arduino\src\MySQL_Encrypt_Sha1.cpp:95:1: error: no return statement in function returning non-void [-Werror=return-type]
   95 | }
      | ^
cc1plus.exe: some warnings being treated as errors

exit status 1

Compilation error: exit status 1

**Comment by earlephilhower** [comment]
Your library has a fatal bug, as GCC explains:
````
 c:\Users\MINH\Documents\Arduino\libraries\MySQL_Connector_Arduino\src\MySQL_Encrypt_Sha1.cpp:95:1: error: no return statement in function returning non-void [-Werror=return-type]
````

I suggest showing this error to the library maintainer so he can correct it.
