### ISSUE TITLE
EEPROM.commit() hangs after updating from 3.6.1 to 3.6.3

### ISSUE THREAD

**Issue by danyhm** [earlephilhower/arduino-pico#1937]
hello,

as the title suggests , EEPROM.commit() hangs after updating from 3.6.1 to 3.6.3/

related?
#719

**Comment by earlephilhower** [comment]
#719 was an application error where they were blocking the 2nd core and trying to write from the other one.

The `EEPROM_WRITE` example runs fine in my tests, so please post a small, self-contained MCVE that shows what you're seeing.

A diff of 3.6.3 against 3.6.1 shows no `EEPROM` differences and no `idleOtherCore` code changes, either.

**Comment by earlephilhower** [comment]
No update from reporter, closing.
