### ISSUE TITLE
Missing pin definitions

### ISSUE THREAD

**Issue by kingfisher09** [earlephilhower/arduino-pico#1940]
Hi,

I'm a complete noob so I think there is a high chance I've misunderstood something. I am trying to use this library with an Arduino Nano rp2040 Connect. This works just fine but when I try to use the [RP2040_PWM](https://github.com/khoih-prog/RP2040_PWM) library I get the error:
`pinDefinitions.h: No such file or directory
   41 | #include "pinDefinitions.h"`
When trying to compile the examples. 
The example compiles if I use the Arduino MBED OS package but that does not seem to support the multi threading that I need for my project.
That library specifically lists compatibility with both the board and this library. 
When I went looking through the package files of this library I didn't find a pin definitions file though I did find it in the files for the Arduino package. 

Am I missing something obvious that I can do to fix this issue?

Thanks

**Comment by earlephilhower** [comment]
Sorry, that's not one of our files and never been part of the core.  Maybe you need to make it yourself to define pinouts or something?  I think you'll need to contact the library's owner (however it looks like the repo was archived so maybe isn't supported anymore).  Good luck!
