### ISSUE TITLE
New option request: default_binary_type settings for compiler

### ISSUE THREAD

**Issue by aotta** [earlephilhower/arduino-pico#1942]
Hello and my compliments for arduino-pico! this is not really an issue but i'd like to have an option for setting the binary_type settings (default. no_flash, copy_to_ram, etc.).
I found in SDK that cmakelist.txt uses that options, but didn't find any way for setting it via Ide setting, neither an easy way to manage it.
Sorry i'm not a CMake expert and maybe there is an easy solutions i don't know.

**Comment by earlephilhower** [comment]
That's not readily possible here, unfortunately, as I think about it.  The way that OTA and the dual-stage boot works means that RAM-only configs aren't possible without significant changes to the build and link process.  Your best bet is to use the SDK itself or decorate any functions you need in RAM for speed with the `__no_inline_not_in_flash_func()` decorator like [here](https://github.com/earlephilhower/arduino-pico/blob/916c31d934c5e3dc4f925e3e5767dc298a77ddb2/cores/rp2040/RP2040Support.h#L133).
