### ISSUE TITLE
Feature Request: Writing to SingleFileDrive

### ISSUE THREAD

**Issue by Nerdtronaut** [earlephilhower/arduino-pico#1954]
It would be super helpful if it was possible to edit files in SingleFileDrive mode on a PC. Thanks for considering!

**Comment by earlephilhower** [comment]
Unfortunately that's not really possible.  There is no real FAT filesystem in use, only a simulated one with very strict assumptions (hence the ability to use LittleFS on the Pico but "see" a FAT-16 drive on the PC).

The way to make this happen would be to do a real on-flash FAT filesystem.  Then there would be no `SingleFileDrive` emulation needed, only a direct memory exposure.

**Comment by earlephilhower** [comment]
Closing as this is not possible, and #2028 would give the desired outcome.
