### ISSUE TITLE
[Feature Request] Wiznet W6100 

### ISSUE THREAD

**Issue by Wxchris071** [earlephilhower/arduino-pico#1971]
Is it possible to add support for the W6100?
I'd like to use IPv6 with WebServerSecure on W6100-EVB-Pico.
The Ethernet Library from Wiznet already supports the W6100 and IPv6, but no Secure Webserver.

**Comment by earlephilhower** [comment]
I don't have any W6100 boards, but if you do then you may want to try your hand at writing a driver yourself.

The [W5100](https://github.com/earlephilhower/arduino-pico/tree/master/libraries/lwIP_w5100) or [W5500](https://github.com/earlephilhower/arduino-pico/tree/master/libraries/lwIP_w5500) libraries are very simple and basically set up a raw bypass mode for those chips and stream raw bits in and out.

**Comment by JAndrassy** [comment]
here the IPv6 and WebServerSecure are not in the chip. so you can use the m with W5500 too

**Comment by Wxchris071** [comment]
@earlephilhower Maybe in my freetime i can try writing a driver for it.
@JAndrassy You're right. I successfully established an IPv6 Connection with WebServerSecure on W5100S-EVB-Pico.

**Comment by earlephilhower** [comment]
Closing for now since the other, lower-end WizNet boards are running and give the needed  IPV6
