### ISSUE TITLE
Request for  upload Uf2 file ,will need to without hold the BOOTSEL button

### ISSUE THREAD

**Issue by maxmurugan** [earlephilhower/arduino-pico#1982]
hi sir
upload Uf2 file ,will need to without hold the BOOTSEL button

because led board fully covered incase any program change to open led board and press the bootsel button .

How to connect USB cable and upload UF2 file ?

please help

**Comment by earlephilhower** [comment]
As long as you don't crash the Pico, it uploads w/o requiring a BOOTSEL reset through the USB 1200bps tickle.  If your code crashes, the Pico can't monitor the USB port and will need a hard reset/BOOTSEL to get out of that state.
