### ISSUE TITLE
uf2conv.py cause warning message during upload phase

### ISSUE THREAD

**Issue by AlainF-ing** [earlephilhower/arduino-pico#1983]
During upload preparation I receive this Warning message:
.arduino15/packages/rp2040/hardware/rp2040/3.7.0/tools/uf2conv.py:264: SyntaxWarning: invalid escape sequence '\s'
The upload complete correctly.
I have seen a similar warning from Python.
  words = re.split('\s+', line)
 was replaced by   words = re.split('\\s+', line) 
I do not have experience with the "Pull request ..." 
I may be wrong.

I am impressed by this rp2040 lib, very good work !

**Comment by earlephilhower** [comment]
I think you meant to change it to the following (adding `r` to make the string a regexp), no?  Your before and after were the same...
````
 words = re.split(r'\s+', line)
````

**Comment by AlainF-ing** [comment]
Sorry for this typo.
I actually get rid of the warning using this 
words = re.split('\\s+', line)

Your choice is probably better than mine.

Best regards Earle
