### ISSUE TITLE
Is it support Arduino IDE in macOS?

### ISSUE THREAD

**Issue by Dracanrage** [earlephilhower/arduino-pico#2]
I have do the instruments in README on my Mac, but seems the arduino IDE can't identify the develop board.
<img width="212" alt="image" src="https://user-images.githubusercontent.com/30333935/111565679-c0a93d80-87d6-11eb-946e-ae206f689c1e.png">
<img width="286" alt="image" src="https://user-images.githubusercontent.com/30333935/111565745-dc144880-87d6-11eb-8c42-0b6ef57402bd.png">

**Comment by earlephilhower** [comment]
I'm not a Mac user, but I will try my best.  Since it is not showing the boards at all, the `hardware` directory may be in the wrong spot.

`hardware` should be in the same directory as your sketches.  Under Linux, that's `~/Arduino/`, on Windows it's `\Users\XXX\Documents\Arduino\`.  There's some place similar on the Mac.

Good luck!

**Comment by Dracanrage** [comment]
> I'm not a Mac user, but I will try my best. Since it is not showing the boards at all, the `hardware` directory may be in the wrong spot.
> 
> `hardware` should be in the same directory as your sketches. Under Linux, that's `~/Arduino/`, on Windows it's `\Users\XXX\Documents\Arduino\`. There's some place similar on the Mac.
> 
> Good luck!

Thanks!
I finally now how to deal with it, I have put it in wrong path, now I can find it in IDE.
But when I try to compile it, it shows errors as below:
```
In file included from /Users/mac/Documents/Arduino/pico_main/pico_main.ino:4:
/Users/mac/Documents/Arduino/hardware/pico/rp2040/cores/rp2040/Arduino.h:28:10: fatal error: api/ArduinoAPI.h: No such file or directory
   28 | #include "api/ArduinoAPI.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by Dracanrage** [comment]
> > I'm not a Mac user, but I will try my best. Since it is not showing the boards at all, the `hardware` directory may be in the wrong spot.
> > `hardware` should be in the same directory as your sketches. Under Linux, that's `~/Arduino/`, on Windows it's `\Users\XXX\Documents\Arduino\`. There's some place similar on the Mac.
> > Good luck!
> 
> Thanks!
> I finally know how to deal with it, I have put it in wrong path, now I can find it in IDE.
> But when I try to compile it, it shows errors as below:
> 
> ```
> In file included from /Users/mac/Documents/Arduino/pico_main/pico_main.ino:4:
> /Users/mac/Documents/Arduino/hardware/pico/rp2040/cores/rp2040/Arduino.h:28:10: fatal error: api/ArduinoAPI.h: No such file or directory
>    28 | #include "api/ArduinoAPI.h"
>       |          ^~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```

Oh, I find the README now, it really works, thanks!
