### ISSUE TITLE
"Forcing software SPI - no hardware SPI for you!"

### ISSUE THREAD

**Issue by Gavin-Perry** [earlephilhower/arduino-pico#2005]
Surely with all it's power and the PIO FEATURE the RP2040 should support hardware SPI. 
It's an issue for FastLED and probably other libraries that want to use SPI. While RP2040 is powerful enough to do some bitbanging it could get jittery when supporting multiple strips like OctoWS2811 though I haven't tried that yet.
If DMX can do it FastLED should, but where is the issue? In arduino-pico or in FastLED?

Thanks Earl for all your amazing support!

**Comment by earlephilhower** [comment]
Err, sorry but there's nothing to be done here.  We support `SPI` and `SPI1` and lots of folks use them extensively for things like the wired Ethernet chips or displays.  I suggest you check the library and see if they have some manually `#ifdef BOARD1....#elif defined BOARD2....#else <SW SPI>...#endif` construct.
