### ISSUE TITLE
analogWrite() prevents digitalWrite() from working

### ISSUE THREAD

**Issue by oerkel47** [earlephilhower/arduino-pico#202]
When using digitalWrite() after using analogWrite() on a gpio the output doesn't change. 

Pair this simple example with an LED for quick visual proof.

```
void setup() {

	pinMode(20, OUTPUT);
}
	


void loop() {

	digitalWrite(20, HIGH);
	delay(1000);
	digitalWrite(10, LOW);
	delay(1000);
	analogWrite(20, 20);
	delay(1000);

}
```

edit: added video, see LED being stuck on low analogWrite value in the end instead of switching up between high/low/pwm.

https://user-images.githubusercontent.com/57231822/121536068-0571f880-ca03-11eb-9e6c-3af800175536.mp4

**Comment by earlephilhower** [comment]
You've got a bug in the sample code (the 2nd `digitalWrite` should write to pin 20), but I was able to repro this.

Basically the analogWrite set an output mux value that digitalWrite never overwrote, so it would always be stuck w/the PWM on the pin (until a `pinMode()` call).  A 1-line fix takes care of it..

**Comment by oerkel47** [comment]
Uhh, yep that was just a typo here on github. Thanks for fixing!
