### ISSUE TITLE
Cannot use stdio_usb_connected()

### ISSUE THREAD

**Issue by neilmendoza** [earlephilhower/arduino-pico#2024]
Is is possible to use stdio_usb_connected() in stdio_usb.h with this core? Doesn't seem to be any way to use it as is and don't want to start messing with the cmake files if it's not possible. Thanks!

**Comment by earlephilhower** [comment]
No, you need to use Arduino specific calls like `while (!Serial) { delay(1);}`.  The core controls the USB port here, not the SDK.
