### ISSUE TITLE
Bug in SDClass.end(..) ?

### ISSUE THREAD

**Issue by sillycowvalley** [earlephilhower/arduino-pico#2034]
I suspect this is a mistake (highlighted below).

Consider calling  `begin(..)` above with a reference to SPI1, not SPI.

![image](https://github.com/earlephilhower/arduino-pico/assets/89331909/8f5742ae-b160-4fe9-bdec-03d31a7ed7f9)

Reference:
https://github.com/earlephilhower/arduino-pico/blob/master/libraries/SD/src/SD.h

**Comment by earlephilhower** [comment]
Yeah, that's an oversight.   Since you found it, want to do a PR to fix it?  You'll need to preserve the `HArdwreSPI&` passed in on `begin` and shut it off here...
