### ISSUE TITLE
Can't figure out how to get assertion failure messages from Pico SDK functions

### ISSUE THREAD

**Issue by wareya** [earlephilhower/arduino-pico#2035]
I'm trying to set up an SPI Slave device, but it's hanging/crashing/panicking inside of a Pico SDK function (irq_set_enabled). But no matter what I do (overwriting defines etc) I can't seem to get all assertion messages to output over serial, so I can't figure out where it's dying or what error condition I'm hitting. I'm using the Arudiono IDE 2.3.0 and the 3.7.2 version of this core (with 77209a12ccf7c940f92591a0826cea2204c09f47 manually applied).

My code:

```c++
// based on the SPISlave spi-to-self example

#include <SPI.h>
#include <SPISlave.h>

SPISettings spisettings(2000000, MSBFIRST, SPI_MODE3);

volatile bool recvBuffReady = false;
uint8_t recvBuff[40000];
int recvIdx = 0;
void recvCallback(uint8_t * data, size_t len)
{
    memcpy(recvBuff + recvIdx, data, len);
    recvIdx += len;
    recvBuffReady = true;
}

void sentCallback() { }

void setup()
{
    Serial.begin(2000000);
    delay(3000);
    Serial.println("Beginning...");
    delay(50);
    Serial.println("INFO: setting callback");
    SPISlave.onDataSent(sentCallback);
    SPISlave.onDataRecv(recvCallback);
    Serial.println("INFO: about to start spi");
    SPISlave.begin(spisettings);
    Serial.println("INFO: spi started");
}

void loop()
{
    if (recvBuffReady)
    {
        recvBuffReady = false;
        Serial.printf("got data, starting with: 0x%X02\n", recvBuff[0]);
    }
}
```

I also modify SPISlave.cpp like follows:

```c++

void SPISlaveClass::begin(SPISettings spis) {
    DEBUGSPI("SPISlave::begin(), rx=%d, cs=%d, sck=%d, tx=%d\n", _RX, _CS, _SCK, _TX);
    gpio_set_function(_RX, GPIO_FUNC_SPI);
    gpio_set_function(_CS, GPIO_FUNC_SPI);
    gpio_set_function(_SCK, GPIO_FUNC_SPI);
    gpio_set_function(_TX, GPIO_FUNC_SPI);
    if (_initted) {
        DEBUGSPI("SPISlave: deinitting currently active SPI\n");
        spi_deinit(_spi);
    }
    DEBUGSPI("SPISlave: initting SPI\n");
    spi_init(_spi, _spis.getClockFreq());
    DEBUGSPI("SPISlave: actual baudrate=%u\n", spi_get_baudrate(_spi));
    delay(50);
    spi_set_slave(_spi, true);
    spi_set_format(_spi, 8, cpol(spis), cpha(spis), SPI_MSB_FIRST);
    DEBUGSPI("SPISlave: finished setting slave status and format\n");
    delay(50);

    // Install our IRQ handler
    if (_spi == spi0) {
        irq_set_exclusive_handler(SPI0_IRQ, _irq0);
    } else {
        irq_set_exclusive_handler(SPI1_IRQ, _irq1);
    }
    DEBUGSPI("SPISlave: finished installing IRQ handlers\n");
    delay(50);
    // Set to get IRQs on transmit and receive
    spi_get_hw(_spi)->imsc = 2 | 4 | 8 ; // RTIM + RXIM + TXIM (not RORIM)
    _initted = true;

    DEBUGSPI("SPISlave: got hw\n");
    delay(500);
    DEBUGSPI("SPISlave: still got hw\n");

    irq_set_enabled(_spi == spi0 ? SPI0_IRQ : SPI1_IRQ, true);

    DEBUGSPI("SPISlave: finished enabling IRQs\n");
    delay(50);
}
```
And the final debug line never prints. Whatever assertion or panic fires inside of `irq_set_enabled` never makes it over `Serial`, and `puts` lines that I insert into Pico SDK files don't seem to have an effect (maybe whatever this core does to make stdio work over serial doesn't apply to the Pico SDK) so I can't figure out where it's breaking. Any pointers in the direction of getting the SDK's error messages working would be fantastic.

**Comment by earlephilhower** [comment]
Use `GDB` in cases like this.  There is no crash, you're stuck in an infinite loop.  Using GDB you can see the issue is not loading the SPI output FIFO so the TX FIFO empty IRQ never clears and you keep getting that interrupt and callback.

The slave must pre-load the data to send using the `sentCallback`, that's just due to timing constraints.  So fix the sent callback to stuff data, like in the example, and you should be fine.
