### ISSUE TITLE
Arduino IDE 2.3.2 debuging with picoprobe / how to catch serial out from target pico

### ISSUE THREAD

**Issue by SJegorovs** [earlephilhower/arduino-pico#2046]
Hello together,

after a longer break im back to my studies to program and debug a pico using picoprobe with the newest release of picoprobe and CMSIS-DAP. Uploading and debuging works good, but I'm not able, to connect a serial monitor window to the target pico. My settings in the tool-section are as follows:

[Arduino IDE picoprobe Settings.pdf](https://github.com/earlephilhower/arduino-pico/files/14537703/Arduino.IDE.picoprobe.Settings.pdf)

Does someone had the same problem and solved it in the past? Is there a treat, where I can find the solution for this problem.

I hope toget some hints from you soon.

Best regards
Sven

**Comment by earlephilhower** [comment]
Dup of #2045 .
