### ISSUE TITLE
SerialUART.cpp: Hardware Flow Control configuration (RTS/CTS)

### ISSUE THREAD

**Issue by sam68ud** [earlephilhower/arduino-pico#2047]
Hi,
I believe there could be an error in the library regarding the uart hw flow control setting function:  SerialUART.begin()
In detail this function call: 
    _**uart_set_hw_flow(_uart, _rts != UART_PIN_NOT_DEFINED, _cts != UART_PIN_NOT_DEFINED);**_ 

The function is defined in uart.h: 
_**static inline void uart_set_hw_flow(uart_inst_t *uart, bool cts, bool rts)**_

As we can see the parameters rts and cts are exchanged with each other: the first parameter must be cts, second parameter rts.
There's no problem if you enable both rts and cts at the same time, but if you would like to use cts or rts flow control separately the behavior will be incorrect.

Regards

![image](https://github.com/earlephilhower/arduino-pico/assets/41929718/5d6d4d66-3da7-416f-8562-99cbd8b71800)

**Comment by earlephilhower** [comment]
Looks like you spotted a bug, want to submit a PR to swap rts/cts in the call?

**Comment by sam68ud** [comment]
Ok. Well.
Thanks

**Comment by sam68ud** [comment]
Thanks Earle.
Regards
Samuel


Il dom 10 mar 2024, 21:23 Earle F. Philhower, III ***@***.***>
ha scritto:
