### ISSUE TITLE
Enhancement request: increase lwIP buffers

### ISSUE THREAD

**Issue by obdevel** [earlephilhower/arduino-pico#2050]
Re our discussion at https://github.com/earlephilhower/arduino-pico/issues/2032 and my experiments with high throughput TCP and UDP traffic.

I have memory to spare but I can't currently use it for larger IP stack buffers.

It would be very useful to have an option for larger lwIP buffers, maybe 32KB and 64KB. I think this would require multiple builds of libpico.a, etc, and a new menu option, with the current 16KB being the default.

I can rebuild libpico.a as you suggested, but this isn't a viable solution for less technical users.

Thanks.

**Comment by earlephilhower** [comment]
Did you increase the buffers and have it correct the timeout problem?  I'm not sure it's the actual buffers vs. some other config option for LWIP...
