### ISSUE TITLE
RP2040 and QNEthernet library issue

### ISSUE THREAD

**Issue by 5b4wn** [earlephilhower/arduino-pico#2071]
Dear @earlephilhower 

MANY THANKS FOR YOUR CORE libraries. Amazing work. I am trying to compile with the help of @ssilverman QNEthernet library which is an amazing ethernet library but running issues with some of the included files WString.h IPAddress.h  (https://github.com/ssilverman/QNEthernet/issues/70#issuecomment-2016607802).

Are you able to make some suggestions please?

BW
@5b4wn

**Comment by JAndrassy** [comment]
why would you want to use QNEthernet with the Pico Core? Pico Core has its own LwIP base library which supports W5500

**Comment by earlephilhower** [comment]
We already natively support LWIP on the WizNet and other Ethernet adapters.  See the LWIP_xxx examples.

We also hove those two headers as they're standard Arduino API.
