### ISSUE TITLE
Run the code in RAM without flashing?

### ISSUE THREAD

**Issue by bgolab** [earlephilhower/arduino-pico#2089]
Hi,
In the original PICO SDK I was able to select the binary type to be able to run the code in RAM without flashing the board:

**pico_set_binary_type(TARGET no_flash)** (a part of CMakeLists.txt)
or 
**-DPICO_NO_FLASH=1**

Is this possible here to configure the linker in such way?

Thanks you.

**Comment by bgolab** [comment]
I am not talking about the same syntax. I wonder if there is any way to link the code in the RAM space.

**Comment by earlephilhower** [comment]
No, the second stage bootloader for OTA support would make that basically impossible.  You'll need to use the raw SDK to get a RAM-only build.  Good luck!
