### ISSUE TITLE
Add wifinina defines in nano connect boards.txt

### ISSUE THREAD

**Issue by earlephilhower** [earlephilhower/arduino-pico#2092]
Add

WiFiNINA works with any Arduino. just create boards.local.txt with -D for pins. for Nano Connect the pins are
```
<board>.build.extra_flags=-DPIWIFI=(SPI1) -DSPIWIFI_SS=(9u) -DSPIWIFI_ACK=(10u) -DSPIWIFI_RESET=(3u) -DNINA_GPIO0=(2u)
```

_Originally posted by @JAndrassy in https://github.com/earlephilhower/arduino-pico/discussions/2091#discussioncomment-9034912_

**Comment by JAndrassy** [comment]
Nano Connect itself has these in pins_arduino.h
in that discussion OP wants to use Nano Connect with a different board selected in Tools menu, but still access the NINA module

**Comment by earlephilhower** [comment]
Invalid, already set up properly
