### ISSUE TITLE
My code doesn't see rp2040.rebootToBootloader();

### ISSUE THREAD

**Issue by fapplin** [earlephilhower/arduino-pico#2096]
Hi,

I just upgraded your library to the latest and I'm using the Arduino IDE 2.3.2. I get an error on rp2040.rebootToBootloader(); - which use to work in a previous version of your library and in the IDE 1.8. When I type "rp2040." I see all of the methods in the new IDE (which is nice), but I don't see rebootToBootloader() as one of the methods. Any ideas?

Frank

**Comment by fapplin** [comment]
Just an added comment - it compiles just fine with your new library under the Arduino IDE 1.8.19.

**Comment by earlephilhower** [comment]
Can you clarify?  Is it the code doesn't compile or the IDE doesn't hilight it?

**Comment by fapplin** [comment]
The code doesn't compile.
======================================================================= 
The price of greatness is responsibility. - Winston Churchill 

    On Wednesday, April 10, 2024 at 04:02:19 AM EDT, Earle F. Philhower, III ***@***.***> wrote:  
 
 


Can you clarify? Is it the code doesn't compile or the IDE doesn't hilight it?

**Comment by earlephilhower** [comment]
I'm traveling this week, but think I know what's going on.

Double check you're using this core and not the official Arduino one.  The Arduino core has no such function, only this one.

The actual source code and compile steps are self contained in this repo, so what you're seeing seems to be only possible if after changing the IDE it isn't using this core.

**Comment by earlephilhower** [comment]
I just tried compiling the simple sketch below with 2.3.2 IDE:
````
void setup() {
rp2040.rebootToBootloader();
}
void loop() {
}
````
and did not encounter any errors.  I imagine it really was a matter of ending up with the Arduino official core and not this one.  Good luck!
