### ISSUE TITLE
Error in Project configuration on PlatformIO

### ISSUE THREAD

**Issue by MicSG-dev** [earlephilhower/arduino-pico#2099]
I am facing some errors when trying to create a project using Arduino-Pico with PlatformIO. When pasting the following code into platformio.ini:
```
[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = Generic
framework = arduino
board_build.core = earlephilhower
board_build.flash_size = 16MB ; Flash Size: 16MB
board_build.filesystem_size = 4mb ; Sketch: 12MB, FS: 4MB
```
and when PlatformIO compiles the project configurations, the following error is displayed in the output of "PlatformIO: Project Configuration":
```
Resolving pico dependencies...
Tool Manager: Installing git+https://github.com/earlephilhower/arduino-pico.git#88ccf0c256dc717ff932adc9e2d84485214bf2e5
git version 2.43.0.windows.1
Cloning into 'C:\Users\MichelGalvao\.platformio\.cache\tmp\pkg-installing-xt3vmxh9'...

error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 2051 bytes of body are still expected

fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF

fatal: fetch-pack: invalid index-pack output

VCSBaseException: VCS: Could not process command ['git', 'clone', '--recursive', 'https://github.com/earlephilhower/arduino-pico.git', 'C:\\Users\\MichelGalvao\\.platformio\\.cache\\tmp\\pkg-installing-xt3vmxh9']

```
I already followed the steps in the documentation to enable the long path in Windows and it didn't help.

**Comment by earlephilhower** [comment]
Your error messages seen to indicate a network connection issue and not anything with the core itself.  Could also have been something transient with the GH hosting/mirrors.  You may want to check your network config, any proxy settings, etc. and give the `git clone` command a try from the command line.  Nothing we can do here about those, unfortunately.  Good luck!
