### ISSUE TITLE
Compile Error for attachinterrupt() 

### ISSUE THREAD

**Issue by aayushgavande** [earlephilhower/arduino-pico#21]
I assume the attachInterrupt() function has not yet been added, it would be great if you add it, as interrupts using micro python are really slow and thanks a lot for this repo.

**Comment by earlephilhower** [comment]
@aayushgavande are you able to test against the GIT version of the tree?  Adding `attachInterrupt` supports looks pretty simple thanks to the great Pico SDK, but I don't have any really good test cases other than shorting a pin with a jumper...

**Comment by aayushgavande** [comment]
I will try installing it with the GIT version, and talking about the test cases you can always try using different sensors with it or you can use a frequency generator to create the pulse with desired frequency and then doing some operations in the isr like incrementing the count. 

Thank You.

**Comment by earlephilhower** [comment]
See #22.  In the worst case you can just overwrite the two changed files in your installation and give it a go.

**Comment by aayushgavande** [comment]
> See #22. In the worst case you can just overwrite the two changed files in your installation and give it a go.

Thanks a lot works great.
