### ISSUE TITLE
UnknownPackageError: Could not find the package

### ISSUE THREAD

**Issue by HiImCris** [earlephilhower/arduino-pico#2103]
Hello.
Whenever I try to build a project with PlatformIO on Visual Studio Code, I get the following error:

> UnknownPackageError: Could not find the package with 'earlephilhower/tool-pioasm-rp2040-earlephilhower @ ^5.100300.220714' requirements for your system 'windows_amd64'

I'm no programmer. I'm just trying to follow a tutorial. I googled it and tried some workarounds, like installing stuff through Git Bash and Powershell. The error message I received before that was

> Submodule path 'pico-sdk/lib/tinyusb/tools/uf2/hidapi': checked out 'a6a622ffb680c55da0de787ff93b80280498330f'
>fatal: Failed to recurse into submodule path 'pico-sdk/lib/tinyusb'
>fatal: Failed to recurse into submodule path 'pico-sdk'

After messing with Git and Pshell, I started to get UnknownPackageError.

If it helps, I'm using Windows 11.

**Comment by HiImCris** [comment]
It seems tool-pioasm-rp2040-earlephilhower is a repository that no longer exists. I don't know if this repository here is its replacement, but once I removed the line, the code built. Once all the parts are delivered trough mail, I'll be able to test the code in real conditions, until then, issue's closed.

**Comment by earlephilhower** [comment]
The P.IO team asked me not to publish any RP2040 cores or tools to their online service, so this is expected.  See the docs for how to have P.IO download toolchains and cores directly from my GH repo release areas.
