### ISSUE TITLE
Feature Request: dmadison ArduinoXInput support

### ISSUE THREAD

**Issue by Wolverine-14** [earlephilhower/arduino-pico#2110]
I would like to see support for [this](https://github.com/dmadison/ArduinoXInput) XInput library as it adds more features to making a joystick such as support for haptic feedback. It's explained [here](https://github.com/dmadison/ArduinoXInput/blob/master/extras/XInputUSB_API.md) what should be needed to add support

**Comment by earlephilhower** [comment]
I think you might have better luck asking the library author.  They seem to have chosen a really "heavy hammer" way of implementing things, requiring copied(not forked so no easy `git` merges), customized and unsupported Arduino cores.

There probably was a good reason for this when they started, but today with the Adafruit TinyUSB library it should be relatively simple to implement the same thing, without customized Arduino cores, and with support for 100s of different boards on 10s of different SOCs, automatically for free.

I imagine it's a pretty trivial HID device with maybe an additional custom channel for the haptics, both of which are simple to implement w/TinyUSB.
