### ISSUE TITLE
Version 3.8.0 Compiler Error

### ISSUE THREAD

**Issue by CraftoHohenvels** [earlephilhower/arduino-pico#2120]
Affected version: 3.8.0
Last known working version: unknown
Python version: 3.12.3
IDE Version: 2.3.2
OS: Windows 10 22H2

Error
```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000ac0c (most recent call first):

exit status 0xc0000409

Compilation error: exit status 0xc0000409
```

I already used version 3.7.2 on Linux and it seemed to be fine, but even that version doesn't compile on Windows

**Comment by earlephilhower** [comment]
The IDE did not install the version correctly, leaving files missing.  Nothing the core itself can do anything about. 

Uninstall the board package, exit the IDE, restart it, and install the core again.  There are other threads here you can look at with a search on "encodings" for more information.
