### ISSUE TITLE
Feature Request: Integration of class MacAddress from arduino-esp32?

### ISSUE THREAD

**Issue by matthias-bs** [earlephilhower/arduino-pico#2127]
Hi,

how about integrating https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/MacAddress.cpp?
As far as I can see, this should work right out of the box.

Best regards,
Matthias

**Comment by earlephilhower** [comment]
Why not try your hand at a PR for it?  Looks like a pretty trivial porting effort, if any, would be needed.  It might be a good idea to update the `WiFi` and LWIP `Ethernet` classes to include support for this object, too.  OTW I'm not seeing how it'd be used...
