### ISSUE TITLE
Joystick library - please update submodule

### ISSUE THREAD

**Issue by benjaminaigner** [earlephilhower/arduino-pico#2136]
Dear @earlephilhower ,

I've fixed some problems with the Joystick hat in my upstream library:

https://github.com/benjaminaigner/Joystick

arduino-pico core is now including your fork in gitmodules, so I had to open the issue here.

I've fixed / added:
* wrong mapping of hat angle to position (corner cases)
* added a new function to use an enum for hat position

I ran astyle with your configuration from here, hope that is what you expect.

thanks!

**Comment by earlephilhower** [comment]
Thanks for the notice.  FYI, the reason we have a different version is that the HID portion was extracted out.  Your Joystick code here can talk over USB, Classic Bluetooth, and BLE with no core changes.
