### ISSUE TITLE
Feature Request: Setting usb_hid_poll_interval in setup

### ISSUE THREAD

**Issue by JacTech** [earlephilhower/arduino-pico#2215]
I don't know if its possible but it would be cool, to be able to set the polling rate in setup. this way a setting could be loaded from EEPOM

**Comment by earlephilhower** [comment]
Already there, see https://github.com/earlephilhower/arduino-pico/pull/1771

**Comment by JacTech** [comment]
but this only works when i define it before void setup() tho. 
It would be cool it it could be defined in the setup

**Comment by earlephilhower** [comment]
Sorry, but that's not possible with the way things run now.  By the time `setup` is called, USB is already running and can't be changed.

**Comment by JacTech** [comment]
i was kind of expecting that. thanks anyways :)
