### ISSUE TITLE
Adafruit SH1106 library not compiling

### ISSUE THREAD

**Issue by dimonDDL** [earlephilhower/arduino-pico#225]
Today I tried compiling the example in the Adafruit SH1106 library, Arduino IDE 1.8.15 for the Raspberry pi pico with standard parameters, however I get the following error on compiling:
````
/home/dima/Arduino/libraries/Adafruit_SH1106-master/Adafruit_SH1106.cpp:31:11: fatal error: util/delay.h: No such file or directory
   31 |  #include <util/delay.h>
      |           ^~~~~~~~~~~~~~
compilation terminated.
````
The full compilation output is [here](https://pastebin.com/nc1zqJuN).

**Comment by earlephilhower** [comment]
That's not an official Adafruit library as far as I can tell, and it also has a bug in its ifdefs.

I'd suggest doing something like
````
#ifndef __SAM3X8E__ 
````
to
````
#if !defined( __SAM3X8E__) && !defined(ARDUINO_ARCH_RP2040)
````
but can't guarantee it doesn't have other problems.  You might want to open a bug report/PR in its repo.

Good luck!
