### ISSUE TITLE
Feature Request: OTA Sketch Upload

### ISSUE THREAD

**Issue by djaus2** [earlephilhower/arduino-pico#2258]
Taking this as wishlist, would it be possible to be able to do Over- The-Air updates of a Sketch? 
Like [picowota](https://github.com/usedbytes/picowota)
Assuming an initial flash required by USB then updates OTA just of the Sketch.

**Comment by djaus2** [comment]
I see there are some closed issues on OTA.
Looking into these to see if what I want is doable already with RPi Pico W

**Comment by Frogieder** [comment]
You may be asking for something that's already been implemented here, be sure to check out [https://arduino-pico.readthedocs.io/en/latest/ota.html](https://arduino-pico.readthedocs.io/en/latest/ota.html).

**Comment by earlephilhower** [comment]
OTA is supported on any Pico.  See the docs or examples(PicoOTA, ArduinoOTA, and the HTTPUpdate libraries in particular).

**Comment by djaus2** [comment]
Thanks

David Jones (MVP)
________________________________

**Comment by djaus2** [comment]
OK got that to work, the BasicOTA example. :)
