### ISSUE TITLE
Provision a new RPi Pico W without Arduino IDE?

### ISSUE THREAD

**Issue by djaus2** [earlephilhower/arduino-pico#2301]
Is this poossible, in a simple manner?
Looking at detailing simple upload of an existing built sketch using a batch file.
Got that working using USB , and OTA.
Would be "nice" if could provision a new RPi Pico W with the BSP without the user being required to install the Aruino IIDE.

**Comment by earlephilhower** [comment]
See #1108 .

**Comment by djaus2** [comment]
That's was simple.Thx

David Jones (MVP)
________________________________
