### ISSUE TITLE
https://arduino-pico.readthedocs.io/en/latest/ doesn't contain the v4 guide

### ISSUE THREAD

**Issue by YohannesGetu** [earlephilhower/arduino-pico#2360]
https://arduino-pico.readthedocs.io/en/latest/ doesn't contain the v4 guide

**Comment by earlephilhower** [comment]
Thanks for the notice.  RTD looks to have been broken for a while.  It's updated now.

**Comment by YohannesGetu** [comment]
> Thanks for the notice. RTD looks to have been broken for a while. It's updated now.

it's updated now, thank you for your swift response.
