### ISSUE TITLE
Typo for `build.libpicow` on platform.txt?

### ISSUE THREAD

**Issue by rei-vilo** [earlephilhower/arduino-pico#2365]
Shouldn't be `libipv4.a` to match the values listed on boards.txt?

https://github.com/earlephilhower/arduino-pico/blob/b2428763d67e2568eb62cee8a8e265411560274f/platform.txt#L104

Thank you and best regards,

**Comment by earlephilhower** [comment]
Yes, it should be.  It's not actually used so won't cause any issues, but it is fixed in #2366
