### ISSUE TITLE
Error for 4.0.1 on OSX

### ISSUE THREAD

**Issue by dpharris** [earlephilhower/arduino-pico#2375]
Hi --

The Arduino library manager offered to upgrade to 4.0.1, but fails to retrieve the release.  

Failed to install platform: 'Raspberry Pi Pico/RP2040:4.0.1'. 2 UNKNOWN: Get "https://github.com/earlephilhower/arduino-pico/releases/download/4.0.1/rp2040-4.0.1.zip": EOF

Thanks

**Comment by earlephilhower** [comment]
That looks like a network issue.  Make sure you can download that link and retry the installation.  Possibly GH or someting in your network was having a hiccup at the time.

**Comment by dpharris** [comment]
Yes, you are right, I just tried it again and it installed fine.  Thank you
(for you great libs and) for your help.

David
