### ISSUE TITLE
flash_range_erase hanging when overwriting XIP

### ISSUE THREAD

**Issue by LordOfDeadbush** [earlephilhower/arduino-pico#2385]
Hello,
I seem to be running into an issue where I can run flash_range_erase and flash_range_program in my code when offset from the actual program instructions, but when I try to overwrite near where the program binary is stored the function will periodically hang on something (it's always erase). 
I am using a W5500-EVB-Pico with the Arduino-Pico core on Arduino IDE.

Here is the function I am using (core1 is already paused at this point) if it helps:

```
void write_flash_sector(uint8_t * buf, intptr_t offset) {
  noInterrupts();
  gpio_put(LED_PIN, 1);

  flash_range_erase(offset, FLASH_SECTOR_SIZE);
  gpio_put(LED_PIN, 0);

  flash_range_program(offset, buf, FLASH_SECTOR_SIZE);

  interrupts();
}
```

I have verified that the offsets my code is setting is correct. Are there any other possible reasons why this would be hanging? Should I be doing any other precautionary measures prior to writing to flash?

**Comment by earlephilhower** [comment]
This is illegal.  The flash chip is not able to read your core0 code when you perform that erase.  And core1 needs a special pause, not just a busy while(1) loop.  Look at EEPROM for a quick example, although you really shouldn't be writing naked flash like that with this core.
