### ISSUE TITLE
4.0.1 breaks core1 at certain clock frequencies

### ISSUE THREAD

**Issue by LucasLHenry** [earlephilhower/arduino-pico#2391]
After updating to 4.0.1, started having issues where core1 would crash after a couple seconds. This was unpredictable however, and didn't always happen. Changing the clock frequency from 133MHz helped though, at 50MHz and above 200MHz the code was functional. Core1 is running an interrupt-based PWM waveform generator. Rolling back to 3.9.5 solved this issue. I'm not sure exactly where this problem is coming from, the code that I'm working can be found in [here](https://github.com/LucasLHenry/spelltwister).

**Comment by earlephilhower** [comment]
No changes to the core for RP2040 were done to 4.0.1 other than the Pico SDK being updated to the latest 2.0.0 version.  I suggest asking at the RPI forums if anyone else has seen the same thing, but you'll need to reduce it to a small simple MCVE to be reproduced by others.  FWIW, running > 133 is always overclocked and not in spec for the chip.
