### ISSUE TITLE
Is it possible to set SPI clock speed for SD card usage?

### ISSUE THREAD

**Issue by omikron88** [earlephilhower/arduino-pico#24]
Hello,
It works fine in 1.8.* IDE, but in 2.0.beta the board is not detected in BOOTSEL mode.

Is it possible to set SPI clock speed for SD card usage?

**Comment by earlephilhower** [comment]
> It works fine in 1.8.* IDE, but in 2.0.beta the board is not detected in BOOTSEL mode.

See #20 near the end, I haven't updated the readme yet but a user got things running and debugged the root cause on their system.
 
> Is it possible to set SPI clock speed for SD card usage?

SPISettings has a clock parameter.  Changing it here should be no different than on other Arduino boards https://www.arduino.cc/en/Reference/SPISettings
