### ISSUE TITLE
Problem with RP2040 floating point with version 4.01?

### ISSUE THREAD

**Issue by dquadros** [earlephilhower/arduino-pico#2410]
This is so weird that it must be a problem in my setup... but it is happening in my desktop and my notebook. The following sketch should turn on the Pico LED after a single floating point multiplication is done:

```
double X; // declared here so the multiplication is not removed by optimization

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, LOW);

  double T = millis();
  X = -1.3 * T;

  digitalWrite(LED_BUILTIN, HIGH);
}

void loop() {
  delay(100);
}

```

It works fine with version 3.95 but fails with version 4.01 (the LED stays unlit). 

Tested with Arduino IDE 2.3.2 under Windows 10, with a Raspberry Pi Pico and default configurations.

In case someone is curious, this problem showed up when I tried to run a Whetstone benchmark with the new version. I isolated the problem to a single multiplication.

**Comment by earlephilhower** [comment]
You are quite correct.  This now fails on the RP2040 (RP2350 is OK).  Logs show a `double` ROM shim issue:
````
#0  __breakpoint () at /home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/rp2040/pico_platform/include/pico/platform.h:126
#1  _exit (status=status@entry=1) at /home/earle/Arduino/hardware/pico/rp2040/cores/rp2040/sdkoverride/newlib_interface.c:45
#2  0x100044de in panic (fmt=0x1000f0a8 "missing double function") at /home/earle/Arduino/hardware/pico/rp2040/pico-sdk/src/rp2_common/pico_platform_panic/panic.c:82
#3  0x10005cb0 in missing_double_func_shim () at /home/earle/Arduino/hardware/pico/rp2040/pico-sdk/src/rp2_common/pico_double/double_init_rom_rp2040.c:17
#4  0x1000322e in setup () at /home/earle/Arduino/sketch_sep03d/sketch_sep03d.ino:8
#5  0x1000354a in main () at /home/earle/Arduino/hardware/pico/rp2040/cores/rp2040/main.cpp:148
````

I'll do some `git` bisection to see when this happened:  if it was at the 2.0.0 SDK merge or the RP2350 changes...
