### ISSUE TITLE
Arduino 1.8.19 SD Card Error

### ISSUE THREAD

**Issue by wro52** [earlephilhower/arduino-pico#2435]
When compiling a program including SDcard.h of SD Version 1.24 or 1.30 the actual version of the pico  4.01 generates:
ambiguous overload for 'operator+' (operand types are 'arduino::String' and 'uint64_t' {aka 'long long unsigned int'}).

Reversing back to Version 3.95 everything compiles without problems (SD Version 1.24 or 1.30).

System is Arduino 1.8.19, Linux Mint recent Version, 64 Bit, 32GB, Intel core I5 (Quad Core) HP Elitebook.

Version 4.0 has the same Problem. The full error report for version 4.0 is:

In file included from /home/wro/Arduino/portable/sketchbook/geek-ir-1/geek-ir/geek-ir.ino:46:
/Arduino/portable/sketchbook/geek-ir-1/geek-ir/sdcard.h: In function 'void SD_info()':
sdcard.h:135:19: error: ambiguous overload for 'operator+' (operand types are 'arduino::String' and 'uint64_t' {aka 'long long unsigned int'})
  135 |   SDCARD = SDCARD + (fs_info.totalBytes);
      |            ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~
      |            |                 |
      |            arduino::String   uint64_t {aka long long unsigned int}
In file included from /Arduino/portable/packages/rp2040/hardware/rp2040/4.0.0/cores/rp2040/api/String.h:2,
                 from /Arduino/portable/packages/rp2040/hardware/rp2040/4.0.0/cores/rp2040/api/../../../ArduinoCore-API/api/IPAddress.h:23,
                 from /Arduino/portable/packages/rp2040/hardware/rp2040/4.0.0/cores/rp2040/api/../../../ArduinoCore-API/api/ArduinoAPI.h:30,
                 from /Arduino/portable/packages/rp2040/hardware/rp2040/4.0.0/cores/rp2040/api/ArduinoAPI.h:2,
                 from /Arduino/portable/packages/rp2040/hardware/rp2040/4.0.0/cores/rp2040/Arduino.h:28,

---------------------------------------------------------------------------------------------------------------------------

For Version 4.01 the error report is:

In file included from /Arduino/portable/sketchbook/geek-ir-1/geek-ir/geek-ir.ino:46:
/Arduino/portable/sketchbook/geek-ir-1/geek-ir/sdcard.h: In function 'void SD_info()':
sdcard.h:135:19: error: ambiguous overload for 'operator+' (operand types are 'arduino::String' and 'uint64_t' {aka 'long long unsigned int'})
  135 |   SDCARD = SDCARD + (fs_info.totalBytes);
      |            ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~
      |            |                 |
      |            arduino::String   uint64_t {aka long long unsigned int}
In file included from /Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/String.h:2,
                 from /Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/IPAddress.h:23,
                 from /Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/ArduinoAPI.h:30,
                 from /Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/ArduinoAPI.h:2,
                 from /Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/Arduino.h:28,
                 from /Arduino/portable/sketchbook/geek-ir-1/geek-ir/geek-ir.ino:28:
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:149:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, double)'
  149 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, double num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:148:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, float)'
  148 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, float num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:147:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, long unsigned int)'
  147 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, unsigned long num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:146:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, long int)'
  146 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, long num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:145:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, unsigned int)'
  145 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, unsigned int num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:144:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, int)'
  144 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, int num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:143:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, unsigned char)'
  143 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, unsigned char num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:142:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, char)'
  142 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, char c);
      |                                  ^~~~~~~~
sdcard.h:138:19: error: ambiguous overload for 'operator+' (operand types are 'arduino::String' and 'uint64_t' {aka 'long long unsigned int'})
  138 |   SDCARD = SDCARD + (fs_info.usedBytes);
      |            ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~
      |            |                 |
      |            arduino::String   uint64_t {aka long long unsigned int}
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:149:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, double)'
  149 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, double num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:148:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, float)'
  148 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, float num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:147:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, long unsigned int)'
  147 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, unsigned long num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:146:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, long int)'
  146 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, long num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:145:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, unsigned int)'
  145 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, unsigned int num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:144:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, int)'
  144 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, int num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:143:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, unsigned char)'
  143 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, unsigned char num);
      |                                  ^~~~~~~~
/Arduino/portable/packages/rp2040/hardware/rp2040/4.0.1/cores/rp2040/api/../../../ArduinoCore-API/api/String.h:142:34: note: candidate: 'arduino::StringSumHelper& arduino::operator+(const StringSumHelper&, char)'
  142 |         friend StringSumHelper & operator + (const StringSumHelper &lhs, char c);

-------------------------------------------------------------------------------------------------------------------------   
Hope it will give some clues. As mentioned the Version 3.95 is compiling without any problems.

Regards and my deep respect for your tremendous work.

**Comment by earlephilhower** [comment]
Looks like whatever code is trying to do string operations on a card size and failing.  `Arduino::String`  doesn't know what a uint64_t is.  Since the size of SD cards has been > 4GB for over a decade now `fs_info.totalBytes` is [now 64-bit, not 32b](https://github.com/earlephilhower/arduino-pico/pull/2335) (which had that 4GB limit).  This was the first part of the release notes.

You can cast the element to a `(uint32_t)` and end up with incorrect output on anything >4GB in size, or replace the `String + String` with a `sprintf`.
