### ISSUE TITLE
Arduino COM port problem with PICO and PICO2

### ISSUE THREAD

**Issue by MartinHugh** [earlephilhower/arduino-pico#2476]
I have just installed IDE 2.3.2 on Windows 11
I also followed these instructions for the PICO boards
https://www.upesy.com/blogs/tutorials/install-raspberry-pi-pico-on-arduino-ide-software#

When I connect a PICO or PICO 2 to a USB port, no new COM port is allocated.
If I hold the button down before I plug into the USB I get an "Autoplay RP2350" device appearing as a disk drive.

In the IDE status bar it now says 
"Raspberry Pi PICO 2 on UF2 board"

Should this say on "COM x" ?

If I try to compile and upload a sketch at this point it ends with
Flashing G: (RP2350)
Wrote 123392 bytes to G:/NEW.UF2

However, the IDE then shows and error
"No monitor available for the port protocol uf2conv. Could not connect to UF2_Board uf2conv port"

Any idea what is going on?

Thanks

**Comment by earlephilhower** [comment]
Select the newly generated serial port in the menus after upload.   UF2 is the fake virtual disk connection, not a serial port.
