### ISSUE TITLE
FreeRTOS SMP Support and wrappers

### ISSUE THREAD

**Issue by DatanoiseTV** [earlephilhower/arduino-pico#2484]
While porting some ESP32 Audio Code, I was wondering if arduino-pico is using an SMP version of the FreeRTOS kernel.

Also, Espressif made some own non-standard wrappers for various functions, such as:
```
portMUX_TYPE timer1Mux = portMUX_INITIALIZER_UNLOCKED; 

xTaskCreatePinnedToCore( task1, "Task1", 8000, NULL, (1 | portPRIVILEGE_BIT), &Task1, 0 );
portENTER_CRITICAL_ISR(&timer1Mux);
portEXIT_CRITICAL_ISR(&timer1Mux);
```

I think it would be practical if these were implemented as well, so code could be ported easier. I have already started writing some wrappers for other things like PSRAM allocation etc.

**Comment by DatanoiseTV** [comment]
After some digging, I found out that indeed both cores are supported already.

Also found how to set core affinity, so I guess I will just write some wrappers around it.
 vTaskCoreAffinitySet(loop2Handle, CORE_0);

**Comment by earlephilhower** [comment]
Yeah, we were SMP before it was cool, man!  :laughing:

The Espressif guys were there even earlier, probably one of the first folks doing real SMP work w/FreeRTOS.  They probably needed to write lots of these little helpers like your header to get things up to speed back in the day.

I'm not really keen on tracking their changes.  If they're just syntactic sugar there's a simple compatible way of doing the call which can be used by everyone.  If they're modifying the upstream FreeRTOS functionality/guts then it's on them to propose those changes upstream or maintain their own branch very separate from RPI's/ours.
