### ISSUE TITLE
W55RP20 support?

### ISSUE THREAD

**Issue by ITstreet1** [earlephilhower/arduino-pico#2492]
Hello,
Do you plan to add support for the W55RP20, and the W55RP20-EVB-PICO dev kit?
https://www.wiznet.hk/en/home/133-w55rp20-evb-pico.html

**Comment by earlephilhower** [comment]
That looks like they have a 2nd model # for @5500-EVB , already included.  If not, please feel free to make a new chip variant.  Thx!

**Comment by ITstreet1** [comment]
Hello,
Just get mine EVB, and I have noticed some issues. The regular GPIO works. Not tested everything, though. However, the WiFi Client W55RP20 does not work. It says: "No wired Ethernet hardware detected. Check pinouts, wiring."

Tried an ethernet example, and get the same. CS is 17, I believe.
