### ISSUE TITLE
SPI.h can't be used in `extern "C"` context

### ISSUE THREAD

**Issue by grantfanian** [earlephilhower/arduino-pico#2499]
I'm working on a PlatformIO project involving [RF24Ethernet](https://github.com/nRF24/RF24Ethernet/) library.
Config is pretty simple, just using git versions of arduino-pico and your toolchain. Errors are independent of project's code.
```ini
[env:_dev_allpaths]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#2a8c40e
board = rpipico
framework = arduino
; to get Mbed-based core:
;board = pico
;platform_packages = platformio/toolchain-gccarmnoneeabi@1.120301.0

lib_deps = SPI
    nrf24/RF24Ethernet@^1.6.16
```

When switching from the default Mbed-based Arduino core, RF24Ethernet build started failing:
```
arm-none-eabi-g++ -o .pio/build/_dev_allpaths/lib1c2/RF24Ethernet/RF24Ethernet.cpp.o -c -fno-exceptions -fno-rtti -std=gnu++17 -Os -Werror=return-type -Wno-psabi -ffunction-sections -fdata-sections -march=armv6-m -mcpu=cortex-m0plus -mthumb -iprefix/home/fun/.platformio/packages/framework-arduinopico @/home/fun/.platformio/packages/framework-arduinopico/lib/rp2040/platform_inc.txt @/home/fun/.platformio/packages/framework-arduinopico/lib/core_inc.txt -DPLATFORMIO=60116 -DARDUINO_RASPBERRY_PI_PICO -DARDUINO_ARCH_RP2040 -DUSBD_MAX_POWER_MA=250 -DARDUINO=10810 -DARDUINO_ARCH_RP2040 -DF_CPU=133000000L -DBOARD_NAME=\"rpipico\" -DARM_MATH_CM0_FAMILY -DARM_MATH_CM0_PLUS -DTARGET_RP2040 -DPICO_RP2040=1 -DPICO_FLASH_SIZE_BYTES=2097152 -DCFG_TUSB_MCU=OPT_MCU_RP2040 -DUSB_VID=0x2E8A -DUSB_PID=0x000A "-DUSB_MANUFACTURER=\"Raspberry Pi\"" -DUSB_PRODUCT=\"Pico\" -DSERIALUSB_PID=0x000A -DPICO_CYW43_ARCH_THREADSAFE_BACKGROUND=1 -DCYW43_LWIP=1 -DLWIP_IPV4=1 -DLWIP_IGMP=1 -DLWIP_CHECKSUM_CTRL_PER_NETIF=1 -DLWIP_IPV6=0 -DARDUINO_VARIANT=\"rpipico\" -I.pio/libdeps/_dev_allpaths/RF24Ethernet -I.pio/libdeps/_dev_allpaths/RF24Ethernet/utility -I.pio/libdeps/_dev_allpaths/RF24Mesh -I.pio/libdeps/_dev_allpaths/RF24Network -I.pio/libdeps/_dev_allpaths/RF24 -I.pio/libdeps/_dev_allpaths/RF24/utility -I/home/fun/.platformio/packages/framework-arduinopico/libraries/SPI/src -I/home/fun/.platformio/packages/framework-arduinopico/cores/rp2040 -I/home/fun/.platformio/packages/framework-arduinopico/cores/rp2040/api/deprecated -I/home/fun/.platformio/packages/framework-arduinopico/cores/rp2040/api/deprecated-avr-comp -I/home/fun/.platformio/packages/framework-arduinopico/include -I/home/fun/.platformio/packages/framework-arduinopico/variants/rpipico .pio/libdeps/_dev_allpaths/RF24Ethernet/RF24Ethernet.cpp
<...>
In file included from /home/fun/.platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/14.2.0/bits/stl_tree.h:69,
                 from /home/fun/.platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/14.2.0/map:62,
                 from /home/fun/.platformio/packages/framework-arduinopico/libraries/SPI/src/SPI.h:26,
                 from .pio/libdeps/_dev_allpaths/RF24/RF24_config.h:143,
                 from .pio/libdeps/_dev_allpaths/RF24Network/RF24Network_config.h:123,
                 from .pio/libdeps/_dev_allpaths/RF24Ethernet/uip-conf.h:49,
                 from .pio/libdeps/_dev_allpaths/RF24Ethernet/RF24Ethernet.h:34,
                 from .pio/libdeps/_dev_allpaths/RF24Ethernet/RF24Ethernet.cpp:21:
/home/fun/.platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/14.2.0/ext/aligned_buffer.h:46:3: error: template with C linkage
   46 |   template<typename _Tp>
      |   ^~~~~~~~
.pio/libdeps/_dev_allpaths/RF24Ethernet/RF24Ethernet.h:33:1: note: 'extern "C"' linkage started here
   33 | extern "C" {
      | ^~~~~~~~~~
/home/fun/.platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/14.2.0/ext/aligned_buffer.h:91:3: error: template with C linkage
   91 |   template<typename _Tp>
      |   ^~~~~~~~
.pio/libdeps/_dev_allpaths/RF24Ethernet/RF24Ethernet.h:33:1: note: 'extern "C"' linkage started here
   33 | extern "C" {
      | ^~~~~~~~~~
<repeated 100s of times per RF24 source file>
```

The error message tracks down to [this line](https://github.com/nRF24/RF24/blob/63cadc42bfab80cc8a77267f5d16e39c550bcf9e/RF24_config.h#L143), where SPI.h gets included. 
In RF24Ethernet this file is eventually included in an `extern "C"` context that starts [here](https://github.com/nRF24/RF24Ethernet/blob/f5980c09e716b33bb2078535f28d31704317a112/RF24Ethernet.h#L34).

Arduino-Pico's implementation of SPI.h includes `<map>` that has templates, while the default core had no templates and thus was `extern "C"`-safe.

It's a pretty popular project and I couldn't find any similar bugs, so the assumption that SPI.h can be included in an `extern "C"` context likely works not only for Pico's Mbed-based Arduino core, but on AVR and STM32, which are pretty popular.

I see two solutions:
- `std::map` use in SPI.h gets replaced with something else in Arduino-Pico for compatibility
- The include gets moved out of the block in RF24Ethernet (doesn't seem trivial at first glance)

The first solution would be better, unless this assumption is never made outside of RF24Ethernet.

**Comment by earlephilhower** [comment]
I am not sure what exactly is being accomplished by wrapping a C++-only header in `extern "C"` other than possibly breaking name mangling somewhere along the line.

The only thing SPI.h does is define a `class` interface and two instances.  Neither of which is legal (or useful) in plain `C` code.

In general it's wrong and unsafe to wrap a header in something like this.  For example, if the header defined a function `void doit(int);` then w/C++ name mangling the C++ source file would implement a mangled function called `_Z4doiti`  while the files that wrapped the `#include` would try to link to unmangled `doit`.

The only case I know of that's safe is when you're wrapping an old C-only header for very old libraries, to ensure the linkage is correct.

So with that, I'm not seeing anything wrong or to be changed in the core, sorry.
