### ISSUE TITLE
4.1.0 Python Path error

### ISSUE THREAD

**Issue by metehoca** [earlephilhower/arduino-pico#2510]
Here's the error message when trying to build Blink sketch on Pico 2 on Arm:

exec: "{runtime.tools.pqt-python3.path}/python3": executable file not found in %PATH%

Compilation error: exec: "{runtime.tools.pqt-python3.path}/python3": executable file not found in %PATH%

Riscv one generates this one:

exec: "C:\\Users\\mete\\AppData\\Local\\Arduino15\\packages\\rp2040\\tools\\pqt-gcc\\4.0.1-8ec9d6f/bin/riscv32-unknown-elf-g++": executable file not found in %PATH%

Compilation error: exec: "C:\\Users\\mete\\AppData\\Local\\Arduino15\\packages\\rp2040\\tools\\pqt-gcc\\4.0.1-8ec9d6f/bin/riscv32-unknown-elf-g++": executable file not found in %PATH%

Tried uninstalling and reinstalling package with admin rights, but no change.

**Comment by earlephilhower** [comment]
Thanks for the report.  There's a post-processing of the `git` repo files to make the `platform.txt` run from a plain IDE install and it looks like that got borked for the R5 binaries.

You can use the `git` repo version instead ([docs here](https://github.com/earlephilhower/arduino-pico/blob/master/docs/install.rst#installing-via-git)) while this gets sorted...another minor release will be in the works!
