### ISSUE TITLE
Best way to test for CPU Architecture selection?

### ISSUE THREAD

**Issue by technoblogy** [earlephilhower/arduino-pico#2522]
Thank you for the new **CPU Architecture** option allowing you to select **ARM** or **RISC-V** in version 4.1.0 of the core.

What is the recommended way to test for the option that's been selected, both at compile time (such as with `#if defined`) and at run time? I checked the documentation but couldn't find anything relevant.

Thanks, David

**Comment by earlephilhower** [comment]
I use the compiler defined `__riscv`.  There is an ARM equivalent, but since it's one or the other you can just use
````
#ifdef __riscv
....r5 specific...
#else
...arm specific...
#endif
````

At run time, just use the defines to set some constant to true or false...

**Comment by technoblogy** [comment]
Thank you - perfect!
David
