### ISSUE TITLE
Documentation Reference to SerialBT

### ISSUE THREAD

**Issue by otacon6530** [earlephilhower/arduino-pico#2571]
I am trying to have two Pico  Ws communicate via bluetooth. One sender, one receiver. I thought SerialBT was the answer per the [(documentation),](https://arduino-pico.readthedocs.io/en/latest/bluetooth.html) but can't find a library by that name. Could you verify if the documentation is meaning [bluetooth serial](https://docs.arduino.cc/libraries/bluetoothserial/) or let me know what is being referenced?

**Comment by earlephilhower** [comment]
`SerialBT` is an `arduino-pico` library.  See the [library example](https://github.com/earlephilhower/arduino-pico/tree/master/libraries/SerialBT).
