### ISSUE TITLE
Upload of package_rp2040_index.json hangs

### ISSUE THREAD

**Issue by djaus2** [earlephilhower/arduino-pico#2572]
When I open the Arduino IDE I continually get  the **Downloading index: package_rp2040_index.json** upload message but it jumps to about 2/3rd done and doesn't progress. At least for a long time.

**Comment by earlephilhower** [comment]
The JSON file is served from GitHub, so there's not anything we can do here.  You may have a network issue, but that's something you might be able to workaround by using `git` and not the Arduino IDE to install the core.  See the [docs](https://github.com/earlephilhower/arduino-pico?tab=readme-ov-file#installing-via-git) for more info on installing via git.

**Comment by djaus2** [comment]
It happens when I start a build.

**Comment by djaus2** [comment]
Also I can directly download https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json vias browser
so network is working.

**Comment by djaus2** [comment]
Did the Git install, no change.
>NB: The BSP was insatlled previously, guess it is trying to just do an update.

**Comment by djaus2** [comment]
![image](https://github.com/user-attachments/assets/f99d4331-4a82-4540-99a9-fb3777fe7457)

**Comment by djaus2** [comment]
Problem seems to have gone way, for now. Not sure why.

**Comment by djaus2** [comment]
Still happens when I  reload the IDE.
![image](https://github.com/user-attachments/assets/eaca6b97-eea8-4689-8a6d-29cd63546a68)
Backgraph doesn't move.
Note no or little netwrk load (o or 0.1)
Workaround is 
- to open a new Sketch from the IDE.
- Close the current one then reopen it.
?????????????????
