### ISSUE TITLE
tinyUSB example `Video/VideoCapture` not working

### ISSUE THREAD

**Issue by umeiko** [earlephilhower/arduino-pico#2621]
As titled. The Windows device manager showed a camera as named "pico", but with error code 10, start up device with problem.

I also tried plug into an andriod phone, also shown a camera device but can't open

**Comment by maxgerhardt** [comment]
FYI tracked in https://github.com/adafruit/Adafruit_TinyUSB_Arduino/issues/469 now; Failure is reproducible on Windows, but works on Linux.

**Comment by umeiko** [comment]
I even tried tinyUSB example with raw pico-sdk, works good, but when i `#define CFG_EXAMPLE_VIDEO_READONLY` to test mjpeg, it opend with black screen.
