### ISSUE TITLE
Pimoroni Pico Plus 2W..

### ISSUE THREAD

**Issue by richm-dev** [earlephilhower/arduino-pico#2631]
Hi,
the Pimoroni Pico Plus 2W doesn't appear in the board list in Arduino when V4.2/4.21 is installed (only the non-wifi Plus 2 does), but appears in the supported board list here on Github.
Thanks,
Rich.

**Comment by earlephilhower** [comment]
Yes, that's correct.  There will be a new release sometime soon taken from `git master` but I am waiting for the 2.1.0 SDK to be released first.  Until then see https://arduino-pico.readthedocs.io/en/latest/install.html#installing-via-git
