### ISSUE TITLE
Pimoroni PicoPlus 2W does not show up as supported board

### ISSUE THREAD

**Issue by hbitter** [earlephilhower/arduino-pico#2635]
Environment:

- Linux Mint 22 Wilma
- Arduino IDE 2.3.3
- Arduino-Pico 4.2.1

If I try to select the Pimoroni PicoPlus 2W it does not show up.

![Pimoroni Boards](https://github.com/user-attachments/assets/d975f424-e640-46fe-9d53-1390d2936afc)

Pimoroni PicoPlus 2 does show up, but not the Wifi version.
PicoPlus 2W is on the list of supported boards for version 4.2.1
Any idea why?

**Comment by earlephilhower** [comment]
https://github.com/earlephilhower/arduino-pico/issues/2631#issuecomment-2495637928
