### ISSUE TITLE
cyw43_get_pin_wl symbol is missing in Core 4.3.0

### ISSUE THREAD

**Issue by lyusupov** [earlephilhower/arduino-pico#2637]
### Discussed in https://github.com/earlephilhower/arduino-pico/discussions/2636

<div type='discussions-op-text'>

<sup>Originally posted by **lyusupov** November 25, 2024</sup>
### I've got a regression

build of a sketch was fine all the way up to Core version 4.2.1

but it is now broken with 4.3.0

```
/home/codespace/.arduino15/packages/rp2040/tools/pqt-gcc/4.0.1-8ec9d6f/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /tmp/arduino/sketch/src/platform/RP2XXX.cpp.o: in function `_ZL11RP2xxx_finii':
RP2XXX.cpp:517:(.text._ZL11RP2xxx_finii+0x20): undefined reference to `cyw43_get_pin_wl'
collect2: error: ld returned 1 exit status
```

Looks like the `cyw43_get_pin_wl` symbol is a part of SDK -

https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c#L598

and it needs CYW43_PIN_WL_DYNAMIC flag to be enabled at the SDK build time. 

</div>

<br>

### MCVE

```
void setup()
{
#if defined(ARDUINO_RASPBERRY_PI_PICO_W)
  pinMode(CYW43_PIN_WL_REG_ON, INPUT_PULLDOWN);
#endif /* ARDUINO_RASPBERRY_PI_PICO_W */
}

void loop()
{

}
```

### To reproduce

```
$ arduino-cli core install rp2040:rp2040@4.3.0
$ export BOARD=rp2040:rp2040:rpipicow
$ arduino-cli  compile -v --build-path=/tmp/arduino -b "$BOARD"  .
```

**Comment by earlephilhower** [comment]
Good catch.  This is an RP2040-only issue which is why it wasn't seen on the SparkFun Think Plus RP2350 or Pico 2W.  Looks like one more library rebuild and release.  I want to slide that into CI as well so if it gets broken again it'll show before it goes out. :(

**Comment by earlephilhower** [comment]
@lyusupov can you try the PR and report back?  I'd like to get a hotfix out in a couple days once we see if there's anything else to do.

**Comment by lyusupov** [comment]
> can you try the PR and report back? 

I've taken `libipv4.a` from the PR and updated this library only.

```
$ arm-none-eabi-nm -n libipv4.a | grep cyw43_get_pin_wl
         U cyw43_get_pin_wl
00000000 T cyw43_get_pin_wl
         U cyw43_get_pin_wl
```

Build of the MCVE and my sketch goes fine afterwards.

Thank you so much!
