### ISSUE TITLE
Serial1 is not working while SerialPIO (SoftwareSerial) is

### ISSUE THREAD

**Issue by racsnet** [earlephilhower/arduino-pico#2642]
Hello there. I have a Project where I need Serial communication.
I Use a Waveshare RP2040-zero and the Hardware Uart does not work. I simply get no Output, if I connect a FTDI.

not working Code:
```
#ifdef USE_TINYUSB
#include <Adafruit_TinyUSB.h>
#endif

void setup() {
  Serial1.setRX(6);
  Serial1.setTX(7);
  Serial1.begin(9600);
}

void loop() {
  Serial1.println("Hello World");
  delay(1000);
}
```
working Code:
```
#ifdef USE_TINYUSB
#include <Adafruit_TinyUSB.h>
#endif

SerialPIO SoftS (7, 6, 64);

void setup() {
  SoftS.begin(9600);
}

void loop() {
  SoftS.println("Hello World");
  delay(1000);
}
```

Pulseview Hardware Serial:

![RP2040_HWSerial](https://github.com/user-attachments/assets/e51fff59-c426-4e8b-80a5-ee874e930950)

Pulseview Software Serial:

![RP2040_SWSerial](https://github.com/user-attachments/assets/69ae50de-347b-454c-9830-30d255e35914)

Does anyone know, what I might do wrong here?

**Comment by earlephilhower** [comment]
You are specifying illegal pins for UART0 (`Serial1`, since `Serial` is USB.  `Serial2` is UART1) and crashing the chip.

Please check with the [datasheet](https://datasheets.raspberrypi.com/pico/pico-datasheet.pdf) for the supported pins for UART0(`Serial1`) and UART1(`Serial2`).
