### ISSUE TITLE
Programming and Serial Monitor Problems Since 4.3.0

### ISSUE THREAD

**Issue by mr-stivo** [earlephilhower/arduino-pico#2660]
Since 4.3.0 I'm having problems uploading and using the serial monitor on my generic rp2040 boards. Downgrading to 4.2.1 or earlier things will work normally.

Uploading will usually timeout. If I force the board into programming mode I can program it but the IDE usually times out. The serial monitor will not connect. Any attempt at connecting to the board either by trying to program it or the serial monitor will cause major performance problems with the board until I stop or disconnect the cable.

Is this a known problem with arduino-pico or maybe upgraded pico sdk?

macOS Sonoma 14.5
Arduino IDE 2.3.3

**Comment by earlephilhower** [comment]
What exactly do you mean by "timeout"?  What is the exact message and where is it coming from (the Serial Monitor, the upload script, etc.)?  Cut-n-pasting of the text output would be helpful.

Are you sure the Pico isn't crashed when you are having these timeouts?  If your app panics, then the Pico can't actually run the USB port and you'll get disconnects/etc. and will need to do a BOOTSEL upload.

To verify that, can you upload Blink.ino using BOOTSEL mode first, make sure it's working and blinking, and then upload it again using the normal method (just upload button) and see if that works.  If so, your code may just be crashing under the new core for some reason.

There were no changes at all to the USB code in the repo here from https://github.com/earlephilhower/arduino-pico/compare/4.2.1...4.3.0 so this is either an issue specific to your machine or something that the TinyUSB library had updated.  

You could always try the `picotool` upload method as well if your Mac is having an issue with CDC ports.  After the 1st upload using UF2 mode with an app built with this upload selection, only the custom RPi reboot USB device interface will be used to reset to the ROM bootloaderand then send the flash data over directly.  (It's actually a little faster than the normal UF2 mode but had some extra driver installation steps needed when run on older Windows boxes.)

**Comment by mr-stivo** [comment]
The blink code works ok. I believe the problem is my code having issues with the new core. This is a project I've been working on for the last year or so and previous updates have never been an issue. Reverting back to 4.2.1 I have no problems.

The board is not crashing as I can see it running, but any attempt at accessing it, either by trying to program it or the serial monitor results in the board's performance dropping massively and the IDE will timeout with "Timeout. The IDE has not received the 'success' message from the monitor after successfully connecting to it. Could not connect to /dev/cu.usbmodem2101 serial port." Attempting to program it sometimes works but the IDE sits for a long time at "Resetting /dev/cu.usbmodem2101" (60+ seconds).

I spent a few hours today trying to troubleshoot my code by removing large portions of it but I am unable to isolate the problem reliably. Since the problem seems to be just my code, and I don't want to waste anymore of your time, I'm just going to revert to 4.2.1. I'll try future updates as they're released.

Thank you for your time..

**Comment by earlephilhower** [comment]
No worries, good luck!
