### ISSUE TITLE
Miso and mosi pins selection pin selection crossed

### ISSUE THREAD

**Issue by djsedaw** [earlephilhower/arduino-pico#2675]
When I try to select a pin for the mosi I only get the miso pin selection in the drop down menu and visa Versa for the miso pin

**Comment by earlephilhower** [comment]
Sorry, but I think you have the wrong repo here.  This the Arduino-Pico (IDE) one and there are no menus to select pin configs, that's done in apps you write using this.

**Comment by djsedaw** [comment]
Apologies, you are correctn
