### ISSUE TITLE
i2c communication issue

### ISSUE THREAD

**Issue by natxopedreira** [earlephilhower/arduino-pico#2706]
Hello

I have been using your framework for a long time, thanks for it!!!! Its great!!

Now i¡m trying to use i2c to communicate with a lcd display controller, so my first step is to locate the i2c address, but a simple scanner is not working for me.

I have sda on GP2 and sdl on GP3, running a plain i2c scanner show no devices (i tested 2 sensors and they work with an arduino) and if i try to set the sda and sdl pins with their setters.... i lost the Serial usb output or pico dont even appear in my computer as a serial port...

I'm using platformio, ubuntu and a raspberry pico

```
#include <Arduino.h>
#include "Wire.h"

void setup() {

  Serial.begin(115200);
  delay(5000);
  Serial.println("\nI2C Scanner");

  Wire.setSDA(2);; // setting those i get no usb serial output and sometimes even no usb port
  Wire.setSCL(3); // setting those i get no usb serial output and sometimes even no usb port

  Wire.begin();

}
 
void loop() {
  Serial.println("\nI2C Scanner");
  delay(1000);

  byte error, address;
  int nDevices;
  Serial.println("Scanning...");
  nDevices = 0;
  for(address = 1; address < 127; address++ ) {
    Wire.beginTransmission(address);
    error = Wire.endTransmission();
    if (error == 0) {
      Serial.print("I2C device found at address 0x");
      if (address<16) {

        
        Serial.print("0");
      }
      Serial.println(address,HEX);
      nDevices++;
    }
    else if (error==4) {
      Serial.print("Unknow error at address 0x");
      if (address<16) {
        Serial.print("0");
      }
      Serial.println(address,HEX);
    }    
  }
  if (nDevices == 0) {
    Serial.println("No I2C devices found\n");
  }
  else {
    Serial.println("done\n");
  }
  delay(1000);          

}

```

**Comment by earlephilhower** [comment]
Your app is crashing the Pico because those pins aren't legal.  Please see the [Pico datasheet](https://datasheets.raspberrypi.com/pico/Pico-R3-A4-Pinout.pdf) for legal I2C0(Wire) pins.

You could also use `Wire1` (I2C1) for which those pins are legal.
