### ISSUE TITLE
(Suggestion) Use Specific SDK file for specific board (unless there isn’t one)

### ISSUE THREAD

**Issue by MeteorTheProto** [earlephilhower/arduino-pico#2717]
Just something I noticed while poking through stuff. Somewhere in the commons of the RP2350 core it’s using a postage stamp xl board definition from the SDK but I ran into issues trying to get my RP2350A board to work with the core. Perhaps this is a future potential problem with trying to add more boards?

edit: found it! It’s in this file  [include/rp2350/pico_base/pico/config_autogen.h](https://github.com/earlephilhower/arduino-pico/blob/master/include/rp2350/pico_base/pico/config_autogen.h)

**Comment by earlephilhower** [comment]
All boards use a single config from the SDK.  We don't use much from the SDK, and only ensure the SDK provides all the needed functions.  Pin assignments aren't even looked at, for example.  That lets 1 version run for everything.  A single RP2040 build runs 40+ Pico 1 boards, and a single RP2350 version runs all 20+ Pico 2 boards, both RP2350A and RP2350B.  There's no need for custom board builds, and they would be both a real pain to maintain but they'd also blow up the repo.  We already have 3 binaries (rp2040, rp2350, and rp2350-riscv) for libpico, no need for more.  If you're not able to get a basic RP2350A board running (the baseline, simplest) please refer to an existing board definition.  The RP2350A is trivially implemented in a bunch of boards already.
