### ISSUE TITLE
Tag 1.9.3 breakes SPI connection with MCP2515

### ISSUE THREAD

**Issue by pepeRossRobotics** [earlephilhower/arduino-pico#274]
When updating the library from 1.9.2 to 1.9.3 the SPI communication seems broken to me
```
static const byte MCP2515_SCK   = 18;
static const byte MCP2515_MOSI  = 19;
static const byte MCP2515_MISO  = 16;
static const byte MCP2515_CS    = 17;
static const byte MCP2515_INT   = 6;
```

The only think that jumps to my eye is the addition of the line 46
`compiler.libstdcpp="{runtime.platform.path}/lib/`
to the file platform.txt

**Comment by earlephilhower** [comment]
Can you try the simple change in https://github.com/earlephilhower/arduino-pico/discussions/276#discussioncomment-1164357 and report back if it fixes the issue?  I have a feeling the ARM low-level stuff got busted when I completely removed C++ exceptions.  The change linked will go back to the normal one (slightly more RAM/flash).
