### ISSUE TITLE
No /media mount point

### ISSUE THREAD

**Issue by ccpetersen** [earlephilhower/arduino-pico#28]
It would appear the mount point for the pico is hardcoded to be "/media".  In Manjaro(Arch) usb mount points are in "/run/media". The simple solution is to create a link "/run/media -> /media", works but should be fixed.

Anyway thanks for doing this.

**Comment by vslinuxdotnet** [comment]
Yes it hard coded in  uf2conv.py in line: 238 
rootpath = "/media"

Should be changed to something like this:

```
rootpath = "/media"
if not os.path.isdir(rootpath):
   rootpath = "/run"
```

**Comment by earlephilhower** [comment]
I'll manually add this here, but I think you want to also open an issue/PR upstream where the file comes from:  https://github.com/microsoft/uf2

**Comment by earlephilhower** [comment]
@ccpetersen Can you check out #37 and report back?  Thx!
