### ISSUE TITLE
Sparkfun Thing Plus RP2040 - SD

### ISSUE THREAD

**Issue by paulhayes** [earlephilhower/arduino-pico#290]
I've been having trouble using the SD card on the [Thing Plus RP2040](https://learn.sparkfun.com/tutorials/rp2040-thing-plus-hookup-guide/hardware-overview]). I made the following changes to the pins_arduino.h of the Sparkfun ProMicro RP2040. And I also specified the SPI1 as the SDCARD_SPI. However I always get "initialization failed!". I've also included my example code. 

- Could you add support for the Thing Plus board to the library
- Any ideas why this would fail?

```
#pragma once

// Taken from schematic at https://cdn.sparkfun.com/assets/e/2/7/6/b/ProMicroRP2040_Graphical_Datasheet.pdf

// LEDs updated for thing plus
#define PIN_LED        (25u)

#define PIN_NEOPIXEL   (8)
#define NUM_NEOPIXEL   (1)

// UARTs
#define PIN_SERIAL1_TX (0u)
#define PIN_SERIAL1_RX (1u)
#define PIN_SERIAL2_TX (8u)
#define PIN_SERIAL2_RX (9u)

// SPI updated for thing plus
#define PIN_SPI0_MISO  (20u) 
#define PIN_SPI0_MOSI  (23u) 
#define PIN_SPI0_SCK   (22u)
#define PIN_SPI0_SS    (21u)
#define PIN_SPI1_MISO  (12u)
#define PIN_SPI1_MOSI  (15u)
#define PIN_SPI1_SCK   (14u)
#define PIN_SPI1_SS    (5u) 

// Wire
#define PIN_WIRE0_SDA  (16u)
#define PIN_WIRE0_SCL  (17u)
#define PIN_WIRE1_SDA  (31u)
#define PIN_WIRE1_SCL  (31u)

#define SERIAL_HOWMANY (3u)
#define SPI_HOWMANY    (2u)
#define WIRE_HOWMANY   (1u)

#include "../generic/common.h"

```

```
#include <SPI.h>
#include <SD.h>

File root;
#define SDCARD_SPI SPI1
#define SDCARD_SS_PIN 5

void setup() {
  // Open serial communications and wait for port to open:
    Serial.begin(115200);
  delay(5000);
 
  Serial.print("Initializing SD card...");
  SPI1.setRX(12);
  SPI1.setTX(15);
  SPI1.setSCK(14);
  
  if (!SD.begin(SDCARD_SS_PIN)) {
    Serial.println("initialization failed!");
    return;
  }
  Serial.println("initialization done.");

  //root = SD.open("/");

  //printDirectory(root, 0);

  Serial.println("done!");
}

void loop() {
  // nothing happens after setup finishes.
  delay(3000);
  Serial.printf("Core temperature: %2.1fC\n", analogReadTemp());
}

void printDirectory(File dir, int numTabs) {
  Serial.println("meep");
  while (true) {

    File entry =  dir.openNextFile();
    if (! entry) {
      // no more files
      break;
    }
    for (uint8_t i = 0; i < numTabs; i++) {
      Serial.print('\t');
    }
    Serial.print(entry.name());
    if (entry.isDirectory()) {
      Serial.println("/");
      printDirectory(entry, numTabs + 1);
    } else {
      // files have sizes, directories do not
      Serial.print("\t\t");
      Serial.print(entry.size(), DEC);
      time_t cr = entry.getCreationTime();
      time_t lw = entry.getLastWrite();
      struct tm * tmstruct = localtime(&cr);
      Serial.printf("\tCREATION: %d-%02d-%02d %02d:%02d:%02d", (tmstruct->tm_year) + 1900, (tmstruct->tm_mon) + 1, tmstruct->tm_mday, tmstruct->tm_hour, tmstruct->tm_min, tmstruct->tm_sec);
      tmstruct = localtime(&lw);
      Serial.printf("\tLAST WRITE: %d-%02d-%02d %02d:%02d:%02d\n", (tmstruct->tm_year) + 1900, (tmstruct->tm_mon) + 1, tmstruct->tm_mday, tmstruct->tm_hour, tmstruct->tm_min, tmstruct->tm_sec);
    }
    entry.close();
  }
}
```

**Comment by spectruma** [comment]
@paulhayes I have a similar problem with the Thing Plus and glad to hear that on your side the SD card is working now.
But I still struggling and I am not able yet to solve to problem.
I have one question. In your above posted header file for the Thing Plus you define
#define PIN_SPI1_SS    (5u) 
but should this not be (9u) (according to the schematics). Anyway both values are not working for me.
Btw. I am using PlatformIO and the SD lib RP2040_SD from  @khoih-prog

**Comment by paulhayes** [comment]
Ah yes that caught me out. That entry on the sparkfun website I think is incorrect.
, The next page specifies keeping SS ( equivalent to chip select ) at 5 [here](https://learn.sparkfun.com/tutorials/rp2040-thing-plus-hookup-guide/software-overview)





 I was using the changes to pin header file recommended by sparkfun as a reference.

**Comment by paulhayes** [comment]
I'll post my changes here tomorrow. So you can try them.

I had to set up SPI1 and modify the code to allow SS to be used on SPI1 ( it's disallowed in the SD library )

**Comment by spectruma** [comment]
Thank you for your comments. Now everything works. I had to modify pins_arduino.h (which i didn't prefer to do)
But if it is at the moment the only solution left, I can live with it.
