### ISSUE TITLE
printf not outputting floating point numbers

### ISSUE THREAD

**Issue by brandonplank** [earlephilhower/arduino-pico#32]
![image](https://user-images.githubusercontent.com/52553007/112701235-78d58680-8e66-11eb-8265-41c2e84f1e73.png)
yeah, the screenshot speaks for itself.

**Comment by earlephilhower** [comment]
Your format string is using '%d %d %d` which means you must pass in an `int` not a `float`.  You might even get a compile warning about it...

You'll want `%f` for floats...

**Comment by brandonplank** [comment]
tried %f. Its does not even output the float.
It outputs nothing.

**Comment by brandonplank** [comment]
That why i used %d. and i even casted it to a int using (int)

**Comment by brandonplank** [comment]
![image](https://user-images.githubusercontent.com/52553007/112702048-a4f20700-8e68-11eb-9581-957535438267.png)

**Comment by brandonplank** [comment]
See. Its odd

**Comment by earlephilhower** [comment]
Ah, that is interesting and proper code.  The newlib printf may be linked w/o floating point support.  Let me do a little digging, or you can check out the libc.a yourself in parallel...

**Comment by earlephilhower** [comment]
Oh, and in the meantime `Serial.print(<float>)` does work (it uses `dtostrf`, a separate function provided by the core).

**Comment by earlephilhower** [comment]
Trivial linking fix.  0.9.7 should get you going.

**Comment by brandonplank** [comment]
Thanks!
