### ISSUE TITLE
Adding WMath.cpp

### ISSUE THREAD

**Issue by joachimhs** [earlephilhower/arduino-pico#34]
Hello, 

Is it possible to add WMath.cpp (https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/WMath.cpp) to this Arduino-pico core, so that the random functions are also available to use? 

Is it simply an issue of adding the WMath.cpp file in the correct directory, or is there more work involved?

**Comment by earlephilhower** [comment]
Yes it is.  Check the latest release

**Comment by joachimhs** [comment]
Thank you for that! I am making good progress in providing Pico support for a block-based programming tool :) (https://vimeo.com/529651781)

**Comment by earlephilhower** [comment]
That's pretty awesome!  Good luck, keep us informed!
