### ISSUE TITLE
Upload error after good build on windows and linux

### ISSUE THREAD

**Issue by nsilveri** [earlephilhower/arduino-pico#349]
Hello,
every time i try to upload i get this error, i tried with windows and linux on the same computer and i get the same error, i tried on another computer and everything works fine.
How can I solve? 

![Screenshot (1450)](https://user-images.githubusercontent.com/24323132/142771356-22bfc967-1c4f-4417-9aa7-dbf1fb86fa72.png)
![Schermata del 2021-11-21 17-40-08](https://user-images.githubusercontent.com/24323132/142771361-bb980940-09f3-4d93-967e-b9e475b62cae.png)

**Comment by centerorbit** [comment]
I discovered that if you have Arduino IDE installed via Flatpak (on Linux) you will receive an error on line 250 in get_drives. Whereas if you install Arduino IDE via the download from their website, you don't get such error and upload works.

I believe it's likely a Flatpak permissions issue.

**Comment by earlephilhower** [comment]
Good point @centerorbit .  Also see #420 for some other users' experience.  Permissions under snap and flatpak can get messy!
