### ISSUE TITLE
Using pico-extras sd_card driver in Arduino

### ISSUE THREAD

**Issue by jpiat** [earlephilhower/arduino-pico#350]
Hi,

i'm trying to port some code to the pico demo VGA board but this board uses non-spi capable pins of the pico to access the sd card. One can bitbang the SPI protocol to use the sd card in arduino but the pico-extras repository provides a driver based on PIO for sd cards. I there any project to port the SD related libraries of the arduino core to use this PIO based driver ?

Regards,

**Comment by earlephilhower** [comment]
I'm not actively looking at it, but it sounds like you're looking for a couple things, a software SPI (CPU based) and the pico-extras experimental SPI-4bit (PIO based).

If there are any generic Arduino libraries that implement SPI, then they might "just work" here.  Have you taken a look?

PRs are always welcome!

**Comment by jpiat** [comment]
I have implemented a wrapper for the spi PIO code example to use existing
libraries with any IO of the pico (for example on the VGA demo board).
https://github.com/jpiat/PIOSpi

I'll have a look into using the SD card PIO driver to reach higher transfer
speed

**Comment by earlephilhower** [comment]
That's awesome, thanks for the link!  Have you published it in the Arduino library manager so people can find it?

**Comment by jpiat** [comment]
Not yet, i want to test it a bit more before (only tested spi mode so far).
One issue I'm having is that i statically declare the PIO and SM index in
the code which might make it incompatible to use with other libraries using
the same PIO/SM combination. Do you know if there is any way to check for
PIO/SM already used to dinamically allocate the PIO/SM and avoid conflict
between libraries ?

**Comment by earlephilhower** [comment]
> One issue I'm having is that i statically declare the PIO and SM index in the code which might make it incompatible to use with other libraries using the same PIO/SM combination. Do you know if there is any way to check for PIO/SM already used to dinamically allocate the PIO/SM and avoid conflict between libraries ? 

The PICO SDK supports a way of registering PIO usage.  I use it in the `PIOProgram` class to avoid hardcoding any PIO unit/offsets:
https://github.com/earlephilhower/arduino-pico/blob/1afbbaba63c34afcceee42a3e71178923abf92e4/cores/rp2040/RP2040.h#L186-L231

**Comment by jpiat** [comment]
Great ! I just finished testing using PIOProgram in my PIOSpi driver and its working great. Thanks
