### ISSUE TITLE
MIDI_TEST  Tiny USB example 

### ISSUE THREAD

**Issue by eowavemarc** [earlephilhower/arduino-pico#352]
in the basic MIDI USB example when you send a message from the computer to the board, there is one message delay in the analyse of incoming messages. for ex. when you send a note message, you receive the "note on" message when the "note off" has been sent.

**Comment by hathach** [comment]
which TinyUSB version you are using, the bundled lib could be out of date. This bug is fixed in latest release https://github.com/adafruit/Adafruit_TinyUSB_Arduino/issues/64 . just install it via lib manager. Arduino IDE will pick the latest version.

**Comment by eowavemarc** [comment]
it works , thank you for the advise

**Comment by hathach** [comment]
@eowavemarc no problem, you should close this issue.
