### ISSUE TITLE
I tried porting FreeRTOS and it's not compatible

### ISSUE THREAD

**Issue by imzooming** [earlephilhower/arduino-pico#354]
I'm using Arduino IDE
The mere inclusion of the lib will cause the Pico to hang, without even using any of the functions.
`#include <FreeRTOS.h>`
I tried to debug it, no, reading memory fails. Without including the FreeRTOS, I can debug with GDB + OpenOCD just fine.

## How I made the FreeRTOS port
1. Download the FreeRTOS kernel latest release zip from https://github.com/FreeRTOS/FreeRTOS-Kernel/releases/tag/V10.4.6.
2. Copied everything in `include` into folder root
3. Copied `heap_4.c` from `portable/MemMang` to folder root
4. Copied `port.c` `portmacro.h` from `portable/GCC/ARM_CM0` to folder root
5. Copied `FreeRTOSConfig.h` to folder root, which worked RP2040 with pico-sdk standalone project before
6. Deleted `portable` because it's useless now
7. Made them into zip, [FreeRTOS-Kernel.zip](https://github.com/earlephilhower/arduino-pico/files/7619587/FreeRTOS-Kernel.zip)
8. Sketch>Include Library>Add ZIP library
9. Added `#include <FreeRTOS.h>` to main .ino file
10. Boom, the whole project hangs, can't debug

This is beyond me, I don't understand, why???? Reeeee

**Comment by earlephilhower** [comment]
You'll need to redo the entire core/rp2040 system to do any FreeRTOS porting.  It's a full operating system and expects to run the whole system with its own pre-init, own main, own interrupt control, etc.  The existing main.cpp/etc. also expect to control everything, so `boom` is the expected result. :(

If you really want to get FreeRTOS running w/Arduino (which would be very cool!) I thin you really need to start from scratch and make the existing Arduino main() into a FreeRTOS task.  The ESP32 Arduino core does this, I believe, if you are looking for a worked example.

Good luck!
