### ISSUE TITLE
Nano RP2040 Connect not showing as a device under ports

### ISSUE THREAD

**Issue by kendo55** [earlephilhower/arduino-pico#372]
first of all ... thanks to everyone for the great work!
I've tried different PICO boards.
and i followed the installation instructions exactly to install the release 1.8.6
Windows Users: ........

**first sketch upload....works fine!**

`Sketch uses 58424 bytes (0%) of program storage space. Maximum is 16773120 bytes.
Global variables use 11184 bytes (4%) of dynamic memory, leaving 250960 bytes for local variables. Maximum is 262144 bytes.
Resetting COM13
Converting to uf2, output size: 130560, start address: 0x2000
Flashing F: (RPI-RP2)
Wrote 130560 bytes to F:/NEW.UF2
Board at COM13 is not available`

**2nd sketch upload....does not works!**

`Resetting COM13
Converting to uf2, output size: 130560, start address: 0x2000
No drive to deploy.
An error occurred while uploading the sketch`

in the Device Manager:--> Other Devices --> **PicoArduino** 
is visible but it says  ---> Driver is not installed

I'm working with WIN 8.1
and i have read many different forums about that problem,
but couldn't find any solution. :-(

**Comment by earlephilhower** [comment]
See the docs:  https://arduino-pico.readthedocs.io/en/latest/install.html#windows-7-driver-notes

Alternatively, just hold the BOOTSEL button while plugging in the board to not require any drivers at all.
