### ISSUE TITLE
build.mcu mentionned twice in boards.txt

### ISSUE THREAD

**Issue by rei-vilo** [earlephilhower/arduino-pico#380]
The `build.mcu` variable is mentioned twice in [boards.txt](https://github.com/earlephilhower/arduino-pico/blob/master/boards.txt).

Example for `rpipico` board

https://github.com/earlephilhower/arduino-pico/blob/7120a1508c09f8d409014552d4b7009106a58623/boards.txt#L20
https://github.com/earlephilhower/arduino-pico/blob/7120a1508c09f8d409014552d4b7009106a58623/boards.txt#L32

`build.mcu` is used for libraries distributed as [pre-compiled binaries](https://arduino.github.io/arduino-cli/0.20/library-specification/#precompiled-binaries). This duplicate entry prevents from using that feature.

**Comment by rei-vilo** [comment]
See PR #381

**Comment by earlephilhower** [comment]
Thanks for the PR!  I've combined your changes with the proper script changes and things should be working fine now w/binary libs.

**Comment by rei-vilo** [comment]
You're welcome!
