### ISSUE TITLE
spi.beginTransaction() takes a long time to complete

### ISSUE THREAD

**Issue by Bodmer** [earlephilhower/arduino-pico#392]
A line like this using this board package:
```
spi.beginTransaction(SPISettings(SPI_FREQUENCY, MSBFIRST, TFT_SPI_MODE));
```
takes ~50us to complete. Using the Arduino Mbed OS RP2040 package completes in <1us.

It appears that the function is slowed down for some reason, maybe by debug code?

**Comment by Bodmer** [comment]
Here is a test sketch that demonstrates the problem. This slows down SPI based sketches significantly.
```
// Arduino RP2040 package   ~0.49us
// Community pacakge      ~ 69.10us
#include <SPI.h>
void setup() {
  Serial.begin(115200);
  SPI.begin();
}

void loop() {
  uint32_t dt = micros();
  for (int i = 0; i < 1000; i++) {
    SPI.beginTransaction(SPISettings(70000000, MSBFIRST, 0));
    SPI.endTransaction();
  }
  Serial.println(micros() - dt);
}
```

**Comment by earlephilhower** [comment]
@Bodmer please try the PR #394 and report back, since you seem to have a setup ready to test.

It should make performance basically identical to the MBED one, but I need someone to verify that the change I did still results in working SPI comms...

**Comment by Bodmer** [comment]
Yes, performance is now the same.

Thank you.

**Comment by earlephilhower** [comment]
> Yes, performance is now the same.

And, just to be 100% sure, it still works, right? :)

**Comment by Bodmer** [comment]
Yes, it works for me. I have two SPI devices on the same bus that operate at different SPI clock frequencies and the beginTransaction() and endTransaction() functions operate as expected, changing the SPI frequency when each device is accessed.

**Comment by Bodmer** [comment]
Performance is now comparable to the Mbed package. Drawing 10,000 pixels to a TFT, first using beginTransaction() and endTransaction(), second without.
```
1.9.9 Philhower package!
drawPixel = 1486ms
Locked drawPixel = 75ms

Arduino MBED!
drawPixel = 113ms
Locked drawPixel = 77ms

FastSPI Philhower package!
drawPixel = 110ms
Locked drawPixel = 75ms
```

**Comment by earlephilhower** [comment]
Thanks for the confirmation!  This will be in the next release, coming soon (serial stuff I want to get in, too).
