### ISSUE TITLE
Support for RAK11300 Board

### ISSUE THREAD

**Issue by fabltd** [earlephilhower/arduino-pico#406]
Hi

Can support be added for this board:

(https://github.com/RAKWireless/WisBlock/tree/master/PlatformIO/RAK11300)

**Comment by earlephilhower** [comment]
That repo looks a little bit of a mess, seems to duplicate a lot of files that are already in both the Arduino.cc MBED core and this one, and even includes a blob for libmbed.a (which isn't used or usable here).  There also doesn't seem to be a public internal schematic for the module, either.  So, it's not something I'd be able to do w/o much hands-on with with an actual module and a lot of time.

However, if you'd like to give it a go I'd be happy to include it in the core support!  Good luck!
