### ISSUE TITLE
Support for ATECC608A chip on Arduino Nano RP2040

### ISSUE THREAD

**Issue by mcarrickscott** [earlephilhower/arduino-pico#409]
Really looking forward to this!

**Comment by earlephilhower** [comment]
Sorry, there are no plans to re-develop Arduino.cc Connect-specific libraries here.  Checking online, there seems to already be a library from Arduino to support that chip, so I would recommend trying it out: https://github.com/arduino-libraries/ArduinoECCX08

Good luck!
