### ISSUE TITLE
Wire (I2C library)

### ISSUE THREAD

**Issue by mcarrickscott** [earlephilhower/arduino-pico#411]
Can WIRE_BUFFER_SIZE in wire.h be increased from 128 to 256? In the equivalent wire.h for the mbed core for RP2040 the transmit buffer size is 256, so this change should make it compatible.

I ask because my program uses the ECCX08 Arduino library to communicate via I2C with the ECC608a chip on the Arduino Nano RP2040 connect. My program needs to transmit an ECDSA signature to the chip for verification, and the full signature size is 136 bytes. The program works fine using the mbed core, but not with this one, unless I make the suggested change.

**Comment by earlephilhower** [comment]
Simple change requests with justification like this one, I like!  I'm used to working w/less RAM than the RP2040 so was conservative initially.  1.9.13 should get you and others going.
