### ISSUE TITLE
Question - Duplicate declarations of millis() and micros()? 

### ISSUE THREAD

**Issue by rei-vilo** [earlephilhower/arduino-pico#418]
The functions `millis()` and `micros()` are declared 

+ in ~/.arduino15/packages/rp2040/hardware/rp2040/1.9.13/cores/rp2040/delay.cpp

https://github.com/earlephilhower/arduino-pico/blob/1fdc0ab7c13cece1403985c7d695816900eb751e/cores/rp2040/delay.cpp#L54-L60

+ and ~/.arduino15/packages/rp2040/hardware/rp2040/1.9.13/cores/rp2040/millis.cpp

https://github.com/earlephilhower/arduino-pico/blob/1fdc0ab7c13cece1403985c7d695816900eb751e/cores/rp2040/millis.cpp#L23-L29

Occasionally, the compiler complains about `multiple definition of 'millis'`, and same for `micros`.

```
~/.arduino15/packages/rp2040/tools/pqt-gcc/1.3.1-a-7855b0c/bin/../lib/gcc/arm-none-eabi/10.3.0/../../../../arm-none-eabi/bin/ld: delay.cpp.o: in function `millis':
~/.arduino15/packages/rp2040/hardware/rp2040/1.9.13/cores/rp2040/delay.cpp:54: multiple definition of `millis'; millis.cpp.o:~/.arduino15/packages/rp2040/hardware/rp2040/1.9.13/cores/rp2040/millis.cpp:23: first defined here
```

I fix the issue by commenting out the functions on one of the files.

Are the declarations duplicate? Thank you.

**Comment by earlephilhower** [comment]
Good catch.  Very strange it didn't pop up for other people, but it's obviously not right as-is!
