### ISSUE TITLE
optimizations?

### ISSUE THREAD

**Issue by WestfW** [earlephilhower/arduino-pico#451]
Are you interested in "small optimizations" that theoretically move the core slightly further away from being portable to potential other RP chips?

For example, microseconds (currently `to_us_since_boot(get_absolute_time());` could use (or be aliased to) `time_us_32()` instead.

And of course digitalWrite() is always prime for speeding up to various degrees...

**Comment by earlephilhower** [comment]
Premature optimization is the root of many evils, but if you have a few things you'd like to suggest then please feel free to submit PRs.  But as a rule, I really want to leverage the SDK as much as possible.  Algorithmic optimization almost always trumps micro optimisations in my experience.  Plus I'm sure there are tons of bugs left to be squashed!

I'd suggest submitting each optimization suggestion as its own PR just to make it easier for everyone. Thanks!
