### ISSUE TITLE
Could the EEPROM emulation limit be increased or removed?

### ISSUE THREAD

**Issue by technoblogy** [earlephilhower/arduino-pico#455]
The core includes EEPROM emulation developed from the ESP8266 version, and in EEPROM.begin() limits the size to 4096 bytes. Decided to pause this comment while I test it out myself.

**Comment by technoblogy** [comment]
Sorry, I think I've seen what the problem is. EEPROM allocates a 4096 RAM sector buffer on the heap, and this would have to increase to the size of the whole Lisp workspace for the change I'm suggesting, which is impractical. I would need to rewrite the code to erase the flash, and then write the Lisp workspace directly to the flash 256 bytes at a time.

**Comment by earlephilhower** [comment]
Expanding EEPROM isn't easily possibly as you found out and doesn't make a lot of sense.  Its use case is for old code which ran on the 8-bit AVRs (who did have a real EEPROM) to let them port more easily.  LittleFS is the way to go for anything written in the last 20 years and not complicated at all.  No need to worry about flash at all.

````
File ws = LittleFS.open("workspace.bin", "w");
if (!ws) { error... }
auto len = ws.write(workspace, 160*1024);
if (len != 160*1024) { error... }
ws.close();
````
and
````
File ws = LittleFS.open("workspace.bin", "r");
if (!ws) { error... }
auto len = ws.read(workspace, 160*1024);
if (len != 160*1024) { error... }
ws.close();
````

are pretty much all you need do.  There are examples in the tree you can look at for more info, or the docs.

**Comment by technoblogy** [comment]
Thanks a lot. I'll see if I can get that working!

**Comment by earlephilhower** [comment]
Also, please make sure you make space for the FS using the `Tools->Flash Size` IDE menu.  You'll also want a `LittleFS.begin()` in your `setup()` somewhere, too, of course.

**Comment by technoblogy** [comment]
Thanks - it's working nicely, and was as simple as you described.
