### ISSUE TITLE
Allow changing I2C clock speed after begin() is called

### ISSUE THREAD

**Issue by jhmaloney** [earlephilhower/arduino-pico#458]
While I'm not an Arduino expert, on most of the 32-bit Arduino platforms I use if you want to change the I2C clock speed to 400 kbps "fast mode", you do so after calling begin():

```
	Wire.begin();
	Wire.setClock(400000); // set i2c fast mode
```

However, in this framework it must be done in the reverse order:

```
	Wire.setClock(400000); // set i2c fast mode
	Wire.begin();
```

After Wire.begin() is called, calls to Wire.setClock() have no effect. I discovered this because my I2C OLED display updates were taking much longer on the Pico than on other boards. When I checked with a 'scope, the I2C clock was running at the default speed of ~100 kbps, not the intended 400 kbps.

I've worked around this with an #ifdef but I wanted to mention it since it might take folks by surprise when porting code from other Arduino frameworks.

**Comment by earlephilhower** [comment]
Thanks for the very concise bug report!

#459  should fix this.  Just need to call the right API if we're already running.

**Comment by jhmaloney** [comment]
That was quick. Glad it was an easy fix. Thanks!
