### ISSUE TITLE
Sketch upload to serial port fails on Mac

### ISSUE THREAD

**Issue by blurfl** [earlephilhower/arduino-pico#46]
Sketch upload to serial port fails on macos because the Arduino IDE uses the callout device "/dev/cu". Adding recognition of "/dev/cu" to uf2conv.py makes the sketch upload work.
```
        if str(args.serial).startswith("/dev/tty") or str(args.serial).startswith("COM")or str(args.serial).startswith("/dev/cu"):

````

**Comment by earlephilhower** [comment]
@blurfl Would you like to do a PR for this?  I don't have a Mac so can't test any changes there, especially Os-specific ones like this.

**Comment by blurfl** [comment]
Happy to. Thanks for all your work!

**Comment by earlephilhower** [comment]
Thanks!
