### ISSUE TITLE
Add support for analogReadResolution and default to 10-bits

### ISSUE THREAD

**Issue by jhmaloney** [earlephilhower/arduino-pico#460]
Feature request, not urgent.

Although the [Arduino docs](https://www.arduino.cc/reference/en/language/functions/zero-due-mkr-family/analogreadresolution) say that the analogReadResolution() function is for the Zero, Due, and Mkr board families, it is supported by many other Arduino frameworks (e.g. nRF5x, ESP32, ESP8266). It is useful when porting Arduino code from other boards. Most frameworks default to 10-bit resolution for backward compatibility with AVR-based Arduinos. Parameter range is 1 to 31 bits. The analogRead() function shifts the result right or left as needed to match the hardware ADC resolution to the desired resolution.

**Comment by technoblogy** [comment]
I support this (I assume you meant **analogReadResolution()** in the first sentence), for consistency with other cores.

**Comment by jhmaloney** [comment]
Yes, I did. Good catch! I've corrected it above.

**Comment by jhmaloney** [comment]
Terrific! Thank you!
