### ISSUE TITLE
The 'Other' Sparkfun boards

### ISSUE THREAD

**Issue by K2AAE** [earlephilhower/arduino-pico#507]
I thank you for the effort of grooming the Pro Micro RP2040 information  for this board package, looking for information in Sparkfun documentation has turned out to be amusing to say the least.  I have the pins for the Thing-Plus RP2040 but I don't understand what the uxx means or what else has to happen to add another board variant.

**Comment by earlephilhower** [comment]
You'd need to map between the PCB labeled pins and the RPO2040 GPIO pins, as well as adjust the serial, SPI, etc. ports to the proper defaults.  Your best bet is to copy the existing one and work from there.

Alternatively, you can use the `generic` option which should get you going w/o changing anything in the core for now.
