### ISSUE TITLE
Pad drive strength

### ISSUE THREAD

**Issue by jlbirccyn** [earlephilhower/arduino-pico#526]
Hello,

Thanks for this great work!

I looked at the code a bit and did some testing and the drive strength is the default value at reset (4mA), which is pretty low. Would it be possible to set it to 12mA in pinMode? Otherwise we can call the function of the sdk(gpio_set_drive_strength) but it is not the usual simplicity of the Arduino.

Kind regards.

**Comment by earlephilhower** [comment]
I'm loathe to change the default value simply because the core is being used by folks for embedded, battery-powered apps.  Changing to a higher drive strength could change the behavior of their boards and reduce battery life.

Any ideas as to a way of allowing folks to override the default?

**Comment by Gavin-Perry** [comment]
I'm happy with gpio_set_drive_strength() 
It clearly says what it does and does the job.

**Comment by jlbirccyn** [comment]
I understand

Maybe add 4 constants to use with pinMode : OUTPUT_2, OUTPUT_4, OUTPUT_8 and OUTPUT_12? OUTPUT would default to OUTPUT4 for compatibility.

**Comment by earlephilhower** [comment]
Interesting idea, especially since it seems the RP2040 can individually set the drive strengths on a per-pad basis.  Would you like to so a Pull Request?  This should be a pretty simple addition...

**Comment by jlbirccyn** [comment]
Of course I do. I'll handle it.

**Comment by earlephilhower** [comment]
Fixed by #532
