### ISSUE TITLE
PlatformIO section in the documentation seems to be outdated

### ISSUE THREAD

**Issue by Laserjones** [earlephilhower/arduino-pico#529]
Hi and thanks for your great work! :-)

I found the documentation PDF (arduino-pico-readthedocs-io-en-latest.pdf), version 1.0.0, dated March 17. I struggled to get the RP Pico connected to PlatformIO until I finally found a hint in some forum that I needed to use Zadig to install the WinUSB driver on the Pico, replacing the standard bootloader. After doing that, I was finally able to upload firmware from PlatformIO using only the default platformio.ini that PlatformIO creates via the Project Wizard:

[env:pico]
platform = raspberrypi
board = pico
framework = arduino

So it seems to me that the information in section 4 of the documentation, which describes a lot of additional stuff, is outdated. I think it would be useful to describe the Zadig process instead.

Best regards,
Joerg

**Comment by earlephilhower** [comment]
Yes.  I'm not a PIO user but AFAIK the docs here still contain the special sauce you need to pull in this core vs. the MBED Arduino.cc one.  Good luck!
