### ISSUE TITLE
Adapting the PJON library for RP2040

### ISSUE THREAD

**Issue by fletchjp** [earlephilhower/arduino-pico#534]
I want to adapt the PJON library to run with the Raspberry Pi Pico and also with the Arduino NANO RP2040 connect.

https://github.com/gioblu/PJON

I have raised an issue at the library and it needs to be modified to compile with ARDUINO_ARCH_RP2040

How could I go about getting this to work?

Thanks John

**Comment by earlephilhower** [comment]
Sorry, you'll need to work with that library's author to do a port.  If bugs in the core here are found while doing the port, you can open a new issue with an MCVE so we can reproduce here.  Good luck!
