### ISSUE TITLE
support for Seeed XIAO RP2040 board

### ISSUE THREAD

**Issue by SilasMoon** [earlephilhower/arduino-pico#537]
Please add support for the Seeed XIAO RP2040 board: https://www.seeedstudio.com/XIAO-RP2040-v1-0-p-5026.html
Thank you.

**Comment by SilasMoon** [comment]
Here are the results:

generic SPI/2 : ok
generic SPI/4 : ok
IS25LP080 QSPI /2 : NOK
IS25LP080 QSPI /4 : NOK
W25Q080 QSPI /2 : ok
W25Q080 QSPI /4 : ok
W25X10CL QSPI /2 : ok
W25X10CL QSPI /2 : ok
W25X10CL QSPI /4 : ok

I could not find anywhere constant pin names for these:
NEOPIXEL LED : GPIO_12
RGB LED blue : GPIO_25
RGB LED red : GPIO_17
RGB LED green : GPIO_16

**Comment by earlephilhower** [comment]
Thanks for the report.  It's merged and will be in the next release.
