### ISSUE TITLE
Upload of a substantial program crashes the Arduino IDE

### ISSUE THREAD

**Issue by technoblogy** [earlephilhower/arduino-pico#57]
I've now successfully uploaded small programs, such as Blink, and a Serial test. But when I upload a more substantial program of about 80Kbytes when compiled (my uLisp Lisp interpreter) it seems to crash the Arduino IDE on my Mac in a way that even a Force-Quit doesn't fix, and I have to restart my Mac to continue. So this is making further progress a bit slow.

Any suggestions?

**Comment by earlephilhower** [comment]
@technoblogy the upload stage is pretty simple and uses the standard UF2 upload tool from Microsoft.  How that would cause your Mac to freeze, I have no idea unfortunately.  I'd check physical things, especially USB cables, as they sometimes are underspec'd and give power droops under extended load.

FWIW, large projects have been done (see https://github.com/earlephilhower/arduino-pico/issues/11 ) without any specific upload issues.

Anyone on a Mac, please feel free to chime in!

You could also use a PicoProbe (see 0.9.13) which would use a different upload method buy selecting a different board in the menus.

**Comment by technoblogy** [comment]
OK, thanks. I'll simplify my program and then reintroduce functionality in stages to see at what point it breaks.

**Comment by marcelvanherk** [comment]
I compile on windows, and indeed my code is fairly big 731k UF2; no problems

**Comment by blurfl** [comment]
Testing with @marcelvanherk 's code on a Mac with Arduino 1.8.14-hourly, the 726K UF2 uploads without error. FWIW I've had other issues with the Arduino IDE on macos 11.3 but they are unrelated to any individual project.

**Comment by technoblogy** [comment]
Thanks - the problem must be with my code.

**Comment by earlephilhower** [comment]
Given the discussion, I'm going to close this for now.
