### ISSUE TITLE
Missing dependency OpenOCD

### ISSUE THREAD

**Issue by dingyifei** [earlephilhower/arduino-pico#576]
Version: 2.0.0-rc6-nightly-20220507
Date: 2022-05-07T03:19:16.802Z
CLI Version: 0.21.0 [10107d24]

Copyright © 2022 Arduino SA

arduino-pico 2.0.0

System: Fedora 35

After installation via arduino ide, system/ folder is empty (only has the placeholder file). The following message appears when I try to upload.

```
Sketch uses 37340 bytes (1%) of program storage space. Maximum is 2093056 bytes.
Global variables use 3556 bytes (1%) of dynamic memory, leaving 242204 bytes for local variables. Maximum is 245760 bytes.

--------------------------
Compilation complete.
Upload error: Failed uploading: cannot execute upload tool: fork/exec /home/yifeiding/.arduino15/packages/rp2040/hardware/rp2040/2.0.0/system/openocd/bin/openocd: no such file or directory
```

I suspect the setup is incorrect, some script has to run.

**Comment by earlephilhower** [comment]
Open OCD is installed in the `~/.arduino15/packages/rp2040/tools` so it looks like the `boards.txt` recipe is busted.  For now, please use a different upload method or add the appropriate symlink (temporarily).
