### ISSUE TITLE
Confused about missing branches and instructions

### ISSUE THREAD

**Issue by oflebbe** [earlephilhower/arduino-pico#578]
Hi I was trying to use to follow the Git https://arduino-pico.readthedocs.io/en/latest/install.html#installing-via-git instructions.

I am confused that there is only one branch in the repo, while releases on different tags, but these tags seem only remotely related to each other.

Instruction is to checkout `master` branch, but this branch seems to be both older and newer than the 1.x releases. 

- master misses `pico-extras` as an submodule, while the release tag  [1.13]([](https://github.com/earlephilhower/arduino-pico/releases/tag/1.13.3)l) has it. 
- master includes FreeRTOS, but that is missing at the release tag .

Is there a branch missing in the repo? Can you give some hints which additional steps are needed to enable the git branch in the IDE or to be used from a CLI ?

**Comment by earlephilhower** [comment]
Master has been updated but the docs haven't.  `Pico-extras` was removed a week ago when I merged a new I2S implementation.  The `README.md` file was updated, but I missed the docs update for that.

As for FreeRTOS, there is no special branch  It's in the main core and you just need to `#include <FreeRTOS.h>` to make it work.  You don't need to do anything special to get it, just follow the directions given.
