### ISSUE TITLE
Why is it not allowed to use our own VID?

### ISSUE THREAD

**Issue by Arya11111** [earlephilhower/arduino-pico#581]
Why is it not allowed to use our own VID?

![image](https://user-images.githubusercontent.com/50972783/168215845-4508022f-7d5c-4c09-873d-adcec4be1123.png)
![image](https://user-images.githubusercontent.com/50972783/168216108-7e876ff2-e6e0-46a4-a315-3598f4f2f22b.png)

**Comment by Arya11111** [comment]
Why is it not allowed to modify VID, but the PID is allowed to be modified?

**Comment by grandaspanna** [comment]
VID's need to be licensed/registered - arbitrarily picking a value can cause issues. This may help:
https://www.oshwa.org/2013/11/19/new-faq-on-usb-vendor-id-and-product-id/
