### ISSUE TITLE
Update Adafruit_TinyUSB_Arduino when PIO-USB support available

### ISSUE THREAD

**Issue by sfranzyshen** [earlephilhower/arduino-pico#582]
Add support for USB host/device implementation using PIO of raspberry pi pico (RP2040)
https://github.com/sekigon-gonnoc/Pico-PIO-USB

with the latest pull request to Pico-PIO-USB ... TinyUSB support has been added
https://github.com/sekigon-gonnoc/Pico-PIO-USB/pull/22 

and there is a active pull request to TinyUSB  itself ...
https://github.com/hathach/tinyusb/pull/1412

**Comment by earlephilhower** [comment]
As in #575, a PR would be appreciated.  Although I think that in this case it might make sense to make a separate Arduino library so you could use if here or in the MBED version.  I'm not really seeing any changes to the core needed for this at first glance.

**Comment by sfranzyshen** [comment]
I guess the changes really should be applied to the Adafruit_TinyUSB_Arduino project and then updated here ...

**Comment by kilograham** [comment]
I added a PR https://github.com/hathach/tinyusb/pull/1467

**Comment by sfranzyshen** [comment]
A new release of Adafruit_TinyUSB_Arduino has been released with "1.11.0 - Updated tinyusb to support rp2040 pio usb host"
https://github.com/adafruit/Adafruit_TinyUSB_Arduino/releases/tag/1.11.0

It's not clear to me how the Adafruit_TinyUSB_Arduino library is pulled into this project  ... or if any other changes would be needed to update it within this project ... 

So I don't know what would be needed to create a pull-request for this ... support?

**Comment by sfranzyshen** [comment]
sweet! thank you

**Comment by earlephilhower** [comment]
Let's wait on the PR merge before closing...

**Comment by sfranzyshen** [comment]
any chance we can get a bump (update) again on the Adafruit_TinyUSB_Arduino again? Not much has changed but an [DualRole](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/tree/master/examples/DualRole/device_info_rp2040) example has been added ...

**Comment by sfranzyshen** [comment]
thanks!
