### ISSUE TITLE
SerialPIO only 4 ports max

### ISSUE THREAD

**Issue by Stylesoftware** [earlephilhower/arduino-pico#592]
Using a pi pico.
The documentation at: [https://arduino-pico.readthedocs.io/en/stable/piouart.html](https://arduino-pico.readthedocs.io/en/stable/piouart.html) states up to 8 ports.
Any time I try to add the 5th port, at any pin, I get no tx.
I have not tested rx, but I suspect it is the same.

**Comment by earlephilhower** [comment]
Each bidir port needs two PIOs, and there are only eight PIOs on the chip.  Hence four bidir SerialPIOs max.  If you did only RX or Tx you could  get eight one way ports.

The docs could be clearer, but this is expected behaviour.

**Comment by Stylesoftware** [comment]
Thanks for the clarification.
