### ISSUE TITLE
Changing baudrate on a running PIO uart

### ISSUE THREAD

**Issue by PontusO** [earlephilhower/arduino-pico#593]
I am trying to change the baud rate of a PIO uart that has already been configured and started (PIOUart.begin(115200)).

My attempt is this:

  _serial->end();
  _serial->begin(baud);

Where _serial is a HardwareSerial object. This code works for the standard uart object but not for PIO uart.
Not sure if I am missing something here or if it is a bug.

**Comment by earlephilhower** [comment]
"Feature," maybe?   :laughing: 
https://github.com/earlephilhower/arduino-pico/blob/fc55e1e778ede6c92b07bdbc689cdda8fb739b87/cores/rp2040/SerialPIO.cpp#L256-L263

The PIO processor is never stopped and a new `begin` will probably allocate a new one (and cause contention on the I/O pins).  And if you do it too often you'll run out of PIO SMs, too.
