### ISSUE TITLE
User with space not working

### ISSUE THREAD

**Issue by ArielWolle** [earlephilhower/arduino-pico#6]
On windows I was dumb and have a user with a space in the name and now the file is going to the wrong place. Im sure the package is there
![image](https://user-images.githubusercontent.com/36164850/112224475-b4234b80-8c01-11eb-905a-4b95f06c6be2.png)

**Comment by ArielWolle** [comment]
its supposed to be "C:\Users\Ariel Wolle\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\0.9.0" but its currently "Wolle\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\0.9.0"

**Comment by ArielWolle** [comment]
changed account file name and now works it was definitely the space

**Comment by earlephilhower** [comment]
@ArielWolle yes, it's related to a space in the path and missing quotation marks around filenames.  

Can you try #7 out and report back?

If you can't use `git`, then just download the file https://raw.githubusercontent.com/earlephilhower/arduino-pico/40e014419586a29c47ab548dc0ad038c82979436/platform.txt , overwrite the `platform.txt` in the rp2040 directory you were looking at, and restart the IDE (restart required or Arduino will not read the new file).

**Comment by ArielWolle** [comment]
yup works perfectly thanks for the fix
