### ISSUE TITLE
packages downloaded everytime when run "pio run"

### ISSUE THREAD

**Issue by Huibean** [earlephilhower/arduino-pico#600]
Can I prevent this download everytime?
```shell
Processing pico (platform: https://github.com/maxgerhardt/platform-raspberrypi.git; board: pico; framework: arduino)
-----------------------------------------------------------------------------------------------------
Tool Manager: Installing https://github.com/earlephilhower/pico-quick-toolchain/releases/download/1.3.1-a/x86_64-w64-mingw32.arm-none-eabi-7855b0c.210706.zip
Unpacking  [####################################]  100%
```

**Comment by maxgerhardt** [comment]
The integration was updated, please update ([CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) -> `pio platform update https://github.com/maxgerhardt/platform-raspberrypi.git`) and use `platformio.ini` from `https://github.com/platformio/platform-raspberrypi/pull/36`, then this should not occurr anymore.
