### ISSUE TITLE
Update PlatformIO builder script + docs

### ISSUE THREAD

**Issue by maxgerhardt** [earlephilhower/arduino-pico#612]
Commits
* https://github.com/earlephilhower/arduino-pico/commit/420d669a4b82d5fdd2eeab4a856b6eec6929ea45
* https://github.com/earlephilhower/arduino-pico/commit/e3053f69f824398b3d615648d5e35ff244bf8378

require an update of docs in regards to 
* update toolchain link downloads for the new version
* how to activate stack protector

require an update of the builder script in regards to
* correctly linking against `-lstdc++` or `-lstdc++-exc` depending on whether exceptions are enabled (`-fexceptions` found in build flags)

(reminder for me later)

**Comment by earlephilhower** [comment]
Argh, sorry for breaking your build.  I need to do a Platform.IO job as part of CI. :(

**Comment by maxgerhardt** [comment]
Pretty sure it did not break the build (e.g., [`-lstdc++`](https://github.com/earlephilhower/arduino-pico/blob/master/tools/platformio-build.py#L96-L99) is sitll linked against), we just need to expose the new features to PlatformIO projects too by expanding the builder script.

**Comment by ivankravets** [comment]
Hi @maxgerhardt and @earlephilhower,

We have received 35 packages for review in the PlatformIO registry. What is the further fate of these packages?

https://github.com/platformio/platform-raspberrypi/issues/13 - Could you provide a PR with support for this core?

Thanks!

**Comment by maxgerhardt** [comment]
Ideally we'd want to have the pico-toolchain, Raspberrypi's tool-openocd version and `framework-arduinopico` in the registry, then I can reference stable versions in https://github.com/maxgerhardt/platform-raspberrypi and create the PR.

**Comment by ivankravets** [comment]
All packages are approved => https://registry.platformio.org/search?q=owner%3Aearlephilhower

Please tell us which packages are not required, we will remove them to keep the registry clean.

**Comment by ivankravets** [comment]
Do we need a custom ARM toolchain and OpenOCD?

**Comment by maxgerhardt** [comment]
Hmm I think I had problems with the tool-openocd-raspberrypi version tha PlatformIO had ([1 year old](https://registry.platformio.org/tools/platformio/tool-openocd-raspberrypi/versions)) when trying PicoProbe etc. support, so a newer build is needed.

And as far as I understand it, this core builds on custom configuration + features of the ARM toolchain, e.g. with exception code etc. (linking against `stdc++-exc` if exceptions are enabled etc), see e.g. [here](https://github.com/earlephilhower/pico-quick-toolchain/commits/master).

**Comment by ivankravets** [comment]
Thanks for the provided information. We would be thankful for the PR. I've just done a quick look at your fork and it looks good. The only note is to use `env.Exit(1)` in SCons scripts where you need to stop the building process.

**Comment by maxgerhardt** [comment]
@ivankravets PR created per above, more PRs for docs and builder script + doc update here will follow.
