### ISSUE TITLE
#if ARDUINO > 106 is false

### ISSUE THREAD

**Issue by Xyntexx** [earlephilhower/arduino-pico#622]
#if ARDUINO > 106 is false and ARDUINO is not set

I'm trying to use a library with arduino-pico.
Should this variable be set by arduino-pico?
The workaround is to set this environment variable manually.

**Comment by earlephilhower** [comment]
That is not a standard Arduino define, at least not now.  The current ArduinoAPI defines the API version using a different `#define`.

Arduino-Pico is at 1.2.0:
https://github.com/earlephilhower/arduino-pico/blob/c35210517678904a7aba215715f5a839407d0c64/cores/rp2040/api/ArduinoAPI.h#L23-L24

While the main Arduino API unstable/master is at 1.3.0
https://github.com/arduino/ArduinoCore-API/blob/e03b65374c614130aa1b11597e07b3b5089a726d/api/ArduinoAPI.h#L23-L24
