### ISSUE TITLE
SPI Clock frequency

### ISSUE THREAD

**Issue by hgs12345** [earlephilhower/arduino-pico#655]
I am using PicoSPI and found some strange behaviour. I don't think it is caused by PicoSPI library.
When I use a CPU Speed "125MHz" and configure SPI with:
PicoSPI0.configure(18, 19, 16, 17, 20000000, 0, false);
SPI clock frequency is 20MHz, as it should be.
But if I use CPU Speed "133MHz", SPI clock frequency seems to be reduced to 8MHz !!
I would like to use highest (reasonable) CPU Speed and SPI clock frequency.
Have you got an idea?
Thank you

**Comment by earlephilhower** [comment]
I just looked at the PicoSPI library and it doesn't use anything in the core to do the work.  It's calling the Pico-SDK directly for everything and not using the already defined and working `SPI` and `SPI`.  I suggest you post something in their repo w/a working sample to explain the problem.  FWIW, the SPI clocks are derived from other internal clocks, and when you're at 133 those clocks may not be able to divide closer to the desired frequency.  So, if he's using the SDK clock setting stuff, it may just be a limitation of the HW.  If he's got his own clk setting stuff, then maybe there's a problem or hardcoded value somewhere.

Good luck!
