### ISSUE TITLE
I2C Device issue - works with Arduino "Mbed OS RP2040 Boards"  but not this one

### ISSUE THREAD

**Issue by yingnanbao** [earlephilhower/arduino-pico#675]
Sorry for the editing - misclicked enter...
So here's the weird thing. I'm trying to use ROS on the pico and tried out the official Arduino core, it deals with the IMU over I2C like a charm, but crashes the pico with my ROS code. So I tried out the great core here and it deals with ROS like a charm, but now I'm not getting readings from the IMU. the code is identical so I'm scratching my head bald now trying to figure out why. The I2C scanner sees the IMU just fine, but just won't get me any reading. I also tried using a different I2C port but still no reading.
Could I get some help here please? Thank you!

Code below:

#include <Wire.h>
#include <I2Cdev.h>
#include <ArduinoHardware.h>
#include <ros.h>
#include <std_msgs/Float32MultiArray.h>

//MPU6050 Header
#include "MPU6050.h"
MPU6050 accelgyro;
int16_t ax, ay, az;
int16_t gx, gy, gz;

//Generics
unsigned long timer = 200;

//ROS Operations
ros::NodeHandle nh;

std_msgs::Float32MultiArray array_msg;

//ROS PUBLISHER
ros::Publisher motion_sensed("motion_sensed", &array_msg);

void setup() {
  Wire.setSCL(PICO_DEFAULT_I2C_SCL_PIN);//gp5
  Wire.setSDA(PICO_DEFAULT_I2C_SDA_PIN);//gp4
  Wire.begin();
  accelgyro.initialize();

  //ROS INIT
  nh.initNode();
  nh.advertise(motion_sensed);
}
void loop() {
  //Acquiring Readings MPU6050
  accelgyro.getMotion6(&ax, &ay, &az, &gx, &gy, &gz);
  float pong[3];
  pong[0] = ax;
  pong[1] = ay;
  pong[2] = gz;

  //ROS Send Sensor Data
  if (millis() > timer) {
    array_msg.data = pong;
    array_msg.data_length = 3;
    motion_sensed.publish( &array_msg );
    timer = millis() + 100;
  }
  nh.spinOnce();
}

**Comment by yingnanbao** [comment]
I also tried "Wire.setSCL()" and "Wire.setSDA()" to use other pins but no luck.

**Comment by earlephilhower** [comment]
One gotcha is that raw #s for pins in this repo correspond to the Pico chip GPIO, not the board GPIO.  So my first suggestion would be to triple check the Nano schematic and veriy the raw GPIO pin you passed into setSDA/setSCL is correct (also that the pin you selected is supported for the I2C interface...see https://cdn-learn.adafruit.com/assets/assets/000/099/339/original/raspberry_pi_Pico-R3-Pinout-narrow.png?1612915004 )  Then a logic analyzer would be handy to see the diffs between here and the other core...

**Comment by yingnanbao** [comment]
> One gotcha is that raw #s for pins in this repo correspond to the Pico chip GPIO, not the board GPIO. So my first suggestion would be to triple check the Nano schematic and veriy the raw GPIO pin you passed into setSDA/setSCL is correct (also that the pin you selected is supported for the I2C interface...see https://cdn-learn.adafruit.com/assets/assets/000/099/339/original/raspberry_pi_Pico-R3-Pinout-narrow.png?1612915004 ) Then a logic analyzer would be handy to see the diffs between here and the other core...

Thanks for the suggestion. I literally slept over it and woke up realizing it's probably the library is written for Arduino board so I found this "https://github.com/jrowberg/i2cdevlib/tree/master/RP2040".
Now both ROS and IMU are happy, so am I!
