### ISSUE TITLE
Software based Canbus

### ISSUE THREAD

**Issue by asevim** [earlephilhower/arduino-pico#684]
Hello,
First thank you for the great work. Do you have any plan to add [can2040](https://github.com/KevinOConnor/can2040/blob/master/docs/API.md#startup) library or is it possible ? I work on canbus with mcp2515 canbus controller. I think software based canbus great option with Arduino core. Thank you.

**Comment by earlephilhower** [comment]
Sorry, no.  I don't have any knowledge of CANbus and it is a pretty specialized field and library.

Looking at the code, it should be relatively simple to package in a library yourself and add to the Arduino Library Repo for others to find.  You might be able to import his raw code yourself and use it in sketched pretty simply, as well, if you're not up to making a wrapper class and library.  AFAICT all the SDK calls he uses we support.

Good Luck!
