### ISSUE TITLE
How to use multicore_launch_core1();

### ISSUE THREAD

**Issue by beegee-tokyo** [earlephilhower/arduino-pico#70]
Hello @earlephilhower 

Great work you are doing here, really appreciated.
I am just starting with the Pico and I guess I make a stupid mistake.
In the [Pico Examples](https://github.com/raspberrypi/pico-examples) is some code how to use the multicore functions.
But when I try to `#include "pico/multicore.h"` compilation fails with file not found. Am I missing something?

If it is not yet implemented here, that is ok, I can wait (or try to implement and do a PR). Just wanted to know before I put time into it.

**Comment by earlephilhower** [comment]
Please use 0.9.16, just released. It was just a matter of adding the proper include path to the platform file.  Good luck!

**Comment by beegee-tokyo** [comment]
@earlephilhower 

Thank you. Will update today and give you feedback.
