### ISSUE TITLE
lwip included on Pi Pico (without W) ?

### ISSUE THREAD

**Issue by SirSydom** [earlephilhower/arduino-pico#712]
With Core Version 2.3.3 i get a lot of redefinition warnings due to some defines from lwip that collide with our knx stack.

> 10 | #define htons(x)  ( (getbyte(x,0)<<8) | getbyte(x,1) )
>       |
> In file included from c:\users\dosp\appdata\local\arduino15\packages\rp2040\hardware\rp2040\2.3.3\pico-sdk\lib\lwip\src\include\lwip\ip_addr.h:41,
> from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/api/IPAddress.h:27,
> from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/api/ArduinoAPI.h:30,
> from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/Arduino.h:28,
> from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx\bits.h:29,
> from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx\transport_layer.cpp:7:

but I wonder why lwip is included because I did not select Pi Pico W and I did not include <WiFi.h>

**Comment by earlephilhower** [comment]
`IPAddress` now includes LWIP files, because it is encapsulating LWIP addresses.  I think that's the issue.  (IPAddress is part of the `Arduino.h` includes IIRC).

I'm pretty surprised you're just seeing it here.  LWIP is running most stacks in the back end, and I've even basically stolen the ESP8266 IPAddress infrastructure.  What cores do you work with?  I'd like to look at how they'd handle it...LWIP and things like the `htons` seem like they'd be everywhere.

The quick alternative is to add to your headers...
````
#ifdef XXXX
    #undef XXXX
#endif
#define XXXX ....
````

**Comment by SirSydom** [comment]
>  What cores do you work with?
you mean, besides your pico core?

I only work with your pico core and knx without ip, but in the knx stack there is also support for esp32 and [esp8266 ](https://github.com/thelsing/knx/blob/master/src/esp_platform.h) with knx-over-ip.. but I did not even try that for fun. 

I plan to adapt our stack for usage with the pico W and your core, but that is not the probem atm.

maybe it would be the best if we change the makros in the knx stack to knx_htons and so on..

**Comment by sstaub** [comment]
I think there should an dedicated IP6Address.h mentioned on another issue.
This can included to the WiFI library.

**Comment by earlephilhower** [comment]
There's no need, really.  With the default IPv4-only config there is normal IPv4 addressing build into IPAddress.  No extra RAM or code gets included.

When you want dual stack, since IPv4 uses the proper LWIP macros/fcns. to work with addresses, no code changes at all are required.  A `WiFiClient` can connect to `www.google.com` as `142.250.72.142` or `2607:f8b0:4007:810::200e` as appropriate, again w/o any changes.  @d-a-v did some amazing work on it!

**Comment by d-a-v** [comment]
Maybe an IPv6 example should help understanding how lwIP helps to make IP addressing easy, and how `IPAddress` can abstract everything without changing anything at the sketch level.
Here's the [esp8266's perfectible one](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/IPv6/IPv6.ino) with its output.

**Comment by SirSydom** [comment]
you lost me, does this ipv4/ipv6 stuff have any connection to my macro "problem" ?

I just wondered why lwip is included on a "non WiFi" pico.

**Comment by d-a-v** [comment]
I'm not the repo owner but usually issues with external libraries should be solved in external libraries as stated above.
Anyway maybe with a more detailed error message something can be made.
Indeed, lwIP defines `lwip_htons()` (not `htons()`) macro, so your truncated initial error message does not allow to isolate the source issue. Can you provide a more complete one ?

**Comment by SirSydom** [comment]
> Indeed, lwIP defines lwip_htons() (not htons()) macro

it does!
https://github.com/lwip-tcpip/lwip/blob/239918ccc173cb2c2a62f41a40fd893f57faf1d6/src/include/lwip/def.h#L117-L123


I think this should be complete now:

`
In file included from c:\users\dosp\appdata\local\arduino15\packages\rp2040\hardware\rp2040\2.3.3\pico-sdk\lib\lwip\src\include\lwip\ip_addr.h:41,
from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/api/IPAddress.h:27,
from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/api/ArduinoAPI.h:30,
from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/Arduino.h:28,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx\bits.h:29,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx_facade.h:3,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx.h:247,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\OpenKNX.h:2,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\OpenKNX.cpp:1:
c:\users\dosp\appdata\local\arduino15\packages\rp2040\hardware\rp2040\2.3.3\pico-sdk\lib\lwip\src\include\lwip\def.h:119: warning: "htons" redefined
119 | #define htons(x) lwip_htons(x)
      |
In file included from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx_facade.h:3,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx.h:247,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\OpenKNX.h:2,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\OpenKNX.cpp:1:
d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx\bits.h:10: note: this is the location of the previous definition
10 | #define htons(x)  ( (getbyte(x,0)<<8) | getbyte(x,1) )
      |
In file included from c:\users\dosp\appdata\local\arduino15\packages\rp2040\hardware\rp2040\2.3.3\pico-sdk\lib\lwip\src\include\lwip\ip_addr.h:41,
from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/api/IPAddress.h:27,
from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/api/ArduinoAPI.h:30,
from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/Arduino.h:28,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx\bits.h:29,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx_facade.h:3,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx.h:247,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\OpenKNX.h:2,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\OpenKNX.cpp:1:
c:\users\dosp\appdata\local\arduino15\packages\rp2040\hardware\rp2040\2.3.3\pico-sdk\lib\lwip\src\include\lwip\def.h:120: warning: "ntohs" redefined
120 | #define ntohs(x) lwip_ntohs(x)
      |
In file included from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx_facade.h:3,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx.h:247,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\OpenKNX.h:2,
from d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\OpenKNX.cpp:1:
d:\Data\Eigene Dokumente\Projekte\EIB\OpenKNX\SirSydom-Repos\SEN-UP1-8xTH\software\SNS-8xTH.P1\src\extlibs\knx\knx\bits.h:12: note: this is the location of the previous definition
12 | #define ntohs(x) htons(x)
      |


`

**Comment by SirSydom** [comment]
LWIP_DONT_PROVIDE_BYTEORDER_FUNCTIONS - if passed directly to the compiler by flag - solves the problem for me.

Maybe LWIP_DONT_PROVIDE_BYTEORDER_FUNCTIONS can be defined in the pico core ?

**Comment by earlephilhower** [comment]
Thanks for digging through to find it, but I am not so sure it is a good idea to remove such a common function.

`htons` and the family have been part of IP stacks since forever.  Anyone sending 16- or 32-bit numbers over the wire is supposed to use them.  

I just tried, and with WiFi the ESP32 and ESP8266 both define the macros.  They're also defined on every modern operating system from Windows to Mac to Linux to QNX

By using the TCP driver supplied versions, they're guaranteed to work no matter the byte-ordering of the host (i.e. your macro will have problems if you port to something w/a different byte order than the Pico).

So, I think the workaround for you, if you *really* want your own host-to-network macros, is to `#undef` them in your headers, and be aware of the porting implications.

**Comment by earlephilhower** [comment]
Or alternatively, maybe remove them with the macro you listed, byt define them you include `WiFi.h`...

So, regular apps would not see them, but if you wanted networking you'd get it as part of the package...

**Comment by SirSydom** [comment]
what's puzzling me is why there are no warning when I use the knx stack (it is a field bus for building automation, btw) together with an ESP8266... there is also lwip used.

I did not yet find out where exactly the lwip/def.h is included..

**Comment by d-a-v** [comment]
For both pico and esp8266, the following generates the same error as yours.
```
#include <IPAddress.h>
#define lwip(x) (x+1)
```
(and both are little endian if it matters)

**Comment by SirSydom** [comment]
good idea.

this minimal sketch (in Arduino IDE, to simply it):

`
#define htons(x) (x+1)


void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
`

on a Pico with Core 2.3.3:

> D:\Data\Eigene Dokumente\Arduino\sketch_jul26a\sketch_jul26a.ino:1: warning: "htons" redefined
>     1 | #define htons(x) (x+1)
>       | 
> In file included from c:\users\dosp\appdata\local\arduino15\packages\rp2040\hardware\rp2040\2.3.3\pico-sdk\lib\lwip\src\include\lwip\ip_addr.h:41,
>                  from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/api/IPAddress.h:27,
>                  from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/api/ArduinoAPI.h:30,
>                  from C:\Users\dosp\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.3\cores\rp2040/Arduino.h:28,
>                  from C:\Users\dosp\AppData\Local\Temp\arduino_build_574822\sketch\sketch_jul26a.ino.cpp:1:
> c:\users\dosp\appdata\local\arduino15\packages\rp2040\hardware\rp2040\2.3.3\pico-sdk\lib\lwip\src\include\lwip\def.h:119: note: this is the location of the previous definition
>   119 | #define htons(x) lwip_htons(x)
>       | 
> 

on a "Generic ESP8266 module" from ESP8266 Boards Core 3.0.2:

no warnings !


There must be a difference...
both ESP8266 core and your core use lwip headers in IPAddress.h there must be something else.
It seems that the ESP8266 core does NOT define the network makros globally.

**Comment by JAndrassy** [comment]
Originally in cores IPAddress.h was not in Arduino.h. Networking libraries included IPAddress.h from core in their headers together with Client.h, UDP.h.
but now for some reason IPAddress.h is included in the ArduinoCore-API in ArduinoAPI.h, which pico core includes in Arduino.h

**Comment by earlephilhower** [comment]
The difference is that the current `ArduinoCore-API`, which is what the Pico uses, includes IPAddress.h.  The ESP8266 was started before this change, so it doesn't include IPAddress.h.

**Comment by earlephilhower** [comment]
I think the net answer is that the macro name you've chosen is unfortunately a "well known" one and present in most newer cores and the wider ecosystem.

If the macro is doing exactly what `htons()` is doing, then I really would recommend just defining your version if there is no version defined, a la:
````
#ifndef htons
  #define htons(x) (....)
#endif
````

If the macro is called `htons` but doesn't do what `man htons` reports it doing, then maybe you might want to reconsider the name, if only to help avoid confusion by other folks coming to your code?

**Comment by d-a-v** [comment]
FWIW, arduino official ethernet library [had accepted this patch](https://github.com/arduino-libraries/Ethernet/commit/0d5019a412857e6b221dd45c2c93633c7b62b276#diff-53c0ae9f9055691d4b15488dda76a3faa27e49a5f7899fb025409a253538dc08).

**Comment by earlephilhower** [comment]
Closing since this seems to be a works-as-intended for modern Arduino, with a potential patch for user code.
