### ISSUE TITLE
Ignore DTR on Serial USB

### ISSUE THREAD

**Issue by lu7did** [earlephilhower/arduino-pico#718]
Hello,

I've to deal with programs that do not raise DTR and thus the rp2040 is not sending data to them. Is there any way to make the Serial USB to ignore the value of  DTR as a condition to send data?

Thanks in advance, Pedro

**Comment by kholia** [comment]
Possibly related: https://github.com/hathach/tinyusb/discussions/932.

**Comment by earlephilhower** [comment]
Right now, that is not supported by the Pico-SDK USB driver.  You may want to follow up on the issue @kholia listed in the TinyUSB repo, and if you have specific tests/etc. to help hathach understand and reproduce that would be very helpful.

For now, this isn't supported in the Pico-SDK which is what we use for basic USB processing, sorry,
