### ISSUE TITLE
Linked files in ELF using absolute path?

### ISSUE THREAD

**Issue by ninjas28** [earlephilhower/arduino-pico#733]
There seems to be a bunch of the source files linked in the ELF file that use your absolute filepath.
Using the Ozone debugger I see a bunch of broken source files:

```
File.Open ("/home/earle/Arduino/hardware/pico/rp2040/pico-sdk/src/rp2_common/hardware_gpio/include/hardware/gpio.h");
File.Open ("/home/earle/Arduino/hardware/pico/rp2040/pico-sdk/src/rp2_common/hardware_gpio/include/hardware/gpio.h"): File not found.
File.Open ("/home/earle/Arduino/hardware/pico/rp2040/system/arm-none-eabi/arm-none-eabi/include/sys/_stdint.h");
File.Open ("/home/earle/Arduino/hardware/pico/rp2040/system/arm-none-eabi/arm-none-eabi/include/sys/_stdint.h"): File not found.
File.Open ("/workdir/arm-none-eabi.x86_64/arm-none-eabi/include/sys/reent.h");
File.Open ("/workdir/arm-none-eabi.x86_64/arm-none-eabi/include/sys/reent.h"): File not found.
```
These are just a couple of about 260 or so errors I get.

**Comment by earlephilhower** [comment]
That’s what happens when you build the SDK and newlib.  You can use the gdb replace path commands to point those paths to the copies in your system.

see https://sourceware.org/gdb/onlinedocs/gdb/Source-Path.html#set-substitute_002dpath
