### ISSUE TITLE
Timer Confusion...

### ISSUE THREAD

**Issue by tbillion** [earlephilhower/arduino-pico#763]
i love your library way better than the mbed one, great work!

does the code use any timer on the pico for any internal functions i have been attempting to use : https://github.com/khoih-prog/RPI_PICO_TimerInterrupt and the only timer it will allow is timer 0, then if i switch to mbed i can use all the timers, i didnt know if this had something to do with the differences with how the code worked or ...
thanks!

**Comment by earlephilhower** [comment]
Sorry, you'll need to open a request there to see what exactly he's doing.  The core uses whatever timer resources the Pico SDK uses to provide the `alarm` module.
