### ISSUE TITLE
Do the wi-fi extensions support soft access points?

### ISSUE THREAD

**Issue by technoblogy** [earlephilhower/arduino-pico#767]
On the ESP32 and ESP8266 you can set up a soft access point with **WiFi.softAP()** but this call doesn't seem to exist in the **Raspberry Pi Pico W** core. Is it there under a different name? If not, any plans to support it?

**Comment by earlephilhower** [comment]
AP mode is supported, but not those ESP-specific APIs yet.  A simple wrapper will suffice for them.  Some things (like channel(!!)) are not supported by the CYW43 driver yet, but basic starting/stopping should be a 1-liner.

We're using the WiFi/WiFiNINA compatible `WiFi.beginAP()` as documented https://www.arduino.cc/reference/en/libraries/wifinina/wifi.beginap/ and elsewhere.

**Comment by technoblogy** [comment]
Thanks! I'll try those out.

**Comment by technoblogy** [comment]
That works nicely - thank you!
