### ISSUE TITLE
MAC Address returned with octets reversed

### ISSUE THREAD

**Issue by cfilipem** [earlephilhower/arduino-pico#811]
I've noticed that in my Pico W, the `String macAddress(void)` method in WiFiClass is returning the NIC MAC Address with the octets reversed.

Looking in `libraries/WiFi/src/WiFiClass.h` I see that the implementation is deliberately reversing the octets.
Is this only happening in my board?

`
sprintf(buff, "%02x:%02x:%02x:%02x:%02x:%02x", mac[5], mac[4], mac[3], mac[2], mac[1], mac[0]);
`

**Comment by earlephilhower** [comment]
Would you like to do a PR to reverse the printing order?

**Comment by cfilipem** [comment]
Created PR #812 for this
