### ISSUE TITLE
Own library error

### ISSUE THREAD

**Issue by fredykoci** [earlephilhower/arduino-pico#847]
Hi, I have pico and you boards definitions installed. I am using arduino ide 1.8.2 and I created own library but pico do not start the program properly. But when I remove class declaration code works normally

**Comment by earlephilhower** [comment]
Without a complete MCVE, there is no way for anyone to help you.  Also, we need a complete explanation of what happens, including compiler messages if it's a build error.

**Comment by earlephilhower** [comment]
Closing since no update or MCVE
