### ISSUE TITLE
replace() function is unstable

### ISSUE THREAD

**Issue by maximeh2** [earlephilhower/arduino-pico#848]
The replace() function is unstable. It does not support when it has to replace several identical characters.

https://forums.raspberrypi.com/viewtopic.php?t=339932

**Comment by earlephilhower** [comment]
That thread has lots of back and forth, can you post some code with expected results?

In any case, we use the official unmodified ArduinoCore-API so if this is a `String` issue you need to bring it up with the Arduino folks, not here.  But let's get some code first to verify.

**Comment by earlephilhower** [comment]
No MCVE in a week, closing.
