### ISSUE TITLE
Use command line to build uf2 file

### ISSUE THREAD

**Issue by PhantomRay** [earlephilhower/arduino-pico#855]
Hi everyone, not sure if this has been asked before (didn't find it in issues) - how do I build uf2 file without using Arduino IDE?
Many thanks.

**Comment by JamesNewton** [comment]
FYI, at least on Linux systems, and when using Arduino IDE v2 (2.3.2 in my case) the .uf2 file from the regular build is kept under the /tmp/arduino/sketches/ folder, in a randomly named subfolder. It will be <project>.ino.uf2
