### ISSUE TITLE
Compile error when using other than Serial for Debug port (Raspberry Pi Pico)

### ISSUE THREAD

**Issue by Colatino** [earlephilhower/arduino-pico#882]
Dear @earlephilhower,

When I switch the Debug port to Serial1 or Serial2 the compiler gives the following:

> ...\rp2040\hardware\rp2040\2.5.4\cores\rp2040/CoreMutex.h: In constructor 'CoreMutex::CoreMutex(mutex_t*, bool)':
<command-line>: error: 'Serial1' was not declared in this scope; did you mean 'Serial'?
...\rp2040\hardware\rp2040\2.5.4\cores\rp2040/debug_internal.h:30:34: note: in expansion of macro 'DEBUG_RP2040_PORT'
   30 | #define DEBUGCORE(fmt, ...) do { DEBUG_RP2040_PORT.printf(fmt, ## __VA_ARGS__); DEBUG_RP2040_PORT.flush(); } while (0)
      |                                  ^~~~~~~~~~~~~~~~~
...\rp2040\hardware\rp2040\2.5.4\cores\rp2040/CoreMutex.h:42:25: note: in expansion of macro 'DEBUGCORE'
   42 |                         DEBUGCORE("CoreMutex - Deadlock detected!\n");
      |                         ^~~~~~~~~
exit status 1
Compilation error: exit status 1

- Steps to reproduce the error:
1. Create an empty sketch (the code doesn't seem to matter)
2. Set board to Raspberry Pi Pico
3. Set debug port to Serial1 or Serial2
4. Set debug level to All or Core
5. Verify/Compile

**Comment by earlephilhower** [comment]
Thanks for the clear steps to reproduce.  Simple fix in #883.
