### ISSUE TITLE
noise after tone remains

### ISSUE THREAD

**Issue by ChrisVeigl** [earlephilhower/arduino-pico#886]
i found that the connected buzzer emits a barely noticable noise after a call to

void tone(uint8_t pin, unsigned int frequency, unsigned long duration)

i think it could fix it by adding `noTone(tone->pin);` 
after line
https://github.com/earlephilhower/arduino-pico/blob/4cc6c36c37eae0764b63a3476a98544f308a0972/cores/rp2040/Tone.cpp#L45

PS: if you prefer i can fork/pull request

**Comment by earlephilhower** [comment]
Thanks for the description and debug, but I think your problem is analog noise, not the PIO.

The line you have shown calls `pio_sm_set_enabled(false)` which per https://raspberrypi.github.io/pico-sdk-doxygen/group__hardware__pio.html#gaa47ec4090dcdc251e44bf4e4cb89a7bc stops the SM (the actual thing making the tone).  So, the pin at that point will no longer toggle under the PIO's countrol.

**Comment by earlephilhower** [comment]
Maybe the `pinMode; digitalWrite` might make sense, though.  Potentially the I/O goes tri-state when under the control of a PIO device which is not running.  So, how about doing a PR that includes the `pinMode(OUTPUT); digitalWrite(low)`?

**Comment by ChrisVeigl** [comment]
hi!
i added  ` pinMode(tone->pin, OUTPUT);   digitalWrite(tone->pin, LOW); ` instead of `noTone(tone->pin);`

but this seems to compromise the function: now only the first call to 'tone ()'  produces an audible result ..

**Comment by earlephilhower** [comment]
Did it remove the noise, though?  It may be a little complicated (because we can't call `noTone` from an IRQ because it uses functions that aren't in RAM) but I can hack in something appropriate to make it work, if that was the underlying problem.

Thx again for the debug!

**Comment by ChrisVeigl** [comment]
yes - it seems to remove the noise.
no problem! - thanks for the great work - the RP2040 core is epic :)

**Comment by earlephilhower** [comment]
@ChrisVeigl can you try out #887 ?  I don't have a speaker handy (used it on my last PC build!) but it's basically doing the hard-LOW-set on `tone` timeout followed by re-initting the I/O direction/control on a new `tone()` call.

**Comment by ChrisVeigl** [comment]
that does the trick, indeed!
nice :)

Am Do., 29. Sept. 2022 um 21:48 Uhr schrieb Earle F. Philhower, III <
***@***.***>:

**Comment by earlephilhower** [comment]
Great, thanks for the follow-up!
