### ISSUE TITLE
ILabs Challenger 2040 WiFi

### ISSUE THREAD

**Issue by ITstreet1** [earlephilhower/arduino-pico#889]
While trying to compile a simple Scan example from the lib, I get this error:
C:\Users\:usr:\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.3.2\libraries\lwIP_Ethernet\src/LwipIntfDev.h:59:29: error: 'SS' was not declared in this scope
   59 |     LwipIntfDev(int8_t cs = SS, SPIClass& spi = SPI, int8_t intr = -1) :
      |                             ^~
exit status 1

This trows for any WiFi example from the lib

**Comment by revell1** [comment]
Looking at your path directory, it looks like you are using an old release of 2.3.2. If so, try the latest and see if that makes any difference.

**Comment by ITstreet1** [comment]
Updated lib

C:\Users\usr\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\2.5.4\libraries\lwIP_Ethernet\src/LwipIntfDev.h:61:29: error: 'SS' was not declared in this scope
   61 |     LwipIntfDev(int8_t cs = SS, SPIClass& spi = SPI, int8_t intr = -1) :
      |                             ^~

**Comment by JAndrassy** [comment]
lwIP_Ethernet should work with a W5500 on any RP2040, but I am not sure if the library is ready

**Comment by ITstreet1** [comment]
> 

I just try to verify. Can someone try to verify any sketch from board examples about WiFi?

**Comment by PontusO** [comment]
Dejan, you should be able to run any example from the wifiespat library 
package, we've tested all examples without any issues.

Having the wifi library (for the rpi w) integrate into the board support 
package automatically makes it available for all rp2040 boards. That is 
just an Arduino thing.

Den 3 oktober 2022 15:03:38 skrev Dejan Petrović ***@***.***>:

**Comment by JAndrassy** [comment]
> @JAndrassy
> 
> I just try to verify. Can someone try to verify any sketch from board examples about WiFi?

the WiFi library bundled with the boards package is only for Raspberry's Pico W board with a CYW43439 WiFi module on board

**Comment by ITstreet1** [comment]
@JAndrassy 
This one has ESP8285 but I get the point
@PontusO 

This clears a lot. Thank you, guys!

**Comment by JAndrassy** [comment]
off topic: @PontusO I think for the ESP8285 AT 1.7.5 would be a better option than AT2. AT 2 for esp82xx stopped at 2.2.0 and has many problems

**Comment by ITstreet1** [comment]
Just in case others stumble upon this:

```
#include <ChallengerWiFi.h>
#include <WiFiEspAT.h>
void setup() {
  Serial.begin(115200);
  while (!Serial2);
  Serial2.begin(115200);
  WiFi.init(Serial2);
  WiFi.begin("ssid", "pass");
  Serial.println("Waiting for connection to WiFi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
    Serial.print('.');
  }
  Serial.println();
  Serial.println("Connected to WiFi network.");
}

void loop() {
  // put your main code here, to run repeatedly:

}
```

This is a basic sketch for a WiFi connection. Works like a charm.

**Comment by earlephilhower** [comment]
Looks like this was cleared up, thanks guys.  If the Challenger WiFi board needs a different `pins_arduino.h` please do submit a PR.
