### ISSUE TITLE
Serial Communication

### ISSUE THREAD

**Issue by shamirtahir50** [earlephilhower/arduino-pico#943]
void setup() {
  Serial.begin(115200);

}

void loop() {

  if (Serial.available()){
      String receivedValues=Serial.readStringUntil('\n');
      Serial.println(receivedValues);
    
}

I am just trying to receive data on RX0, and TX0 on pin 16 17.
How is it done on Pico?
Actually want to communicate between ESP32 and Raspberry pi pico.

**Comment by earlephilhower** [comment]
Use `Serial1` or `Serial2` and set the pins using the documentation.  https://arduino-pico.readthedocs.io/en/latest/
