### ISSUE TITLE
Problems with default pwm resolution

### ISSUE THREAD

**Issue by jjsch-dev** [earlephilhower/arduino-pico#955]
Hello, using the default resolution:

static uint32_t analogScale = 255;
static uint32_t analogFreq = 1000;

analogWrite(10, 255); outputs about 25 percent on the output pin.

![analogwrite_255](https://user-images.githubusercontent.com/55675185/199823360-7eb6a5cc-1f7f-42e2-93ad-fb418d56cd70.PNG)

analogWrite(10, 512); outputs about 50 percent on the output pin.

![analogwrite_512](https://user-images.githubusercontent.com/55675185/199823467-be4aa351-3b5e-4762-9a87-70358f398325.PNG)

analogWrite(10, 100); outputs about 99 percent at the output pin.

![analog_write_1000](https://user-images.githubusercontent.com/55675185/199823550-6e7ce004-1fed-4da5-ba43-056a3c34a027.PNG)

analog write (10, 1020); outputs 100 percent on the output pin.

![analogwrite_1020](https://user-images.githubusercontent.com/55675185/199823690-4db8c277-ad84-4b8e-9d88-1e2c5348df75.PNG)

Is there a way to set the resolution to be 8bit at frequencies below 1.5KHZ?

**Comment by earlephilhower** [comment]
This is an interesting problem, thanks for the graphs.  Does look like a bug from the images.

There's code which (should) handles this in most cases, but maybe we've hit an overflow case here (`analogWritePseudoScale`):
https://github.com/earlephilhower/arduino-pico/blob/40855c90fb1d37a7544c1324c291a2413ff48bdc/cores/rp2040/wiring_analog.cpp#L81-L101

**Comment by earlephilhower** [comment]
There is some debug info from the core to quickly verify this.  

Can you please re-run your testing with `Tools->Debug Port->Serial` and `Tools->Debug Level->Core` and capture the logs (you may need a `delay(5000);` at the head of your `setup()` to make sure the printouts don't start before the PC and the Pico negotiate all the USB stuff....otherwise you may miss the `DEBUGCORE` messages shown above.)

**Comment by jjsch-dev** [comment]
Thank you for taking the time to review the report, you do a great job.

Turn on core debugging and these are the results for: analogWrite(255):

10:04:42.270 -> Adjusting analogWrite values PS=2, scale=510
10:04:42.270 -> Adjusting analogWrite values PS=3, scale=1020

**Comment by earlephilhower** [comment]
That's very odd and seems to indicate it should work.
https://github.com/earlephilhower/arduino-pico/blob/40855c90fb1d37a7544c1324c291a2413ff48bdc/cores/rp2040/wiring_analog.cpp#L103-L104

`analogWritePseudoScale` = 3, `analogWriteSlowScale` = 1 (the default) so it should take your inputs and shift left (3-1 = 2) or convert it to 0...1023 automatically.

I'll need to single step through the code and see what's going on.  Can you confirm your code is like this:

````
analogWriteRange(255);
analogWriteFreq(1000);
analogWrite(10, 255);
````

**Comment by fjansson** [comment]
@jjsch-dev more questions: 
* Are you using the latest version of arduino-pico, or which version?  
* What is your system clock frequency (set by "CPU Speed" in tools menu)? 
* When you measured the signal, did you by any chance use analogWrite on another pin simultaneously with other frequency or analogRange? (because the pins aren't all independent, some combinations of pins affect each other)

The debug output you got looks ok to me, as if the code is working as it should. 

Maybe there's a typo in the third test, so it should read analogWrite(10, **1000**); outputs about 99 percent at the output pin. Then your measurements look as if the range would be about 1020.

**Comment by earlephilhower** [comment]
@fjansson I think you just described a bug, then.  Might not be what is happening here, need more info, but I see how the change from "all pins initted to same PWM settings" to "allow individual PWM settings per pin" has busted things.

When there was only 1 setting for all pins, then a single `analogWritePrescale` and `analogWriteSlowScale` is needed.

Now, we need one of those variable for each PWM slice, or you could set slice A to 10khz@1024, set slice B to 1khz@255, and then have a write to slice A have the wrong setting...

**Comment by jjsch-dev** [comment]
@fjansson thanks for the tips.

- Yes, I use the last version from Arduino Board Manager.
![pico_version](https://user-images.githubusercontent.com/55675185/200059335-237a1121-37f8-4ac6-8681-6bb5354e26d1.jpeg)

- The system clock frequency is: 133 Mhz.
- Yes, I use two pin with the same PWM value.
- you're right, it's a typo, it should be analogWrite(10, 1000);

@earlephilhower to avoid polluting the sample (my fault), I wrote the following imo with the pwm functions. And I found that when I use a single analogWrite(), the output behaves as expected. But with two, as @fjansson suggests, the strange behavior appears.

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  delay(5000);
  
  analogWriteRange(255);
  analogWriteFreq(1000);
}

void loop() {
  // put your main code here, to run repeatedly:
  delay(1000);

  analogWrite(10, 255);
  analogWrite(11, 255);
}

These are the screenshots with the different options:
analogWrite(10, 255);
//analogWrite(11, 255);
![analowrite_pin10_255](https://user-images.githubusercontent.com/55675185/200062408-a7768a41-8da8-4c57-adb9-618281f06407.PNG)

analogWrite(10, 255);
analogWrite(11, 255);
![analogwrite_pin10-11_255](https://user-images.githubusercontent.com/55675185/200062651-4dcf5de0-7613-4fc9-8846-afee226b9c01.PNG)

analogWrite(10, 127);
analogWrite(11, 127);
![analowrite_pin10-11_127](https://user-images.githubusercontent.com/55675185/200062775-26376f8a-72f7-4aa8-b9ea-84f5c08d490c.PNG)

analogWrite(10, 127);
//analogWrite(11, 127);
![analowrite_pin10_127](https://user-images.githubusercontent.com/55675185/200062912-da8e8597-e955-4fca-97a7-834b9aeba842.png)

//analogWrite(10, 127);
analogWrite(11, 127);
![anolowrite_pin11_127](https://user-images.githubusercontent.com/55675185/200063062-3828f0c7-2fd9-42b8-b778-d8080808ca67.PNG)

**Comment by earlephilhower** [comment]
I seem to have the world's flakiest noname 8-bit logic analyzer clone, so testing for me is difficult.  It's hard to know if there's a PWM issue when the pins themselves seem to read out with lots of random noise.  :sob: 

That said, I've got #962 for you all to try out on your apps and report back on.  The PWM devices are slice-based, not pin-based, so this change pretty minimally ensures the init isn't duplicated when you're hitting the same slice (as in pins 10, 11 in the failing test).

If you could give it a go and let me know if this clears things up I would much appreciate it!

**Comment by earlephilhower** [comment]
Latest push on #962 seems to clear it up.  I've written 3 pins in 2 different slices and the PWM values all look good.  Please test w/your own app and report back.

**Comment by jjsch-dev** [comment]
@earlephilhower  I have updated the arduinopico version to the ppp branch and compiled the code successfully. I see that you added the variable static bool `scaleInitted = false;` in the `wired_analog.cpp` file, which I assume will not re-init the pwm range when the `analogWrite` function is called more than once.

Unfortunately, I don't have the oscilloscope at home to take the measurements right now, butr I'll do them no later than Monday and send them to you.

I wonder what the world's flakiest unnamed 8-bit logic analyzer clone is? :thinking:

**Comment by revell1** [comment]
This appears to have fixed (restored) my motor control WRT V2.6.1 (also linked with issues #962 and #961)

**Comment by earlephilhower** [comment]
Thanks!  I'll wait for @jjsch-dev 's report for the merge.

**Comment by jjsch-dev** [comment]
@earlephilhower  Good job, this push #962 fixed the problem. Below I put the captures for: `analogWriteRange(255);` and `analogWriteFreq(1000);`. Thanks for your time.

analogWrite(10, 255);
analogWrite(11, 255);
![analogwrite_10-11_255](https://user-images.githubusercontent.com/55675185/200322581-ce2f14a7-3e94-406d-b98f-b8cb079499a9.PNG)

analogWrite(10, 127);
analogWrite(11, 255);
![analogwrite_10_127_11_255](https://user-images.githubusercontent.com/55675185/200322670-4612ab48-8a38-444c-a5a5-d8b946318cee.PNG)

analogWrite(10, 255);
analogWrite(11, 127);
![analogwrite_11_127_10_255](https://user-images.githubusercontent.com/55675185/200322792-64af73e3-d66d-4041-8153-12e4b6498cb9.PNG)

analogWrite(10, 127);
analogWrite(11, 127);
![analogwrite_10-11_127](https://user-images.githubusercontent.com/55675185/200322928-f925c818-3fff-4cfe-bd12-9e1bd348a819.PNG)
