### ISSUE TITLE
Windows 7 sometimes does not recognize the device as serial port

### ISSUE THREAD

**Issue by PsychoXIVI** [earlephilhower/arduino-pico#96]
Windows 7 sometimes does not recognize the device as serial port, even after fresh reinstalling using BOOTSEL button. You still can upload sketch using BOOTSEL mode manually, but it requires disconnecting device each time. Simply, the issue disable easy upload and auto-restart feature. 

There is "ArduinoPico" unrecognized device in the device manager list with ID: `USB\VID_2E8A&PID_000A&REV_0100` or similar. I am using Arduino IDE 1.8.13. Using different USB port didn't help. Restarting the IDE didn't help. On Windows 10 the same board works without any problems.

I found **solution to make it work also on Windows 7**:
![image](https://user-images.githubusercontent.com/23557839/114192705-185a4500-994e-11eb-9a16-e12b91a69fba.png)
(from https://www.onetransistor.eu/2021/02/set-up-raspberry-pi-pico-for-microphyton.html , btw: I used "Install driver")

Tested on Windows 7 that had previously this issue. Maybe you can add it to README or somewhere?

**Comment by prenticedavid** [comment]
Thanks for the tip.   I have a Win7-32 laptop.   This gets a Serial Terminal and Program Upload.    Opening the Arduino Serial Terminal does **not** reset the Pico.
If you upload when the Serial Terminal is open you tend to get an Error when it resets baud rate.
If you upload with a Closed Serial,   you need the program to wait e.g. with `while (!Serial) ;`

But my big problem is Win10-64 Desktop PC.
I can upload if I put the Pico into Boot mode.
But the Serial will only run if I toggle the power.

After toggling power I see PicoArduino (COM23) in the Device Manager.
Properties say: usbser.sys
Driver Version: 1.0.0.0
Digital Signer: USB\VID_2E8A&PID_000A (libwdi autogenerated)

Has Win10 installed the correct Driver ?

David.

**Comment by Andy2No** [comment]
I've just gone through this process, and that wasn't exactly what I saw, so here are some screenshots which might make it clearer to someone else.  The serial port was shown as PicoArduino.

Zadig (1) - Immediately after plugging in the Pi Pico, Zagig sees PicoArduino which shows as no driver, WinUSB

![Zadig (1) - PicoArduino shows as no driver, WinUSB](https://user-images.githubusercontent.com/8021302/117580636-d0674300-b0f0-11eb-92cf-06169384b1dc.gif)

Zadig (2) - PicoArduino (2E8A) needs to be set to USB Serial (CDC), using the arrow keys next to the driver type, then pressing Install Driver.

![Zadig (2) - PicoArduino (2E8A) needs to be set to USB Serial (CDC)](https://user-images.githubusercontent.com/8021302/117580647-df4df580-b0f0-11eb-8e73-7e401dbca189.gif)

Zadig (3) - PicoArduino (2E8A) after pressing Install Driver it looks like this:

![Zadig (3) - PicoArduino (2E8A) after presing Install Driver - USB Serial (CDC)](https://user-images.githubusercontent.com/8021302/117580660-eaa12100-b0f0-11eb-8e4a-14230ad966ac.gif)
