### ISSUE TITLE
"Arduino Nano RP2040 Connect" board associated with PID of Nano Every

### ISSUE THREAD

**Issue by per1234** [earlephilhower/arduino-pico#968]
https://github.com/earlephilhower/arduino-pico/blob/ea5f8241e36c21f59123c12127f238451636f9fa/boards.txt#L5483-L5484

```text
arduino_nano_connect.vid.0=0x2341
arduino_nano_connect.pid.0=0x0058
```

`2341:0058` is the VID/PID pair of the ATmega4809-based [**Nano Every**](https://store.arduino.cc/products/arduino-nano-every) board:

https://github.com/arduino/ArduinoCore-megaavr/blob/1.8.7/boards.txt#L44-L45

This association causes the port of the Nano Every to be identified incorrectly as "Arduino Nano RP2040 Connect" in Arduino IDE/Arduino CLI when the "Raspberry Pi Pico/RP2040" boards platform is installed, which causes confusion to the users ([example](https://forum.arduino.cc/t/board-info-returning-incorrect-board-name/1050793)).

The official VID/PID pairs of the "Arduino Nano RP2040 Connect" board are listed here:

https://github.com/arduino/ArduinoCore-mbed/blob/a0b596d7c1d8eb1a59c90ab8d0a8fef615d20687/boards.txt#L343-L350

```text
nanorp2040connect.vid.0=0x2341
nanorp2040connect.pid.0=0x005e
nanorp2040connect.vid.1=0x2341
nanorp2040connect.pid.1=0x805e
nanorp2040connect.vid.2=0x2341
nanorp2040connect.pid.2=0x015e
nanorp2040connect.vid.3=0x2341
nanorp2040connect.pid.3=0x025e
```

(note the primary PID is `0x005e`, NOT `0x0058`)

I didn't submit a PR for this because some of the PIDs resulting from [the system of programmatically generating an array of additional PIDs by iterating from the base PID](https://github.com/earlephilhower/arduino-pico/blob/ea5f8241e36c21f59123c12127f238451636f9fa/tools/makeboards.py#L114-l120) do not reflect the reality of the PIDs Arduino has actually allocated to the Nano RP204 Connect.

**Comment by earlephilhower** [comment]
New PR moves back to your defined ones:
````
arduino_nano_connect.vid.0=0x2341
arduino_nano_connect.pid.0=0x005e
arduino_nano_connect.vid.1=0x2341
arduino_nano_connect.pid.1=0x805e
arduino_nano_connect.vid.2=0x2341
arduino_nano_connect.pid.2=0x015e
arduino_nano_connect.vid.3=0x2341
arduino_nano_connect.pid.3=0x025e
````
